# HW7: Time-series features + JSONB event-log у PostgreSQL

Дзеркало у **Google Colab** середовищі:

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1qprxAuC7uMkPAsYd0d-SygUTQzJY_Bky?usp=sharing)


**Pipeline:**
1. Setup PostgreSQL у Colab
2. $\rightarrow$ NYC TLC Yellow Taxi (офіційний Parquet) або stub-fallback
3. $\rightarrow$ daily-агрегат `t7_hw_taxi_daily`
4. $\rightarrow$ lag / rolling / expanding features (`v_t7_hw_taxi_features`)
5. $\rightarrow$ JSONB event-log `t7_hw_events`
6. $\rightarrow$ `@>`, `?`, `?|`, JSONPath
7. $\rightarrow$ GIN / expression B-tree + `EXPLAIN (ANALYZE, BUFFERS)`
8. $\rightarrow$ JSONB vs normalized
9. $\rightarrow$ Reflection.

**Відтворюваність:**
> кожен SQL-блок починається з `DROP ... IF EXISTS` (view видаляється *до* таблиці, від якої він залежить $-$ інакше повторний Run All упав би на `DROP TABLE`, бо сервер PostgreSQL переживає рестарт kernel);

> семплінг даних $-$ з фіксованим `random_state`;

> stub $-$ з фіксованою датою, а не `CURRENT_DATE`.

> Notebook розрахований на **Runtime $\rightarrow$ Restart & Run All** без ручних дій.

## 1. Setup і typed-схема Olist

### 1.1. Запуск PostgreSQL і перевірка підключення

In [1]:
# PostgreSQL in Colab
!apt-get -qq update > /dev/null
!apt-get -qq install -y postgresql > /dev/null
!service postgresql start
# password for the user
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

!pip install -q sqlalchemy psycopg2-binary pandas pyarrow ipython-sql

import os
import re
import io
import time
from urllib.request import urlretrieve

import pandas as pd
import psycopg2
from sqlalchemy import (
    create_engine,
    text
)

DSN = "postgresql://postgres:postgres@localhost:5432/postgres"
engine = create_engine(
  "postgresql+psycopg2://postgres:postgres@localhost/postgres",
  isolation_level="AUTOCOMMIT",
)

def run_sql(sql: str) -> None:
    """
        Виконує багатостатементний SQL-скрипт (DDL + DML) в autocommit-режимі.
    """
    conn = psycopg2.connect(DSN)
    conn.autocommit = True
    try:
        with conn.cursor() as cur:
            cur.execute(sql)
    finally:
        conn.close()

PLANS: dict[str, list[str]] = {}  # label -> list of plan lines (для зведеної таблиці)
RANDOM_STATE_VALUE: int = 42

def explain(label: str, sql: str) -> None:
    """
        EXPLAIN (ANALYZE, BUFFERS) + друк плану + збереження для порівняння.
    """
    conn = psycopg2.connect(DSN)
    conn.autocommit = True
    try:
        with conn.cursor() as cur:
            cur.execute("EXPLAIN (ANALYZE, BUFFERS) " + sql)
            lines = [r[0] for r in cur.fetchall()]
    finally:
        conn.close()
    PLANS[label] = lines
    print(f"===== {label} =====")
    print(sql.strip())
    print("-" * 80)
    print("\n".join(lines))

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
[ OK ]
ALTER ROLE

In [2]:
# Завантажуємо SQL розширення
%load_ext sql
# Підключаємося до локальної бази даних postgres
%sql postgresql+psycopg2://postgres:postgres@localhost:5432/postgres
# Перемикаємо стиль оформлення на той, що підтримується поточною версією PrettyTable
%config SqlMagic.style = '_DEPRECATED_DEFAULT'
%config SqlMagic.displaylimit = 30

In [3]:
%%sql
SELECT
    current_database() AS curr_db,
    current_user AS curr_user,
    inet_server_port() AS port,
    version() AS postgres_version;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
1 rows affected.

[('postgres', 'postgres', 5432, 'PostgreSQL 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit')]

### Варіант A $-$ NYC TLC Yellow Taxi з офіційного джерела (з автоматичним fallback на Варіант B)

**Джерело:** <br>
[![Dataset](https://img.shields.io/badge/Dataset-NYC%20TLC%20Yellow%20Taxi-20BEFF?logoColor=white)](<https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page>)
<br>
Файли `https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_YYYY-MM.parquet`.

Свідомі відхилення від шаблону (обидва $-$ щоб ознаки були коректними, а не формально порахованими):

* **2 повні місячні партиції (2026-07 і 2026-08), без семплування.** У місяці ≤ 31 день, тож `trips_lag_30d` був би не-NULL лише для одного дня, і фінальний view (`WHERE trips_lag_30d IS NOT NULL`) був би майже порожній.

* **Завантаження через `COPY` у таблицю з явною схемою** замість `df.to_sql`: ~6.5 млн рядків `to_sql` вставляв би десятки хвилин,`COPY` — ~1 хв; типи колонок задаються DDL, а не вгадуються pandas.

* **Розширене очищення** (окрім обов'язкових правил fare/distance) — аномальні тривалості, явно згадані в умові:`pickup` у межах місяця партиції (у файлах є записи з 2002/2009 рр.), `0 < duration ≤ 180 хв` (у даних є від'ємні тривалості й поїздки > 24 год), середня швидкість ≤ 80 mph, `PULocationID` (у TLC zone lookup це «Unknown»).

> <span style="color:red;">Звіт про кількість відкинутих рядків за кожним правилом друкується нижче.</span>

Якщо завантаження недоступне (немає мережі тощо), notebook **автоматично** переходить на stub-схему (Варіант B), а `DATA_SOURCE` про це повідомляє.

In [4]:
MONTHS = ["2026-07", "2026-08"]
SAMPLE_PER_MONTH = 500_000
BASE_URL = "https://d37ci6vzurychx.cloudfront.net/trip-data/"
COLUMNS = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
    "PULocationID",
    "DOLocationID",
    "trip_distance",
    "fare_amount",
    "passenger_count",
]

RAW_DDL = '''
DROP TABLE IF EXISTS t7_hw_taxi_trips_typed;
DROP TABLE IF EXISTS nyc_taxi_raw;
CREATE TABLE nyc_taxi_raw (
    tpep_pickup_datetime   TIMESTAMP NOT NULL,   -- NYC wall-clock, без зони (як у TLC Parquet)
    tpep_dropoff_datetime  TIMESTAMP NOT NULL,
    "PULocationID"         INTEGER   NOT NULL,
    "DOLocationID"         INTEGER   NOT NULL,
    trip_distance          DOUBLE PRECISION NOT NULL,
    fare_amount            DOUBLE PRECISION NOT NULL,
    passenger_count        DOUBLE PRECISION      -- у TLC бувають NULL
);
'''

def clean_month(part: pd.DataFrame, month: str):
    """
        Повертає очищений DataFrame і звіт: скільки рядків порушує
        кожне правило (правила можуть перетинатися).
    """
    start = pd.Timestamp(f"{month}-01")
    end = start + pd.offsets.MonthBegin(1)
    pick, drop = part["tpep_pickup_datetime"], part["tpep_dropoff_datetime"]
    dur_min = (drop - pick).dt.total_seconds() / 60
    rules = {
        "pickup outside month": ~(
            (pick >= start) &
            (pick < end)
        ),
        "fare not in (0, 500)": ~(
            (part["fare_amount"] > 0) &
            (part["fare_amount"] < 500)
        ),
        "distance not in (0, 100)": ~(
            (part["trip_distance"] > 0) &
            (part["trip_distance"] < 100)
        ),
        "PU zone null/unknown": (
            part["PULocationID"].isna()
        ),
        "duration not in (0, 180]": ~(
            (dur_min > 0) &
            (dur_min <= 180)
        ),
        "speed > 80 mph": (
            (part["trip_distance"] / (dur_min / 60)) > 80
        ),
    }
    bad = pd.concat(rules, axis=1).any(axis=1)
    report = {"month": month, "raw_rows": len(part)}
    report.update({k: int(v.sum()) for k, v in rules.items()})
    report["kept_rows"] = int((~bad).sum())
    return part[~bad], report


def copy_to_postgres(frame: pd.DataFrame, table: str) -> None:
    """
        Швидке завантаження через COPY ... FROM STDIN
        (NaN -> порожнє поле -> NULL).
    """
    buf = io.StringIO()
    frame.to_csv(buf, index=False, header=False)
    buf.seek(0)
    conn = psycopg2.connect(DSN)
    try:
        with conn, conn.cursor() as cur:
            cur.copy_expert(f"COPY {table} FROM STDIN WITH (FORMAT csv)", buf)
    finally:
        conn.close()


try:
    run_sql(RAW_DDL)
    frames, reports = [], []
    for month in MONTHS:
        parquet_path = f"/content/yellow_tripdata_{month}.parquet"
        os.makedirs(os.path.dirname(parquet_path), exist_ok=True)
        if not os.path.exists(parquet_path):
            urlretrieve(f"{BASE_URL}yellow_tripdata_{month}.parquet", parquet_path)
        part, rep = clean_month(pd.read_parquet(parquet_path, columns=COLUMNS), month)
        copy_to_postgres(part[COLUMNS], "nyc_taxi_raw")
        frames.append(part)
        reports.append(rep)
    df = pd.concat(frames, ignore_index=True)
    del frames
    run_sql("ANALYZE nyc_taxi_raw;")
    DATA_SOURCE = "tlc"
except Exception as exc:  # мережа недоступна / файл не знайдено -> stub
    print(
        f"TLC download/load failed ({type(exc).__name__}: {exc})"
        " -> using stub-schema fallback"
    )
    DATA_SOURCE = "stub"

print("DATA_SOURCE =", DATA_SOURCE)
if DATA_SOURCE == "tlc":
    print("Cleaning report (кількість рядків, що порушують правило):")
    display(pd.DataFrame(reports).set_index("month"))
    display(pd.read_sql('''
        SELECT
            COUNT(*) AS n_rows,
            MIN(tpep_pickup_datetime) AS min_ts,
            MAX(tpep_pickup_datetime) AS max_ts,
            ROUND(COUNT(*) / COUNT(
               DISTINCT tpep_pickup_datetime::DATE
            )::NUMERIC) AS avg_trips_per_day
        FROM nyc_taxi_raw''', engine)
    )

DATA_SOURCE = tlc
Cleaning report (кількість рядків, що порушують правило):

,raw_rows,pickup outside month,"fare not in (0, 500)","distance not in (0, 100)",PU zone null/unknown,"duration not in (0, 180]",speed > 80 mph,kept_rows
month,,,,,,,,
2026-07,3530109,46,17031,128494,0,43318,42212,3343698
2026-08,3336716,15,17360,119194,0,44058,40998,3161430

    n_rows     min_ts              max_ts  avg_trips_per_day
0  6505128 2026-07-01 2026-08-31 23:59:59           104921.0

### Daily aggregation `t7_hw_taxi_daily`

* `ts_day DATE` $-$ **локальний NYC-день**: raw `tpep_pickup_datetime` є NYC wall-clock часом (`TIMESTAMP` без зони), тож `::DATE` дає саме календарний день у Нью-Йорку. Конвертувати в UTC перед агрегацією було б помилкою $-$ вечірні поїздки "переїхали" б на наступний день.
* **Dense calendar:** для кожної зони генеруємо всі дні періоду (`generate_series`) і заповнюємо дні без поїздок `trip_count = 0`, `avg_fare = NULL`. Без цього `LAG(trip_count, 7)` (зсув на 7 *рядків*) у зоні з пропущеними днями був би зсувом не на 7 *днів* $-$ класичний off-by-one у time-series features. `avg_fare` для порожнього дня $-$ `NULL` (невідомо), а не 0, щоб не занижувати rolling-середні.
* Constraints (`PRIMARY KEY`, `CHECK`) задаються явно в DDL.
* Оскільки завантажено **повні** місяці без семплування, нулі в dense calendar $-$ реальні дні без поїздок у зоні, а не артефакт семплу.

In [5]:
DAILY_SQL_TLC = """
DROP VIEW  IF EXISTS v_t7_hw_taxi_features;
DROP TABLE IF EXISTS t7_hw_taxi_daily;

CREATE TABLE t7_hw_taxi_daily (
    pickup_zone_id  INTEGER NOT NULL,
    ts_day          DATE    NOT NULL,  -- локальний NYC-день
    trip_count      INTEGER NOT NULL CHECK (trip_count >= 0),
    avg_fare        NUMERIC(10, 2) CHECK (avg_fare >= 0), -- NULL, якщо поїздок не було
    total_distance  NUMERIC(12, 2) NOT NULL CHECK (total_distance >= 0),
    PRIMARY KEY (pickup_zone_id, ts_day)
);

INSERT INTO t7_hw_taxi_daily (pickup_zone_id, ts_day, trip_count, avg_fare, total_distance)
WITH agg AS (
    SELECT
        "PULocationID"::INTEGER AS pickup_zone_id,
        DATE_TRUNC(
            'day', tpep_pickup_datetime::TIMESTAMP
        )::DATE AS ts_day,
        COUNT(*)::INTEGER AS trip_count,
        AVG(fare_amount)::NUMERIC(10, 2) AS avg_fare,
        SUM(trip_distance)::NUMERIC(12, 2) AS total_distance
    FROM nyc_taxi_raw
    WHERE fare_amount > 0
      AND fare_amount < 500
      AND trip_distance > 0
      AND trip_distance < 100
      AND "PULocationID" IS NOT NULL
      AND tpep_pickup_datetime >= TIMESTAMP '2026-07-01'
      AND tpep_pickup_datetime <  TIMESTAMP '2026-09-01'
    GROUP BY 1, 2
),
zones AS (
    SELECT DISTINCT pickup_zone_id FROM agg
),
calendar AS (
    SELECT d::DATE AS ts_day
    FROM generate_series(
        DATE '2026-07-01',
        DATE '2026-08-31',
        INTERVAL '1 day'
    ) AS d
)
SELECT
    z.pickup_zone_id,
    c.ts_day,
    COALESCE(a.trip_count, 0),
    a.avg_fare,
    COALESCE(a.total_distance, 0)
FROM zones z
CROSS JOIN calendar c
LEFT JOIN agg a
       ON a.pickup_zone_id = z.pickup_zone_id
      AND a.ts_day = c.ts_day;

ANALYZE t7_hw_taxi_daily;
"""

# Варіант B. Stub-schema fallback: 60 днів x 5 zones = 300 рядків, фіксована дата
DAILY_SQL_STUB = """
DROP VIEW  IF EXISTS v_t7_hw_taxi_features;
DROP TABLE IF EXISTS t7_hw_taxi_daily;

CREATE TABLE t7_hw_taxi_daily (
    pickup_zone_id  INTEGER NOT NULL,
    ts_day          DATE    NOT NULL,
    trip_count      INTEGER NOT NULL CHECK (trip_count >= 0),
    avg_fare        NUMERIC(10, 2) CHECK (avg_fare >= 0),
    total_distance  NUMERIC(12, 2) NOT NULL CHECK (total_distance >= 0),
    PRIMARY KEY (pickup_zone_id, ts_day)
);

INSERT INTO t7_hw_taxi_daily (
    pickup_zone_id,
    ts_day,
    trip_count,
    avg_fare,
    total_distance
)
SELECT
    z.zone_id,
    DATE '2024-08-31' - (59 - n) AS ts_day,
    500 + (n * 7) + z.zone_id * 50 + (n % 5) * 30 AS trip_count,
    (12.5 + z.zone_id * 0.7 + (n % 4) * 0.4)::NUMERIC(10, 2) AS avg_fare,
    (1500 + n * 25 + z.zone_id * 120)::NUMERIC(12, 2) AS total_distance
FROM generate_series(0, 59) AS n
CROSS JOIN (VALUES (1), (2), (3), (4), (5)) AS z(zone_id);

ANALYZE t7_hw_taxi_daily;
"""

run_sql(DAILY_SQL_TLC if DATA_SOURCE == "tlc" else DAILY_SQL_STUB)

n_rows = pd.read_sql(
    """
        SELECT COUNT(*) AS n
        FROM t7_hw_taxi_daily
    """,
    engine
)["n"].iloc[0]
assert n_rows > 100, n_rows
print(f"DATA_SOURCE={DATA_SOURCE}; t7_hw_taxi_daily rows = {n_rows}")

DATA_SOURCE=tlc; t7_hw_taxi_daily rows = 16182

In [6]:
%%sql
SELECT
    COUNT(*)                        AS n_rows,
    COUNT(DISTINCT pickup_zone_id)  AS n_zones,
    MIN(ts_day)                     AS first_day,
    MAX(ts_day)                     AS last_day,
    SUM(trip_count)                 AS total_trips,
    COUNT(*) FILTER (
        WHERE trip_count = 0
    )                               AS zero_trip_days
FROM t7_hw_taxi_daily;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
1 rows affected.

[(16182, 261, datetime.date(2026, 7, 1), datetime.date(2026, 8, 31), 6505128, 1438)]

In [7]:
%%sql
SELECT
    pickup_zone_id,
    COUNT(*) AS n_days,
    SUM(trip_count) AS trips
FROM t7_hw_taxi_daily
GROUP BY pickup_zone_id
ORDER BY trips DESC;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
261 rows affected.

[(132, 62, 292100),
 (161, 62, 277276),
 (237, 62, 256886),
 (186, 62, 225127),
 (236, 62, 212540),
 (162, 62, 204396),
 (230, 62, 196913),
 (68, 62, 178609),
 (170, 62, 178060),
 (79, 62, 177500),
 (142, 62, 174629),
 (138, 62, 171279),
 (234, 62, 168478),
 (239, 62, 159903),
 (48, 62, 158758),
 (163, 62, 157408),
 (249, 62, 152591),
 (141, 62, 141059),
 (164, 62, 136581),
 (140, 62, 130889),
 (246, 62, 130349),
 (263, 62, 121314),
 (107, 62, 116865),
 (238, 62, 114193),
 (229, 62, 105259),
 (90, 62, 101984),
 (148, 62, 95746),
 (100, 62, 95325),
 (262, 62, 91295),
 (114, 62, 91056),
 (231, 62, 87980),
 (113, 62, 87300),
 (137, 62, 79336),
 (144, 62, 75166),
 (233, 62, 74809),
 (43, 62, 74486),
 (143, 62, 71820),
 (158, 62, 67964),
 (211, 62, 57156),
 (87, 62, 53761),
 (151, 62, 53416),
 (50, 62, 52935),
 (75, 62, 50398),
 (13, 62, 44329),
 (166, 62, 35717),
 (261, 62, 34009),
 (125, 62, 32585),
 (4, 62, 31356),
 (41, 62, 31353),
 (74, 62, 28727),
 (88, 62, 27547),
 (232, 62, 23091),
 (42, 62, 22523),
 (24, 62, 20091),
 (224, 62, 18349),
 (255, 62, 18273),
 (45, 62, 18086),
 (244, 62, 16803),
 (209, 62, 16798),
 (116, 62, 15913),
 (70, 62, 14960),
 (7, 62, 14397),
 (145, 62, 13966),
 (256, 62, 12315),
 (112, 62, 11921),
 (226, 62, 10800),
 (80, 62, 10468),
 (37, 62, 10075),
 (152, 62, 9867),
 (66, 62, 9543),
 (97, 62, 8351),
 (65, 62, 8082),
 (33, 62, 8020),
 (61, 62, 7486),
 (243, 62, 7327),
 (146, 62, 7264),
 (25, 62, 7212),
 (181, 62, 6327),
 (36, 62, 6070),
 (129, 62, 5883),
 (225, 62, 5771),
 (179, 62, 5740),
 (264, 62, 5581),
 (17, 62, 5248),
 (223, 62, 5209),
 (49, 62, 5184),
 (93, 62, 4943),
 (130, 62, 3909),
 (193, 62, 3898),
 (216, 62, 3794),
 (168, 62, 3543),
 (188, 62, 3518),
 (260, 62, 3474),
 (127, 62, 3131),
 (247, 62, 3111),
 (89, 62, 3003),
 (12, 62, 2931),
 (40, 62, 2807),
 (76, 62, 2748),
 (157, 62, 2722),
 (82, 62, 2706),
 (189, 62, 2700),
 (95, 62, 2664),
 (228, 62, 2651),
 (198, 62, 2402),
 (177, 62, 2390),
 (52, 62, 2313),
 (195, 62, 2173),
 (10, 62, 2158),
 (197, 62, 2115),
 (39, 62, 2096),
 (62, 62, 1855),
 (265, 62, 1776),
 (106, 62, 1756),
 (72, 62, 1756),
 (35, 62, 1671),
 (92, 62, 1596),
 (71, 62, 1528),
 (69, 62, 1399),
 (85, 62, 1394),
 (159, 62, 1391),
 (215, 62, 1324),
 (119, 62, 1288),
 (83, 62, 1264),
 (91, 62, 1178),
 (134, 62, 1168),
 (196, 62, 1109),
 (213, 62, 1087),
 (14, 62, 1086),
 (56, 62, 1042),
 (28, 62, 1025),
 (133, 62, 990),
 (63, 62, 984),
 (219, 62, 917),
 (258, 62, 905),
 (202, 62, 874),
 (34, 62, 862),
 (235, 62, 840),
 (167, 62, 802),
 (169, 62, 792),
 (254, 62, 763),
 (212, 62, 756),
 (220, 62, 752),
 (77, 62, 749),
 (257, 62, 735),
 (173, 62, 735),
 (51, 62, 712),
 (78, 62, 709),
 (124, 62, 700),
 (217, 62, 694),
 (205, 62, 693),
 (160, 62, 688),
 (54, 62, 643),
 (248, 62, 634),
 (191, 62, 627),
 (18, 62, 621),
 (55, 62, 616),
 (259, 62, 597),
 (102, 62, 584),
 (126, 62, 578),
 (241, 62, 558),
 (131, 62, 545),
 (227, 62, 533),
 (182, 62, 524),
 (47, 62, 516),
 (174, 62, 507),
 (208, 62, 492),
 (136, 62, 490),
 (155, 62, 477),
 (250, 62, 468),
 (180, 62, 447),
 (60, 62, 441),
 (147, 62, 433),
 (194, 62, 432),
 (81, 62, 432),
 (26, 62, 420),
 (121, 62, 419),
 (200, 62, 417),
 (207, 62, 389),
 (218, 62, 383),
 (190, 62, 380),
 (53, 62, 370),
 (203, 62, 365),
 (210, 62, 347),
 (22, 62, 343),
 (135, 62, 335),
 (122, 62, 332),
 (165, 62, 329),
 (86, 62, 326),
 (242, 62, 326),
 (20, 62, 321),
 (32, 62, 318),
 (128, 62, 308),
 (67, 62, 305),
 (185, 62, 304),
 (171, 62, 300),
 (117, 62, 282),
 (94, 62, 273),
 (252, 62, 271),
 (139, 62, 269),
 (222, 62, 268),
 (38, 62, 263),
 (192, 62, 258),
 (19, 62, 243),
 (16, 62, 236),
 (3, 62, 234),
 (1, 62, 231),
 (101, 62, 222),
 (201, 62, 216),
 (123, 62, 210),
 (21, 62, 209),
 (29, 62, 203),
 (98, 62, 197),
 (153, 62, 193),
 (183, 62, 186),
 (175, 62, 182),
 (149, 62, 167),
 (64, 62, 166),
 (120, 62, 152),
 (11, 62, 145),
 (240, 62, 139),
 (15, 62, 139),
 (150, 62, 138),
 (6, 62, 136),
 (57, 62, 136),
 (31, 62, 133),
 (108, 62, 133),
 (9, 62, 129),
 (8, 62, 113),
 (73, 62, 106),
 (253, 62, 102),
 (27, 62, 97),
 (178, 62, 97),
 (96, 62, 83),
 (46, 62, 77),
 (184, 62, 75),
 (221, 62, 72),
 (154, 62, 72),
 (214, 62, 50),
 (58, 62, 48),
 (59, 62, 45),
 (23, 62, 45),
 (118, 62, 41),
 (30, 62, 40),
 (206, 62, 36),
 (115, 62, 35),
 (172, 62, 34),
 (251, 62, 31),
 (111, 62, 26),
 (245, 62, 24),
 (109, 62, 23),
 (156, 62, 22),
 (2, 62, 18),
 (176, 62, 17),
 (187, 62, 16),
 (44, 62, 10),
 (5, 62, 8),
 (199, 62, 7),
 (204, 62, 4),
 (84, 62, 3),
 (99, 62, 3)]

### Production-style typed таблиця з `TIMESTAMPTZ` (тільки для real TLC-даних)

Raw `TIMESTAMP` інтерпретується як NYC-час через `AT TIME ZONE 'America/New_York'` і перетворюється на абсолютний момент `TIMESTAMPTZ`. Якщо зберігати production-події як `TIMESTAMP`, то можливі UTC-зсув після переходу на літній час в Березні, або зимовий час в Листопаді. Цей фактор не має впливу у Липні та Серпні, про що свідчить результат перевірки нижче.

In [8]:
TYPED_SQL = """
DROP TABLE IF EXISTS t7_hw_taxi_trips_typed;

CREATE TABLE t7_hw_taxi_trips_typed AS
SELECT
    "PULocationID"::INTEGER AS pickup_zone_id,
    "DOLocationID"::INTEGER AS dropoff_zone_id,
    (tpep_pickup_datetime::TIMESTAMP  AT TIME ZONE 'America/New_York') AS pickup_at,
    (tpep_dropoff_datetime::TIMESTAMP AT TIME ZONE 'America/New_York') AS dropoff_at,
    trip_distance::NUMERIC(10, 2) AS trip_distance,
    fare_amount::NUMERIC(10, 2)   AS fare_amount,
    passenger_count::INTEGER      AS passenger_count
FROM nyc_taxi_raw
WHERE fare_amount > 0
    AND fare_amount < 500
    AND trip_distance > 0
    AND trip_distance < 100
    AND tpep_dropoff_datetime >  tpep_pickup_datetime
    AND tpep_dropoff_datetime <= tpep_pickup_datetime + INTERVAL '3 hours';
"""

if DATA_SOURCE == "tlc":
    run_sql(TYPED_SQL)
    display(
        pd.read_sql("""
        SELECT
            raw.tpep_pickup_datetime              AS raw_local_ts,
            pg_typeof(raw.tpep_pickup_datetime)   AS raw_type,
            (raw.tpep_pickup_datetime AT TIME ZONE 'America/New_York') AS pickup_at,
            pg_typeof(
                raw.tpep_pickup_datetime
                AT TIME ZONE 'America/New_York'
            ) AS pickup_type,
            to_char(
                (raw.tpep_pickup_datetime AT TIME ZONE 'America/New_York')
                AT TIME ZONE 'UTC',
                'YYYY-MM-DD HH24:MI'
            ) || ' UTC' AS as_utc
        FROM (
            SELECT
                tpep_pickup_datetime
            FROM nyc_taxi_raw
            WHERE tpep_pickup_datetime::DATE IN (
                DATE '2026-08-09',
                DATE '2026-08-11'
            )
            ORDER BY tpep_pickup_datetime LIMIT 1) raw
        UNION ALL
        SELECT
            raw.tpep_pickup_datetime,
            pg_typeof(raw.tpep_pickup_datetime),
            (raw.tpep_pickup_datetime AT TIME ZONE 'America/New_York'),
            pg_typeof(raw.tpep_pickup_datetime AT TIME ZONE 'America/New_York'),
            to_char(
                (raw.tpep_pickup_datetime AT TIME ZONE 'America/New_York')
                AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI'
            ) || ' UTC'
        FROM (
            SELECT tpep_pickup_datetime
            FROM nyc_taxi_raw
            WHERE tpep_pickup_datetime::DATE = DATE '2026-08-11'
            ORDER BY tpep_pickup_datetime LIMIT 1
        ) raw
        """,
        engine)
    )
else:
    print("Stub-mode: raw trips відсутні, typed-таблиця не створюється.")

,raw_local_ts,raw_type,pickup_at,pickup_type,as_utc
0,2026-08-09,timestamp without time zone,2026-08-09 04:00:00+00:00,timestamp with time zone,2026-08-09 04:00 UTC
1,2026-08-11,timestamp without time zone,2026-08-11 04:00:00+00:00,timestamp with time zone,2026-08-11 04:00 UTC

## 2. Time-series ML features

Усі вікна мають `PARTITION BY pickup_zone_id`. Без нього `LAG` на першому рядку нової зони взяв би значення з останнього рядка попередньої зони $-$ тиха ML-помилка (модель отримує історію іншої сутності).

### Feature 1. Lag features: lag-1d, lag-7d, lag-30d
`LAG` рахує зсув у **рядках**; це дорівнює зсуву в **днях** лише тому, що календар щільний (див. dense calendar вище, перевірка $-$ нижче).

In [13]:
%%sql
WITH cte AS (
    SELECT
        pickup_zone_id,
        ts_day,
        COALESCE(trip_count, 0),
        LAG(trip_count, 1)  OVER w AS trips_lag_1d,
        LAG(trip_count, 7)  OVER w AS trips_lag_7d,
        LAG(trip_count, 30) OVER w AS trips_lag_30d
    FROM t7_hw_taxi_daily
    WINDOW w AS (
        PARTITION BY pickup_zone_id
        ORDER BY ts_day
    )
)
SELECT *
FROM cte
WHERE ts_day >= DATE '2026-08-01'
ORDER BY pickup_zone_id, ts_day;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
8091 rows affected.

[(1, datetime.date(2026, 8, 1), 4, 4, 4, 2),
 (1, datetime.date(2026, 8, 2), 4, 4, 8, 1),
 (1, datetime.date(2026, 8, 3), 1, 4, 1, 3),
 (1, datetime.date(2026, 8, 4), 3, 1, 2, 8),
 (1, datetime.date(2026, 8, 5), 1, 3, 7, 2),
 (1, datetime.date(2026, 8, 6), 6, 1, 4, 3),
 (1, datetime.date(2026, 8, 7), 5, 6, 4, 2),
 (1, datetime.date(2026, 8, 8), 4, 5, 4, 3),
 (1, datetime.date(2026, 8, 9), 11, 4, 4, 1),
 (1, datetime.date(2026, 8, 10), 6, 11, 1, 3),
 (1, datetime.date(2026, 8, 11), 2, 6, 3, 10),
 (1, datetime.date(2026, 8, 12), 6, 2, 1, 3),
 (1, datetime.date(2026, 8, 13), 6, 6, 6, 1),
 (1, datetime.date(2026, 8, 14), 3, 6, 5, 2),
 (1, datetime.date(2026, 8, 15), 3, 3, 4, 1),
 (1, datetime.date(2026, 8, 16), 8, 3, 11, 3),
 (1, datetime.date(2026, 8, 17), 4, 8, 6, 3),
 (1, datetime.date(2026, 8, 18), 1, 4, 2, 6),
 (1, datetime.date(2026, 8, 19), 4, 1, 6, 9),
 (1, datetime.date(2026, 8, 20), 5, 4, 6, 3),
 (1, datetime.date(2026, 8, 21), 1, 5, 3, 5),
 (1, datetime.date(2026, 8, 22), 2, 1, 3, 3),
 (1, datetime.date(2026, 8, 23), 2, 2, 8, 3),
 (1, datetime.date(2026, 8, 24), 3, 2, 4, 4),
 (1, datetime.date(2026, 8, 25), 2, 3, 1, 8),
 (1, datetime.date(2026, 8, 26), 7, 2, 4, 1),
 (1, datetime.date(2026, 8, 27), 2, 7, 5, 2),
 (1, datetime.date(2026, 8, 28), 3, 2, 1, 7),
 (1, datetime.date(2026, 8, 29), 2, 3, 2, 4),
 (1, datetime.date(2026, 8, 30), 3, 2, 2, 4),
 (1, datetime.date(2026, 8, 31), 5, 3, 3, 4),
 (2, datetime.date(2026, 8, 1), 0, 0, 0, 0),
 (2, datetime.date(2026, 8, 2), 0, 0, 0, 0),
 (2, datetime.date(2026, 8, 3), 0, 0, 0, 1),
 (2, datetime.date(2026, 8, 4), 0, 0, 0, 0),
 (2, datetime.date(2026, 8, 5), 1, 0, 2, 0),
 (2, datetime.date(2026, 8, 6), 0, 1, 1, 0),
 (2, datetime.date(2026, 8, 7), 0, 0, 0, 1),
 (2, datetime.date(2026, 8, 8), 0, 0, 0, 0),
 (2, datetime.date(2026, 8, 9), 0, 0, 0, 0),
 (2, datetime.date(2026, 8, 10), 0, 0, 0, 2),
 (2, datetime.date(2026, 8, 11), 0, 0, 0, 0),
 (2, datetime.date(2026, 8, 12), 1, 0, 1, 0),
 (2, datetime.date(2026, 8, 13), 0, 1, 0, 0),
 (2, datetime.date(2026, 8, 14), 0, 0, 0, 0),
 (2, datetime.date(2026, 8, 15), 0, 0, 0, 1),
 (2, datetime.date(2026, 8, 16), 0, 0, 0, 0),
 (2, datetime.date(2026, 8, 17), 0, 0, 0, 1),
 (2, datetime.date(2026, 8, 18), 1, 0, 0, 0),
 (2, datetime.date(2026, 8, 19), 0, 1, 1, 0),
 (2, datetime.date(2026, 8, 20), 0, 0, 0, 1),
 (2, datetime.date(2026, 8, 21), 1, 0, 0, 0),
 (2, datetime.date(2026, 8, 22), 1, 1, 0, 1),
 (2, datetime.date(2026, 8, 23), 0, 1, 0, 0),
 (2, datetime.date(2026, 8, 24), 1, 0, 0, 0),
 (2, datetime.date(2026, 8, 25), 0, 1, 1, 0),
 (2, datetime.date(2026, 8, 26), 0, 0, 0, 0),
 (2, datetime.date(2026, 8, 27), 0, 0, 0, 0),
 (2, datetime.date(2026, 8, 28), 0, 0, 1, 2),
 (2, datetime.date(2026, 8, 29), 0, 0, 1, 1),
 (2, datetime.date(2026, 8, 30), 1, 0, 0, 0),
 (2, datetime.date(2026, 8, 31), 0, 1, 1, 0),
 (3, datetime.date(2026, 8, 1), 6, 6, 5, 0),
 (3, datetime.date(2026, 8, 2), 6, 6, 8, 0),
 (3, datetime.date(2026, 8, 3), 6, 6, 2, 6),
 (3, datetime.date(2026, 8, 4), 0, 6, 2, 4),
 (3, datetime.date(2026, 8, 5), 1, 0, 4, 1),
 (3, datetime.date(2026, 8, 6), 3, 1, 3, 1),
 (3, datetime.date(2026, 8, 7), 6, 3, 6, 0),
 (3, datetime.date(2026, 8, 8), 3, 6, 6, 2),
 (3, datetime.date(2026, 8, 9), 3, 3, 6, 5),
 (3, datetime.date(2026, 8, 10), 3, 3, 6, 4),
 (3, datetime.date(2026, 8, 11), 1, 3, 0, 7),
 (3, datetime.date(2026, 8, 12), 5, 1, 1, 5),
 (3, datetime.date(2026, 8, 13), 5, 5, 3, 4),
 (3, datetime.date(2026, 8, 14), 5, 5, 6, 2),
 (3, datetime.date(2026, 8, 15), 4, 5, 3, 1),
 (3, datetime.date(2026, 8, 16), 5, 4, 3, 5),
 (3, datetime.date(2026, 8, 17), 3, 5, 3, 8),
 (3, datetime.date(2026, 8, 18), 3, 3, 1, 12),
 (3, datetime.date(2026, 8, 19), 4, 3, 5, 3),
 (3, datetime.date(2026, 8, 20), 3, 4, 5, 5),
 (3, datetime.date(2026, 8, 21), 4, 3, 5, 7),
 (3, datetime.date(2026, 8, 22), 3, 4, 4, 2),
 (3, datetime.date(2026, 8, 23), 5, 3, 5, 4),
 (3, datetime.date(2026, 8, 24), 1, 5, 3, 5),
 (3, datetime.date(2026, 8, 25), 2, 1, 3, 8),
 (3, datetime.date(2026, 8, 26), 4, 2, 4, 2),
 (3, datetime.date(2026, 8, 27), 1, 4, 3, 2),
 (3, datetime.date(2026, 8, 28), 5, 1, 4, 4),
 (3, datetime.date(2026, 8, 29), 6, 5, 3, 3),
 (3, datetime.date(2026, 8, 30), 5, 6, 5, 6),
 (3, datetime.date(2026, 8, 31), 4, 5, 1, 6),
 (4, datetime.date(2026, 8, 1), 881, 606, 902, 462),
 (4, datetime.date(2026, 8, 2), 682, 881, 724, 454),
 (4, datetime.date(2026, 8, 3), 282, 682, 276, 537),
 (4, datetime.date(2026, 8, 4), 371, 282, 338, 369),
 (4, datetime.date(2026, 8, 5), 391, 371, 399, 231),
 (4, datetime.date(2026, 8, 6), 454, 391, 393, 246),
 (4, datetime.date(2026, 8, 7), 639, 454, 606, 323),
 (4, datetime.date(2026, 8, 8), 904, 639, 881, 360),
 (4, datetime.date(2026, 8, 9), 684, 904, 682, 521),
 (4, datetime.date(2026, 8, 10), 277, 684, 282, 837),
 (4, datetime.date(2026, 8, 11), 353, 277, 371, 752),
 (4, datetime.date(2026, 8, 12), 392, 353, 391, 257),
 (4, datetime.date(2026, 8, 13), 450, 392, 454, 387),
 (4, datetime.date(2026, 8, 14), 575, 450, 639, 377),
 (4, datetime.date(2026, 8, 15), 852, 575, 904, 424),
 (4, datetime.date(2026, 8, 16), 709, 852, 684, 623),
 (4, datetime.date(2026, 8, 17), 306, 709, 277, 967),
 (4, datetime.date(2026, 8, 18), 350, 306, 353, 871),
 (4, datetime.date(2026, 8, 19), 366, 350, 392, 292),
 (4, datetime.date(2026, 8, 20), 478, 366, 450, 315),
 (4, datetime.date(2026, 8, 21), 504, 478, 575, 366),
 (4, datetime.date(2026, 8, 22), 877, 504, 852, 447),
 (4, datetime.date(2026, 8, 23), 732, 877, 709, 555),
 (4, datetime.date(2026, 8, 24), 259, 732, 306, 902),
 (4, datetime.date(2026, 8, 25), 325, 259, 350, 724),
 (4, datetime.date(2026, 8, 26), 372, 325, 366, 276),
 (4, datetime.date(2026, 8, 27), 411, 372, 478, 338),
 (4, datetime.date(2026, 8, 28), 570, 411, 504, 399),
 (4, datetime.date(2026, 8, 29), 880, 570, 877, 393),
 (4, datetime.date(2026, 8, 30), 734, 880, 732, 606),
 (4, datetime.date(2026, 8, 31), 313, 734, 259, 881),
 (5, datetime.date(2026, 8, 1), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 2), 0, 0, 1, 0),
 (5, datetime.date(2026, 8, 3), 2, 0, 0, 1),
 (5, datetime.date(2026, 8, 4), 0, 2, 0, 0),
 (5, datetime.date(2026, 8, 5), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 6), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 7), 1, 0, 0, 0),
 (5, datetime.date(2026, 8, 8), 0, 1, 0, 0),
 (5, datetime.date(2026, 8, 9), 1, 0, 0, 0),
 (5, datetime.date(2026, 8, 10), 0, 1, 2, 0),
 (5, datetime.date(2026, 8, 11), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 12), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 13), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 14), 0, 0, 1, 0),
 (5, datetime.date(2026, 8, 15), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 16), 0, 0, 1, 0),
 (5, datetime.date(2026, 8, 17), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 18), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 19), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 20), 2, 0, 0, 0),
 (5, datetime.date(2026, 8, 21), 0, 2, 0, 0),
 (5, datetime.date(2026, 8, 22), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 23), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 24), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 25), 0, 0, 0, 1),
 (5, datetime.date(2026, 8, 26), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 27), 0, 0, 2, 0),
 (5, datetime.date(2026, 8, 28), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 29), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 30), 0, 0, 0, 0),
 (5, datetime.date(2026, 8, 31), 0, 0, 0, 0),
 (6, datetime.date(2026, 8, 1), 1, 2, 2, 2),
 (6, datetime.date(2026, 8, 2), 2, 1, 2, 0),
 (6, datetime.date(2026, 8, 3), 4, 2, 1, 4),
 (6, datetime.date(2026, 8, 4), 3, 4, 3, 3),
 (6, datetime.date(2026, 8, 5), 3, 3, 2, 2),
 (6, datetime.date(2026, 8, 6), 2, 3, 2, 1),
 (6, datetime.date(2026, 8, 7), 3, 2, 2, 1),
 (6, datetime.date(2026, 8, 8), 2, 3, 1, 2),
 (6, datetime.date(2026, 8, 9), 6, 2, 2, 4),
 (6, datetime.date(2026, 8, 10), 3, 6, 4, 2),
 (6, datetime.date(2026, 8, 11), 1, 3, 3, 1),
 (6, datetime.date(2026, 8, 12), 0, 1, 3, 2),
 (6, datetime.date(2026, 8, 13), 2, 0, 2, 1),
 (6, datetime.date(2026, 8, 14), 1, 2, 3, 1),
 (6, datetime.date(2026, 8, 15), 3, 1, 2, 2),
 (6, datetime.date(2026, 8, 16), 1, 3, 6, 1),
 (6, datetime.date(2026, 8, 17), 3, 1, 3, 3),
 (6, datetime.date(2026, 8, 18), 1, 3, 1, 3),
 (6, datetime.date(2026, 8, 19), 3, 1, 0, 2),
 (6, datetime.date(2026, 8, 20), 2, 3, 2, 1),
 (6, datetime.date(2026, 8, 21), 3, 2, 1, 2),
 (6, datetime.date(2026, 8, 22), 2, 3, 3, 1),
 (6, datetime.date(2026, 8, 23), 3, 2, 1, 2),
 (6, datetime.date(2026, 8, 24), 1, 3, 3, 2),
 (6, datetime.date(2026, 8, 25), 4, 1, 1, 2),
 (6, datetime.date(2026, 8, 26), 3, 4, 3, 1),
 (6, datetime.date(2026, 8, 27), 2, 3, 2, 3),
 (6, datetime.date(2026, 8, 28), 2, 2, 3, 2),
 (6, datetime.date(2026, 8, 29), 6, 2, 2, 2),
 (6, datetime.date(2026, 8, 30), 4, 6, 3, 2),
 (6, datetime.date(2026, 8, 31), 1, 4, 1, 1),
 (7, datetime.date(2026, 8, 1), 315, 224, 310, 148),
 (7, datetime.date(2026, 8, 2), 277, 315, 311, 196),
 (7, datetime.date(2026, 8, 3), 218, 277, 145, 396),
 (7, datetime.date(2026, 8, 4), 175, 218, 130, 269),
 (7, datetime.date(2026, 8, 5), 148, 175, 140, 216),
 (7, datetime.date(2026, 8, 6), 158, 148, 171, 131),
 (7, datetime.date(2026, 8, 7), 208, 158, 224, 127),
 (7, datetime.date(2026, 8, 8), 332, 208, 315, 140),
 (7, datetime.date(2026, 8, 9), 315, 332, 277, 190),
 (7, datetime.date(2026, 8, 10), 157, 315, 218, 338),
 (7, datetime.date(2026, 8, 11), 145, 157, 175, 319),
 (7, datetime.date(2026, 8, 12), 169, 145, 148, 189),
 (7, datetime.date(2026, 8, 13), 177, 169, 158, 156),
 (7, datetime.date(2026, 8, 14), 214, 177, 208, 199),
 (7, datetime.date(2026, 8, 15), 354, 214, 332, 200),
 (7, datetime.date(2026, 8, 16), 321, 354, 315, 343),
 (7, datetime.date(2026, 8, 17), 166, 321, 157, 478),
 (7, datetime.date(2026, 8, 18), 158, 166, 145, 553),
 (7, datetime.date(2026, 8, 19), 152, 158, 169, 234),
 (7, datetime.date(2026, 8, 20), 253, 152, 177, 200),
 (7, datetime.date(2026, 8, 21), 222, 253, 214, 194),
 (7, datetime.date(2026, 8, 22), 353, 222, 354, 194),
 (7, datetime.date(2026, 8, 23), 349, 353, 321, 207),
 (7, datetime.date(2026, 8, 24), 145, 349, 166, 310),
 (7, datetime.date(2026, 8, 25), 150, 145, 158, 311),
 (7, datetime.date(2026, 8, 26), 160, 150, 152, 145),
 (7, datetime.date(2026, 8, 27), 185, 160, 253, 130),
 (7, datetime.date(2026, 8, 28), 238, 185, 222, 140),
 (7, datetime.date(2026, 8, 29), 350, 238, 353, 171),
 (7, datetime.date(2026, 8, 30), 371, 350, 349, 224),
 (7, datetime.date(2026, 8, 31), 168, 371, 145, 315),
 (8, datetime.date(2026, 8, 1), 3, 0, 5, 2),
 (8, datetime.date(2026, 8, 2), 3, 3, 0, 3),
 (8, datetime.date(2026, 8, 3), 0, 3, 1, 2),
 (8, datetime.date(2026, 8, 4), 1, 0, 0, 1),
 (8, datetime.date(2026, 8, 5), 1, 1, 1, 2),
 (8, datetime.date(2026, 8, 6), 1, 1, 1, 1),
 (8, datetime.date(2026, 8, 7), 1, 1, 0, 2),
 (8, datetime.date(2026, 8, 8), 3, 1, 3, 1),
 (8, datetime.date(2026, 8, 9), 2, 3, 3, 1),
 (8, datetime.date(2026, 8, 10), 1, 2, 0, 5),
 (8, datetime.date(2026, 8, 11), 3, 1, 1, 1),
 (8, datetime.date(2026, 8, 12), 2, 3, 1, 0),
 (8, datetime.date(2026, 8, 13), 2, 2, 1, 3),
 (8, datetime.date(2026, 8, 14), 4, 2, 1, 1),
 (8, datetime.date(2026, 8, 15), 11, 4, 3, 1),
 (8, datetime.date(2026, 8, 16), 2, 11, 2, 1),
 (8, datetime.date(2026, 8, 17), 2, 2, 1, 1),
 (8, datetime.date(2026, 8, 18), 0, 2, 3, 4),
 (8, datetime.date(2026, 8, 19), 0, 0, 2, 5),
 (8, datetime.date(2026, 8, 20), 2, 0, 2, 0),
 (8, datetime.date(2026, 8, 21), 0, 2, 4, 2),
 (8, datetime.date(2026, 8, 22), 2, 0, 11, 3),
 (8, datetime.date(2026, 8, 23), 2, 2, 2, 2),
 (8, datetime.date(2026, 8, 24), 0, 2, 2, 5),
 (8, datetime.date(2026, 8, 25), 0, 0, 0, 0),
 (8, datetime.date(2026, 8, 26), 3, 0, 0, 1),
 (8, datetime.date(2026, 8, 27), 0, 3, 2, 0),
 (8, datetime.date(2026, 8, 28), 2, 0, 0, 1),
 (8, datetime.date(2026, 8, 29), 4, 2, 2, 1),
 (8, datetime.date(2026, 8, 30), 2, 4, 2, 0),
 (8, datetime.date(2026, 8, 31), 0, 2, 0, 3),
 (9, datetime.date(2026, 8, 1), 1, 0, 3, 1),
 (9, datetime.date(2026, 8, 2), 1, 1, 2, 1),
 (9, datetime.date(2026, 8, 3), 8, 1, 0, 1),
 (9, datetime.date(2026, 8, 4), 2, 8, 0, 4),
 (9, datetime.date(2026, 8, 5), 1, 2, 4, 2),
 (9, datetime.date(2026, 8, 6), 3, 1, 2, 2),
 (9, datetime.date(2026, 8, 7), 0, 3, 0, 3),
 (9, datetime.date(2026, 8, 8), 1, 0, 1, 3),
 (9, datetime.date(2026, 8, 9), 2, 1, 1, 1),
 (9, datetime.date(2026, 8, 10), 1, 2, 8, 1),
 (9, datetime.date(2026, 8, 11), 2, 1, 2, 1),
 (9, datetime.date(2026, 8, 12), 4, 2, 1, 1),
 (9, datetime.date(2026, 8, 13), 4, 4, 3, 1),
 (9, datetime.date(2026, 8, 14), 2, 4, 0, 1),
 (9, datetime.date(2026, 8, 15), 2, 2, 1, 0),
 (9, datetime.date(2026, 8, 16), 1, 2, 2, 3),
 (9, datetime.date(2026, 8, 17), 1, 1, 1, 12),
 (9, datetime.date(2026, 8, 18), 2, 1, 2, 3),
 (9, datetime.date(2026, 8, 19), 1, 2, 4, 6),
 (9, datetime.date(2026, 8, 20), 1, 1, 4, 0),
 (9, datetime.date(2026, 8, 21), 4, 1, 2, 3),
 (9, datetime.date(2026, 8, 22), 2, 4, 2, 4),
 (9, datetime.date(2026, 8, 23), 4, 2, 1, 0),
 (9, datetime.date(2026, 8, 24), 1, 4, 1, 3),
 (9, datetime.date(2026, 8, 25), 2, 1, 2, 2),
 (9, datetime.date(2026, 8, 26), 2, 2, 1, 0),
 (9, datetime.date(2026, 8, 27), 3, 2, 1, 0),
 (9, datetime.date(2026, 8, 28), 1, 3, 4, 4),
 (9, datetime.date(2026, 8, 29), 0, 1, 2, 2),
 (9, datetime.date(2026, 8, 30), 1, 0, 4, 0),
 (9, datetime.date(2026, 8, 31), 3, 1, 1, 1),
 (10, datetime.date(2026, 8, 1), 30, 34, 27, 24),
 (10, datetime.date(2026, 8, 2), 38, 30, 52, 25),
 (10, datetime.date(2026, 8, 3), 50, 38, 40, 40),
 (10, datetime.date(2026, 8, 4), 25, 50, 40, 43),
 (10, datetime.date(2026, 8, 5), 28, 25, 40, 55),
 (10, datetime.date(2026, 8, 6), 38, 28, 33, 29),
 (10, datetime.date(2026, 8, 7), 31, 38, 34, 24),
 (10, datetime.date(2026, 8, 8), 32, 31, 30, 20),
 (10, datetime.date(2026, 8, 9), 32, 32, 38, 39),
 (10, datetime.date(2026, 8, 10), 33, 32, 50, 30),
 (10, datetime.date(2026, 8, 11), 26, 33, 25, 36),
 (10, datetime.date(2026, 8, 12), 16, 26, 28, 37),
 (10, datetime.date(2026, 8, 13), 26, 16, 38, 40),
 (10, datetime.date(2026, 8, 14), 29, 26, 31, 37),
 (10, datetime.date(2026, 8, 15), 36, 29, 32, 41),
 (10, datetime.date(2026, 8, 16), 36, 36, 32, 47),
 (10, datetime.date(2026, 8, 17), 46, 36, 33, 38),
 (10, datetime.date(2026, 8, 18), 24, 46, 26, 58),
 (10, datetime.date(2026, 8, 19), 17, 24, 16, 49),
 (10, datetime.date(2026, 8, 20), 30, 17, 26, 41),
 (10, datetime.date(2026, 8, 21), 34, 30, 29, 30),
 (10, datetime.date(2026, 8, 22), 15, 34, 36, 36),
 (10, datetime.date(2026, 8, 23), 43, 15, 36, 27),
 (10, datetime.date(2026, 8, 24), 27, 43, 46, 27),
 (10, datetime.date(2026, 8, 25), 40, 27, 24, 52),
 (10, datetime.date(2026, 8, 26), 41, 40, 17, 40),
 (10, datetime.date(2026, 8, 27), 30, 41, 30, 40),
 (10, datetime.date(2026, 8, 28), 30, 30, 34, 40),
 (10, datetime.date(2026, 8, 29), 44, 30, 15, 33),
 (10, datetime.date(2026, 8, 30), 47, 44, 43, 34),
 (10, datetime.date(2026, 8, 31), 44, 47, 27, 30),
 (11, datetime.date(2026, 8, 1), 0, 3, 1, 1),
 (11, datetime.date(2026, 8, 2), 1, 0, 3, 4),
 (11, datetime.date(2026, 8, 3), 7, 1, 1, 4),
 (11, datetime.date(2026, 8, 4), 1, 7, 1, 4),
 (11, datetime.date(2026, 8, 5), 0, 1, 1, 3),
 (11, datetime.date(2026, 8, 6), 0, 0, 1, 1),
 (11, datetime.date(2026, 8, 7), 2, 0, 3, 0),
 (11, datetime.date(2026, 8, 8), 6, 2, 0, 0),
 (11, datetime.date(2026, 8, 9), 3, 6, 1, 3),
 (11, datetime.date(2026, 8, 10), 0, 3, 7, 3),
 (11, datetime.date(2026, 8, 11), 1, 0, 1, 3),
 (11, datetime.date(2026, 8, 12), 4, 1, 0, 1),
 (11, datetime.date(2026, 8, 13), 0, 4, 0, 2),
 (11, datetime.date(2026, 8, 14), 2, 0, 2, 3),
 (11, datetime.date(2026, 8, 15), 2, 2, 6, 2),
 (11, datetime.date(2026, 8, 16), 2, 2, 3, 6),
 (11, datetime.date(2026, 8, 17), 2, 2, 0, 8),
 (11, datetime.date(2026, 8, 18), 0, 2, 1, 6),
 (11, datetime.date(2026, 8, 19), 1, 0, 4, 3),
 (11, datetime.date(2026, 8, 20), 3, 1, 0, 2),
 (11, datetime.date(2026, 8, 21), 5, 3, 2, 4),
 (11, datetime.date(2026, 8, 22), 5, 5, 2, 2),
 (11, datetime.date(2026, 8, 23), 5, 5, 2, 1),
 (11, datetime.date(2026, 8, 24), 0, 5, 2, 1),
 (11, datetime.date(2026, 8, 25), 2, 0, 0, 3),
 (11, datetime.date(2026, 8, 26), 1, 2, 1, 1),
 (11, datetime.date(2026, 8, 27), 3, 1, 3, 1),
 (11, datetime.date(2026, 8, 28), 0, 3, 5, 1),
 (11, datetime.date(2026, 8, 29), 4, 0, 5, 1),
 (11, datetime.date(2026, 8, 30), 1, 4, 5, 3),
 (11, datetime.date(2026, 8, 31), 5, 1, 0, 0),
 (12, datetime.date(2026, 8, 1), 81, 51, 88, 37),
 (12, datetime.date(2026, 8, 2), 75, 81, 78, 78),
 (12, datetime.date(2026, 8, 3), 47, 75, 60, 87),
 (12, datetime.date(2026, 8, 4), 63, 47, 19, 80),
 (12, datetime.date(2026, 8, 5), 37, 63, 37, 39),
 (12, datetime.date(2026, 8, 6), 43, 37, 20, 50),
 (12, datetime.date(2026, 8, 7), 53, 43, 51, 44),
 (12, datetime.date(2026, 8, 8), 70, 53, 81, 39),
 (12, datetime.date(2026, 8, 9), 71, 70, 75, 49),
 (12, datetime.date(2026, 8, 10), 30, 71, 47, 63),
 (12, datetime.date(2026, 8, 11), 46, 30, 63, 71),
 (12, datetime.date(2026, 8, 12), 29, 46, 37, 34),
 (12, datetime.date(2026, 8, 13), 36, 29, 43, 41),
 (12, datetime.date(2026, 8, 14), 40, 36, 53, 39),
 (12, datetime.date(2026, 8, 15), 81, 40, 70, 32),
 (12, datetime.date(2026, 8, 16), 61, 81, 71, 48),
 (12, datetime.date(2026, 8, 17), 36, 61, 30, 44),
 (12, datetime.date(2026, 8, 18), 48, 36, 46, 34),
 (12, datetime.date(2026, 8, 19), 28, 48, 29, 52),
 (12, datetime.date(2026, 8, 20), 21, 28, 36, 31),
 (12, datetime.date(2026, 8, 21), 37, 21, 40, 41),
 (12, datetime.date(2026, 8, 22), 44, 37, 81, 55),
 (12, datetime.date(2026, 8, 23), 47, 44, 61, 48),
 (12, datetime.date(2026, 8, 24), 30, 47, 36, 88),
 (12, datetime.date(2026, 8, 25), 38, 30, 48, 78),
 (12, datetime.date(2026, 8, 26), 22, 38, 28, 60),
 (12, datetime.date(2026, 8, 27), 35, 22, 21, 19),
 (12, datetime.date(2026, 8, 28), 36, 35, 37, 37),
 (12, datetime.date(2026, 8, 29), 55, 36, 44, 20),
 (12, datetime.date(2026, 8, 30), 37, 55, 47, 51),
 (12, datetime.date(2026, 8, 31), 25, 37, 30, 81),
 (13, datetime.date(2026, 8, 1), 690, 787, 684, 686),
 (13, datetime.date(2026, 8, 2), 437, 690, 551, 478),
 (13, datetime.date(2026, 8, 3), 635, 437, 766, 548),
 (13, datetime.date(2026, 8, 4), 861, 635, 852, 400),
 (13, datetime.date(2026, 8, 5), 893, 861, 948, 681),
 (13, datetime.date(2026, 8, 6), 882, 893, 1042, 781),
 (13, datetime.date(2026, 8, 7), 779, 882, 787, 823),
 (13, datetime.date(2026, 8, 8), 693, 779, 690, 890),
 (13, datetime.date(2026, 8, 9), 497, 693, 437, 733),
 (13, datetime.date(2026, 8, 10), 615, 497, 635, 665),
 (13, datetime.date(2026, 8, 11), 856, 615, 861, 484),
 (13, datetime.date(2026, 8, 12), 858, 856, 893, 722),
 (13, datetime.date(2026, 8, 13), 869, 858, 882, 903),
 (13, datetime.date(2026, 8, 14), 705, 869, 779, 989),
 (13, datetime.date(2026, 8, 15), 595, 705, 693, 1001),
 (13, datetime.date(2026, 8, 16), 394, 595, 497, 864),
 (13, datetime.date(2026, 8, 17), 586, 394, 615, 596),
 (13, datetime.date(2026, 8, 18), 782, 586, 856, 570),
 (13, datetime.date(2026, 8, 19), 785, 782, 858, 780),
 (13, datetime.date(2026, 8, 20), 868, 785, 869, 909),
 (13, datetime.date(2026, 8, 21), 608, 868, 705, 967),
 (13, datetime.date(2026, 8, 22), 502, 608, 595, 1043),
 (13, datetime.date(2026, 8, 23), 351, 502, 394, 810),
 (13, datetime.date(2026, 8, 24), 538, 351, 586, 684),
 (13, datetime.date(2026, 8, 25), 652, 538, 782, 551),
 (13, datetime.date(2026, 8, 26), 784, 652, 785, 766),
 (13, datetime.date(2026, 8, 27), 747, 784, 868, 852),
 (13, datetime.date(2026, 8, 28), 616, 747, 608, 948),
 (13, datetime.date(2026, 8, 29), 539, 616, 502, 1042),
 (13, datetime.date(2026, 8, 30), 410, 539, 351, 787),
 (13, datetime.date(2026, 8, 31), 565, 410, 538, 690),
 (14, datetime.date(2026, 8, 1), 43, 23, 35, 12),
 (14, datetime.date(2026, 8, 2), 26, 43, 16, 10),
 (14, datetime.date(2026, 8, 3), 25, 26, 12, 25),
 (14, datetime.date(2026, 8, 4), 13, 25, 9, 18),
 (14, datetime.date(2026, 8, 5), 12, 13, 15, 11),
 (14, datetime.date(2026, 8, 6), 13, 12, 18, 5),
 (14, datetime.date(2026, 8, 7), 15, 13, 23, 7),
 (14, datetime.date(2026, 8, 8), 21, 15, 43, 13),
 (14, datetime.date(2026, 8, 9), 15, 21, 26, 13),

### Feature 2. Rolling 7-day average fare
`RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW` = 7 **календарних** днів включно з поточним. `ts_day` приводиться до `TIMESTAMP`, щоб `RANGE ... INTERVAL` був однозначним. `AVG` ігнорує `NULL` (дні без поїздок). На відміну від `days_in_window`, `valid_days_in_window` враховує кількість днів без нульового `avg_fare` між поточою датою та датою з +7 днів від поточної.

In [18]:
%%sql
SELECT
    pickup_zone_id,
    ts_day,
    avg_fare,
    (AVG(avg_fare) OVER w7)::NUMERIC(8, 2) AS rolling_avg_fare_7d,
    COUNT(avg_fare) OVER w7 AS valid_days_in_window,
    COUNT(*) OVER w7 AS days_in_window
FROM t7_hw_taxi_daily
WINDOW w7 AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day::TIMESTAMP
    RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
16182 rows affected.

[(1, datetime.date(2026, 7, 1), Decimal('70.20'), Decimal('70.20'), 1, 1),
 (1, datetime.date(2026, 7, 2), Decimal('33.35'), Decimal('51.78'), 2, 2),
 (1, datetime.date(2026, 7, 3), Decimal('109.00'), Decimal('70.85'), 3, 3),
 (1, datetime.date(2026, 7, 4), Decimal('97.10'), Decimal('77.41'), 4, 4),
 (1, datetime.date(2026, 7, 5), Decimal('88.88'), Decimal('79.71'), 5, 5),
 (1, datetime.date(2026, 7, 6), Decimal('117.50'), Decimal('86.01'), 6, 6),
 (1, datetime.date(2026, 7, 7), Decimal('149.15'), Decimal('95.03'), 7, 7),
 (1, datetime.date(2026, 7, 8), Decimal('109.70'), Decimal('100.67'), 7, 7),
 (1, datetime.date(2026, 7, 9), Decimal('126.67'), Decimal('114.00'), 7, 7),
 (1, datetime.date(2026, 7, 10), Decimal('99.00'), Decimal('112.57'), 7, 7),
 (1, datetime.date(2026, 7, 11), Decimal('76.67'), Decimal('109.65'), 7, 7),
 (1, datetime.date(2026, 7, 12), Decimal('102.42'), Decimal('111.59'), 7, 7),
 (1, datetime.date(2026, 7, 13), Decimal('117.33'), Decimal('111.56'), 7, 7),
 (1, datetime.date(2026, 7, 14), Decimal('99.00'), Decimal('104.40'), 7, 7),
 (1, datetime.date(2026, 7, 15), Decimal('120.00'), Decimal('105.87'), 7, 7),
 (1, datetime.date(2026, 7, 16), Decimal('115.00'), Decimal('104.20'), 7, 7),
 (1, datetime.date(2026, 7, 17), Decimal('112.67'), Decimal('106.16'), 7, 7),
 (1, datetime.date(2026, 7, 18), Decimal('71.77'), Decimal('105.46'), 7, 7),
 (1, datetime.date(2026, 7, 19), Decimal('117.50'), Decimal('107.61'), 7, 7),
 (1, datetime.date(2026, 7, 20), Decimal('119.22'), Decimal('107.88'), 7, 7),
 (1, datetime.date(2026, 7, 21), Decimal('90.37'), Decimal('106.65'), 7, 7),
 (1, datetime.date(2026, 7, 22), Decimal('128.00'), Decimal('107.79'), 7, 7),
 (1, datetime.date(2026, 7, 23), Decimal('124.67'), Decimal('109.17'), 7, 7),
 (1, datetime.date(2026, 7, 24), Decimal('70.47'), Decimal('103.14'), 7, 7),
 (1, datetime.date(2026, 7, 25), Decimal('73.75'), Decimal('103.43'), 7, 7),
 (1, datetime.date(2026, 7, 26), Decimal('118.88'), Decimal('103.62'), 7, 7),
 (1, datetime.date(2026, 7, 27), Decimal('124.00'), Decimal('104.31'), 7, 7),
 (1, datetime.date(2026, 7, 28), Decimal('104.50'), Decimal('106.32'), 7, 7),
 (1, datetime.date(2026, 7, 29), Decimal('115.44'), Decimal('104.53'), 7, 7),
 (1, datetime.date(2026, 7, 30), Decimal('107.50'), Decimal('102.08'), 7, 7),
 (1, datetime.date(2026, 7, 31), Decimal('118.75'), Decimal('108.97'), 7, 7),
 (1, datetime.date(2026, 8, 1), Decimal('116.75'), Decimal('115.12'), 7, 7),
 (1, datetime.date(2026, 8, 2), Decimal('77.12'), Decimal('109.15'), 7, 7),
 (1, datetime.date(2026, 8, 3), Decimal('120.00'), Decimal('108.58'), 7, 7),
 (1, datetime.date(2026, 8, 4), Decimal('126.67'), Decimal('111.75'), 7, 7),
 (1, datetime.date(2026, 8, 5), Decimal('30.00'), Decimal('99.54'), 7, 7),
 (1, datetime.date(2026, 8, 6), Decimal('107.67'), Decimal('99.57'), 7, 7),
 (1, datetime.date(2026, 8, 7), Decimal('119.10'), Decimal('99.62'), 7, 7),
 (1, datetime.date(2026, 8, 8), Decimal('115.82'), Decimal('99.48'), 7, 7),
 (1, datetime.date(2026, 8, 9), Decimal('114.77'), Decimal('104.86'), 7, 7),
 (1, datetime.date(2026, 8, 10), Decimal('90.00'), Decimal('100.58'), 7, 7),
 (1, datetime.date(2026, 8, 11), Decimal('110.00'), Decimal('98.19'), 7, 7),
 (1, datetime.date(2026, 8, 12), Decimal('105.32'), Decimal('108.95'), 7, 7),
 (1, datetime.date(2026, 8, 13), Decimal('105.67'), Decimal('108.67'), 7, 7),
 (1, datetime.date(2026, 8, 14), Decimal('130.00'), Decimal('110.23'), 7, 7),
 (1, datetime.date(2026, 8, 15), Decimal('108.33'), Decimal('109.16'), 7, 7),
 (1, datetime.date(2026, 8, 16), Decimal('89.45'), Decimal('105.54'), 7, 7),
 (1, datetime.date(2026, 8, 17), Decimal('82.25'), Decimal('104.43'), 7, 7),
 (1, datetime.date(2026, 8, 18), Decimal('57.60'), Decimal('96.95'), 7, 7),
 (1, datetime.date(2026, 8, 19), Decimal('107.89'), Decimal('97.31'), 7, 7),
 (1, datetime.date(2026, 8, 20), Decimal('100.40'), Decimal('96.56'), 7, 7),
 (1, datetime.date(2026, 8, 21), Decimal('115.00'), Decimal('94.42'), 7, 7),
 (1, datetime.date(2026, 8, 22), Decimal('125.00'), Decimal('96.80'), 7, 7),
 (1, datetime.date(2026, 8, 23), Decimal('106.50'), Decimal('99.23'), 7, 7),
 (1, datetime.date(2026, 8, 24), Decimal('83.33'), Decimal('99.39'), 7, 7),
 (1, datetime.date(2026, 8, 25), Decimal('121.96'), Decimal('108.58'), 7, 7),
 (1, datetime.date(2026, 8, 26), Decimal('100.86'), Decimal('107.58'), 7, 7),
 (1, datetime.date(2026, 8, 27), Decimal('103.00'), Decimal('107.95'), 7, 7),
 (1, datetime.date(2026, 8, 28), Decimal('101.50'), Decimal('106.02'), 7, 7),
 (1, datetime.date(2026, 8, 29), Decimal('122.50'), Decimal('105.66'), 7, 7),
 (1, datetime.date(2026, 8, 30), Decimal('50.00'), Decimal('97.59'), 7, 7),
 (1, datetime.date(2026, 8, 31), Decimal('107.40'), Decimal('101.03'), 7, 7),
 (2, datetime.date(2026, 7, 1), None, None, 0, 1),
 (2, datetime.date(2026, 7, 2), None, None, 0, 2),
 (2, datetime.date(2026, 7, 3), None, None, 0, 3),
 (2, datetime.date(2026, 7, 4), Decimal('35.90'), Decimal('35.90'), 1, 4),
 (2, datetime.date(2026, 7, 5), None, Decimal('35.90'), 1, 5),
 (2, datetime.date(2026, 7, 6), None, Decimal('35.90'), 1, 6),
 (2, datetime.date(2026, 7, 7), None, Decimal('35.90'), 1, 7),
 (2, datetime.date(2026, 7, 8), Decimal('70.00'), Decimal('52.95'), 2, 7),
 (2, datetime.date(2026, 7, 9), None, Decimal('52.95'), 2, 7),
 (2, datetime.date(2026, 7, 10), None, Decimal('52.95'), 2, 7),
 (2, datetime.date(2026, 7, 11), Decimal('71.15'), Decimal('70.58'), 2, 7),
 (2, datetime.date(2026, 7, 12), None, Decimal('70.58'), 2, 7),
 (2, datetime.date(2026, 7, 13), None, Decimal('70.58'), 2, 7),
 (2, datetime.date(2026, 7, 14), None, Decimal('70.58'), 2, 7),
 (2, datetime.date(2026, 7, 15), None, Decimal('71.15'), 1, 7),
 (2, datetime.date(2026, 7, 16), Decimal('32.40'), Decimal('51.78'), 2, 7),
 (2, datetime.date(2026, 7, 17), None, Decimal('51.78'), 2, 7),
 (2, datetime.date(2026, 7, 18), Decimal('19.80'), Decimal('26.10'), 2, 7),
 (2, datetime.date(2026, 7, 19), None, Decimal('26.10'), 2, 7),
 (2, datetime.date(2026, 7, 20), None, Decimal('26.10'), 2, 7),
 (2, datetime.date(2026, 7, 21), Decimal('70.00'), Decimal('40.73'), 3, 7),
 (2, datetime.date(2026, 7, 22), None, Decimal('40.73'), 3, 7),
 (2, datetime.date(2026, 7, 23), Decimal('66.70'), Decimal('52.17'), 3, 7),
 (2, datetime.date(2026, 7, 24), None, Decimal('52.17'), 3, 7),
 (2, datetime.date(2026, 7, 25), None, Decimal('68.35'), 2, 7),
 (2, datetime.date(2026, 7, 26), None, Decimal('68.35'), 2, 7),
 (2, datetime.date(2026, 7, 27), None, Decimal('68.35'), 2, 7),
 (2, datetime.date(2026, 7, 28), None, Decimal('66.70'), 1, 7),
 (2, datetime.date(2026, 7, 29), Decimal('55.50'), Decimal('61.10'), 2, 7),
 (2, datetime.date(2026, 7, 30), Decimal('44.30'), Decimal('49.90'), 2, 7),
 (2, datetime.date(2026, 7, 31), None, Decimal('49.90'), 2, 7),
 (2, datetime.date(2026, 8, 1), None, Decimal('49.90'), 2, 7),
 (2, datetime.date(2026, 8, 2), None, Decimal('49.90'), 2, 7),
 (2, datetime.date(2026, 8, 3), None, Decimal('49.90'), 2, 7),
 (2, datetime.date(2026, 8, 4), None, Decimal('49.90'), 2, 7),
 (2, datetime.date(2026, 8, 5), Decimal('16.30'), Decimal('30.30'), 2, 7),
 (2, datetime.date(2026, 8, 6), None, Decimal('16.30'), 1, 7),
 (2, datetime.date(2026, 8, 7), None, Decimal('16.30'), 1, 7),
 (2, datetime.date(2026, 8, 8), None, Decimal('16.30'), 1, 7),
 (2, datetime.date(2026, 8, 9), None, Decimal('16.30'), 1, 7),
 (2, datetime.date(2026, 8, 10), None, Decimal('16.30'), 1, 7),
 (2, datetime.date(2026, 8, 11), None, Decimal('16.30'), 1, 7),
 (2, datetime.date(2026, 8, 12), Decimal('45.00'), Decimal('45.00'), 1, 7),
 (2, datetime.date(2026, 8, 13), None, Decimal('45.00'), 1, 7),
 (2, datetime.date(2026, 8, 14), None, Decimal('45.00'), 1, 7),
 (2, datetime.date(2026, 8, 15), None, Decimal('45.00'), 1, 7),
 (2, datetime.date(2026, 8, 16), None, Decimal('45.00'), 1, 7),
 (2, datetime.date(2026, 8, 17), None, Decimal('45.00'), 1, 7),
 (2, datetime.date(2026, 8, 18), Decimal('26.80'), Decimal('35.90'), 2, 7),
 (2, datetime.date(2026, 8, 19), None, Decimal('26.80'), 1, 7),
 (2, datetime.date(2026, 8, 20), None, Decimal('26.80'), 1, 7),
 (2, datetime.date(2026, 8, 21), Decimal('151.80'), Decimal('89.30'), 2, 7),
 (2, datetime.date(2026, 8, 22), Decimal('75.10'), Decimal('84.57'), 3, 7),
 (2, datetime.date(2026, 8, 23), None, Decimal('84.57'), 3, 7),
 (2, datetime.date(2026, 8, 24), Decimal('38.00'), Decimal('72.93'), 4, 7),
 (2, datetime.date(2026, 8, 25), None, Decimal('88.30'), 3, 7),
 (2, datetime.date(2026, 8, 26), None, Decimal('88.30'), 3, 7),
 (2, datetime.date(2026, 8, 27), None, Decimal('88.30'), 3, 7),
 (2, datetime.date(2026, 8, 28), None, Decimal('56.55'), 2, 7),
 (2, datetime.date(2026, 8, 29), None, Decimal('38.00'), 1, 7),
 (2, datetime.date(2026, 8, 30), Decimal('70.00'), Decimal('54.00'), 2, 7),
 (2, datetime.date(2026, 8, 31), None, Decimal('70.00'), 1, 7),
 (3, datetime.date(2026, 7, 1), Decimal('24.70'), Decimal('24.70'), 1, 1),
 (3, datetime.date(2026, 7, 2), None, Decimal('24.70'), 1, 2),
 (3, datetime.date(2026, 7, 3), None, Decimal('24.70'), 1, 3),
 (3, datetime.date(2026, 7, 4), Decimal('37.53'), Decimal('31.12'), 2, 4),
 (3, datetime.date(2026, 7, 5), Decimal('36.90'), Decimal('33.04'), 3, 5),
 (3, datetime.date(2026, 7, 6), Decimal('37.22'), Decimal('34.09'), 4, 6),
 (3, datetime.date(2026, 7, 7), Decimal('14.25'), Decimal('30.12'), 5, 7),
 (3, datetime.date(2026, 7, 8), None, Decimal('31.48'), 4, 7),
 (3, datetime.date(2026, 7, 9), Decimal('41.01'), Decimal('33.38'), 5, 7),
 (3, datetime.date(2026, 7, 10), Decimal('17.90'), Decimal('30.80'), 6, 7),
 (3, datetime.date(2026, 7, 11), Decimal('18.22'), Decimal('27.58'), 6, 7),
 (3, datetime.date(2026, 7, 12), Decimal('27.67'), Decimal('26.05'), 6, 7),
 (3, datetime.date(2026, 7, 13), Decimal('17.04'), Decimal('22.68'), 6, 7),
 (3, datetime.date(2026, 7, 14), Decimal('23.90'), Decimal('24.29'), 6, 7),
 (3, datetime.date(2026, 7, 15), Decimal('39.05'), Decimal('26.40'), 7, 7),
 (3, datetime.date(2026, 7, 16), Decimal('59.20'), Decimal('29.00'), 7, 7),
 (3, datetime.date(2026, 7, 17), Decimal('21.83'), Decimal('29.56'), 7, 7),
 (3, datetime.date(2026, 7, 18), Decimal('36.35'), Decimal('32.15'), 7, 7),
 (3, datetime.date(2026, 7, 19), Decimal('24.42'), Decimal('31.68'), 7, 7),
 (3, datetime.date(2026, 7, 20), Decimal('34.36'), Decimal('34.16'), 7, 7),
 (3, datetime.date(2026, 7, 21), Decimal('9.73'), Decimal('32.13'), 7, 7),
 (3, datetime.date(2026, 7, 22), Decimal('27.17'), Decimal('30.44'), 7, 7),
 (3, datetime.date(2026, 7, 23), Decimal('9.43'), Decimal('23.33'), 7, 7),
 (3, datetime.date(2026, 7, 24), Decimal('16.86'), Decimal('22.62'), 7, 7),
 (3, datetime.date(2026, 7, 25), Decimal('15.94'), Decimal('19.70'), 7, 7),
 (3, datetime.date(2026, 7, 26), Decimal('30.69'), Decimal('20.60'), 7, 7),
 (3, datetime.date(2026, 7, 27), Decimal('25.04'), Decimal('19.27'), 7, 7),
 (3, datetime.date(2026, 7, 28), Decimal('30.39'), Decimal('22.22'), 7, 7),
 (3, datetime.date(2026, 7, 29), Decimal('22.54'), Decimal('21.56'), 7, 7),
 (3, datetime.date(2026, 7, 30), Decimal('24.08'), Decimal('23.65'), 7, 7),
 (3, datetime.date(2026, 7, 31), Decimal('18.44'), Decimal('23.87'), 7, 7),
 (3, datetime.date(2026, 8, 1), Decimal('28.58'), Decimal('25.68'), 7, 7),
 (3, datetime.date(2026, 8, 2), Decimal('27.98'), Decimal('25.29'), 7, 7),
 (3, datetime.date(2026, 8, 3), Decimal('10.89'), Decimal('23.27'), 7, 7),
 (3, datetime.date(2026, 8, 4), None, Decimal('22.09'), 6, 7),
 (3, datetime.date(2026, 8, 5), Decimal('26.97'), Decimal('22.82'), 6, 7),
 (3, datetime.date(2026, 8, 6), Decimal('40.21'), Decimal('25.51'), 6, 7),
 (3, datetime.date(2026, 8, 7), Decimal('9.67'), Decimal('24.05'), 6, 7),
 (3, datetime.date(2026, 8, 8), Decimal('24.95'), Decimal('23.45'), 6, 7),
 (3, datetime.date(2026, 8, 9), Decimal('37.86'), Decimal('25.09'), 6, 7),
 (3, datetime.date(2026, 8, 10), Decimal('27.90'), Decimal('27.93'), 6, 7),
 (3, datetime.date(2026, 8, 11), Decimal('8.39'), Decimal('25.14'), 7, 7),
 (3, datetime.date(2026, 8, 12), Decimal('35.90'), Decimal('26.41'), 7, 7),
 (3, datetime.date(2026, 8, 13), Decimal('53.55'), Decimal('28.32'), 7, 7),
 (3, datetime.date(2026, 8, 14), Decimal('21.52'), Decimal('30.01'), 7, 7),
 (3, datetime.date(2026, 8, 15), Decimal('23.46'), Decimal('29.80'), 7, 7),
 (3, datetime.date(2026, 8, 16), Decimal('25.36'), Decimal('28.01'), 7, 7),
 (3, datetime.date(2026, 8, 17), Decimal('43.73'), Decimal('30.27'), 7, 7),
 (3, datetime.date(2026, 8, 18), Decimal('23.24'), Decimal('32.39'), 7, 7),
 (3, datetime.date(2026, 8, 19), Decimal('22.74'), Decimal('30.51'), 7, 7),
 (3, datetime.date(2026, 8, 20), Decimal('18.85'), Decimal('25.56'), 7, 7),
 (3, datetime.date(2026, 8, 21), Decimal('35.36'), Decimal('27.53'), 7, 7),
 (3, datetime.date(2026, 8, 22), Decimal('32.83'), Decimal('28.87'), 7, 7),
 (3, datetime.date(2026, 8, 23), Decimal('30.31'), Decimal('29.58'), 7, 7),
 (3, datetime.date(2026, 8, 24), Decimal('3.00'), Decimal('23.76'), 7, 7),
 (3, datetime.date(2026, 8, 25), Decimal('20.70'), Decimal('23.40'), 7, 7),
 (3, datetime.date(2026, 8, 26), Decimal('31.11'), Decimal('24.59'), 7, 7),
 (3, datetime.date(2026, 8, 27), Decimal('39.34'), Decimal('27.52'), 7, 7),
 (3, datetime.date(2026, 8, 28), Decimal('16.02'), Decimal('24.76'), 7, 7),
 (3, datetime.date(2026, 8, 29), Decimal('27.79'), Decimal('24.04'), 7, 7),
 (3, datetime.date(2026, 8, 30), Decimal('41.85'), Decimal('25.69'), 7, 7),
 (3, datetime.date(2026, 8, 31), Decimal('44.88'), Decimal('31.67'), 7, 7),
 (4, datetime.date(2026, 7, 1), Decimal('18.62'), Decimal('18.62'), 1, 1),
 (4, datetime.date(2026, 7, 2), Decimal('19.55'), Decimal('19.09'), 2, 2),
 (4, datetime.date(2026, 7, 3), Decimal('17.92'), Decimal('18.70'), 3, 3),
 (4, datetime.date(2026, 7, 4), Decimal('19.11'), Decimal('18.80'), 4, 4),
 (4, datetime.date(2026, 7, 5), Decimal('18.71'), Decimal('18.78'), 5, 5),
 (4, datetime.date(2026, 7, 6), Decimal('19.15'), Decimal('18.84'), 6, 6),
 (4, datetime.date(2026, 7, 7), Decimal('19.56'), Decimal('18.95'), 7, 7),
 (4, datetime.date(2026, 7, 8), Decimal('18.52'), Decimal('18.93'), 7, 7),
 (4, datetime.date(2026, 7, 9), Decimal('18.37'), Decimal('18.76'), 7, 7),
 (4, datetime.date(2026, 7, 10), Decimal('18.00'), Decimal('18.77'), 7, 7),
 (4, datetime.date(2026, 7, 11), Decimal('18.51'), Decimal('18.69'), 7, 7),
 (4, datetime.date(2026, 7, 12), Decimal('19.07'), Decimal('18.74'), 7, 7),
 (4, datetime.date(2026, 7, 13), Decimal('18.42'), Decimal('18.64'), 7, 7),
 (4, datetime.date(2026, 7, 14), Decimal('18.17'), Decimal('18.44'), 7, 7),
 (4, datetime.date(2026, 7, 15), Decimal('19.03'), Decimal('18.51'), 7, 7),
 (4, datetime.date(2026, 7, 16), Decimal('20.38'), Decimal('18.80'), 7, 7),
 (4, datetime.date(2026, 7, 17), Decimal('18.98'), Decimal('18.94'), 7, 7),
 (4, datetime.date(2026, 7, 18), Decimal('19.09'), Decimal('19.02'), 7, 7),
 (4, datetime.date(2026, 7, 19), Decimal('19.25'), Decimal('19.05'), 7, 7),
 (4, datetime.date(2026, 7, 20), Decimal('21.00'), Decimal('19.41'), 7, 7),
 (4, datetime.date(2026, 7, 21), Decimal('18.99'), Decimal('19.53'), 7, 7),
 (4, datetime.date(2026, 7, 22), Decimal('20.04'), Decimal('19.68'), 7, 7),
 (4, datetime.date(2026, 7, 23), Decimal('18.82'), Decimal('19.45'), 7, 7),
 (4, datetime.date(2026, 7, 24), Decimal('18.36'), Decimal('19.36'), 7, 7),
 (4, datetime.date(2026, 7, 25), Decimal('18.61'), Decimal('19.30'), 7, 7),
 (4, datetime.date(2026, 7, 26), Decimal('18.91'), Decimal('19.25'), 7, 7),
 (4, datetime.date(2026, 7, 27), Decimal('18.50'), Decimal('18.89'), 7, 7),
 (4, datetime.date(2026, 7, 28), Decimal('20.41'), Decimal('19.09'), 7, 7),
 (4, datetime.date(2026, 7, 29), Decimal('19.73'), Decimal('19.05'), 7, 7),
 (4, datetime.date(2026, 7, 30), Decimal('20.54'), Decimal('19.29'), 7, 7),
 (4, datetime.date(2026, 7, 31), Decimal('18.55'), Decimal('19.32'), 7, 7),
 (4, datetime.date(2026, 8, 1), Decimal('18.99'), Decimal('19.38'), 7, 7),
 (4, datetime.date(2026, 8, 2), Decimal('19.04'), Decimal('19.39'), 7, 7),
 (4, datetime.date(2026, 8, 3), Decimal('21.92'), Decimal('19.88'), 7, 7),
 (4, datetime.date(2026, 8, 4), Decimal('19.80'), Decimal('19.80'), 7, 7),
 (4, datetime.date(2026, 8, 5), Decimal('19.09'), Decimal('19.70'), 7, 7),
 (4, datetime.date(2026, 8, 6), Decimal('20.18'), Decimal('19.65'), 7, 7),
 (4, datetime.date(2026, 8, 7), Decimal('19.16'), Decimal('19.74'), 7, 7),
 (4, datetime.date(2026, 8, 8), Decimal('19.76'), Decimal('19.85'), 7, 7),
 (4, datetime.date(2026, 8, 9), Decimal('18.60'), Decimal('19.79'), 7, 7),
 (4, datetime.date(2026, 8, 10), Decimal('18.45'), Decimal('19.29'), 7, 7),
 (4, datetime.date(2026, 8, 11), Decimal('19.99'), Decimal('19.32'), 7, 7),
 (4, datetime.date(2026, 8, 12), Decimal('19.52'), Decimal('19.38'), 7, 7),
 (4, datetime.date(2026, 8, 13), Decimal('18.96'), Decimal('19.21'), 7, 7),
 (4, datetime.date(2026, 8, 14), Decimal('19.30'), Decimal('19.23'), 7, 7),
 (4, datetime.date(2026, 8, 15), Decimal('18.54'), Decimal('19.05'), 7, 7),
 (4, datetime.date(2026, 8, 16), Decimal('18.53'), Decimal('19.04'), 7, 7),
 (4, datetime.date(2026, 8, 17), Decimal('19.34'), Decimal('19.17'), 7, 7),
 (4, datetime.date(2026, 8, 18), Decimal('19.95'), Decimal('19.16'), 7, 7),
 (4, datetime.date(2026, 8, 19), Decimal('19.85'), Decimal('19.21'), 7, 7),
 (4, datetime.date(2026, 8, 20), Decimal('19.55'), Decimal('19.29'), 7, 7),
 (4, datetime.date(2026, 8, 21), Decimal('19.04'), Decimal('19.26'), 7, 7),
 (4, datetime.date(2026, 8, 22), Decimal('19.13'), Decimal('19.34'), 7, 7),
 (4, datetime.date(2026, 8, 23), Decimal('18.67'), Decimal('19.36'), 7, 7),
 (4, datetime.date(2026, 8, 24), Decimal('19.38'), Decimal('19.37'), 7, 7),
 (4, datetime.date(2026, 8, 25), Decimal('18.71'), Decimal('19.19'), 7, 7),
 (4, datetime.date(2026, 8, 26), Decimal('19.90'), Decimal('19.20'), 7, 7),
 (4, datetime.date(2026, 8, 27), Decimal('19.85'), Decimal('19.24'), 7, 7),
 (4, datetime.date(2026, 8, 28), Decimal('19.84'), Decimal('19.35'), 7, 7),
 (4, datetime.date(2026, 8, 29), Decimal('19.06'), Decimal('19.34'), 7, 7),
 (4, datetime.date(2026, 8, 30), Decimal('18.81'), Decimal('19.36'), 7, 7),
 (4, datetime.date(2026, 8, 31), Decimal('18.98'), Decimal('19.31'), 7, 7),
 (5, datetime.date(2026, 7, 1), None, None, 0, 1),
 (5, datetime.date(2026, 7, 2), None, None, 0, 2),
 (5, datetime.date(2026, 7, 3), None, None, 0, 3),
 (5, datetime.date(2026, 7, 4), Decimal('37.89'), Decimal('37.89'), 1, 4),
 (5, datetime.date(2026, 7, 5), None, Decimal('37.89'), 1, 5),
 (5, datetime.date(2026, 7, 6), None, Decimal('37.89'), 1, 6),
 (5, datetime.date(2026, 7, 7), None, Decimal('37.89'), 1, 7),
 (5, datetime.date(2026, 7, 8), None, Decimal('37.89'), 1, 7),
 (5, datetime.date(2026, 7, 9), None, Decimal('37.89'), 1, 7),
 (5, datetime.date(2026, 7, 10), None, Decimal('37.89'), 1, 7),
 (5, datetime.date(2026, 7, 11), None, None, 0, 7),
 (5, datetime.date(2026, 7, 12), None, None, 0, 7),
 (5, datetime.date(2026, 7, 13), None, None, 0, 7),
 (5, datetime.date(2026, 7, 14), None, None, 0, 7),
 (5, datetime.date(2026, 7, 15), None, None, 0, 7),
 (5, datetime.date(2026, 7, 16), None, None, 0, 7),
 (5, datetime.date(2026, 7, 17), None, None, 0, 7),
 (5, datetime.date(2026, 7, 18), None, None, 0, 7),
 (5, datetime.date(2026, 7, 19), None, None, 0, 7),
 (5, datetime.date(2026, 7, 20), None, None, 0, 7),
 (5, datetime.date(2026, 7, 21), None, None, 0, 7),
 (5, datetime.date(2026, 7, 22), None, None, 0, 7),
 (5, datetime.date(2026, 7, 23), None, None, 0, 7),
 (5, datetime.date(2026, 7, 24), None, None, 0, 7),
 (5, datetime.date(2026, 7, 25), None, None, 0, 7),
 (5, datetime.date(2026, 7, 26), Decimal('61.10'), Decimal('61.10'), 1, 7),
 (5, datetime.date(2026, 7, 27), None, Decimal('61.10'), 1, 7),
 (5, datetime.date(2026, 7, 28), None, Decimal('61.10'), 1, 7),
 (5, datetime.date(2026, 7, 29), None, Decimal('61.10'), 1, 7),
 (5, datetime.date(2026, 7, 30), None, Decimal('61.10'), 1, 7),

### Feature 3. Rolling 30-day fare volatility

In [20]:
%%sql
SELECT
    pickup_zone_id,
    ts_day,
    avg_fare,
    (
        STDDEV_SAMP(avg_fare) OVER w30
    )::NUMERIC(8, 2)  AS rolling_std_fare_30d,
    COUNT(*) OVER w30 AS days_in_window
FROM t7_hw_taxi_daily
WINDOW w30 AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day::TIMESTAMP
    RANGE BETWEEN INTERVAL '29 days' PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
16182 rows affected.

[(1, datetime.date(2026, 7, 1), Decimal('70.20'), None, 1),
 (1, datetime.date(2026, 7, 2), Decimal('33.35'), Decimal('26.06'), 2),
 (1, datetime.date(2026, 7, 3), Decimal('109.00'), Decimal('37.83'), 3),
 (1, datetime.date(2026, 7, 4), Decimal('97.10'), Decimal('33.56'), 4),
 (1, datetime.date(2026, 7, 5), Decimal('88.88'), Decimal('29.51'), 5),
 (1, datetime.date(2026, 7, 6), Decimal('117.50'), Decimal('30.58'), 6),
 (1, datetime.date(2026, 7, 7), Decimal('149.15'), Decimal('36.72'), 7),
 (1, datetime.date(2026, 7, 8), Decimal('109.70'), Decimal('34.39'), 8),
 (1, datetime.date(2026, 7, 9), Decimal('126.67'), Decimal('33.67'), 9),
 (1, datetime.date(2026, 7, 10), Decimal('99.00'), Decimal('31.75'), 10),
 (1, datetime.date(2026, 7, 11), Decimal('76.67'), Decimal('30.93'), 11),
 (1, datetime.date(2026, 7, 12), Decimal('102.42'), Decimal('29.52'), 12),
 (1, datetime.date(2026, 7, 13), Decimal('117.33'), Decimal('28.75'), 13),
 (1, datetime.date(2026, 7, 14), Decimal('99.00'), Decimal('27.63'), 14),
 (1, datetime.date(2026, 7, 15), Decimal('120.00'), Decimal('27.13'), 15),
 (1, datetime.date(2026, 7, 16), Decimal('115.00'), Decimal('26.44'), 16),
 (1, datetime.date(2026, 7, 17), Decimal('112.67'), Decimal('25.74'), 17),
 (1, datetime.date(2026, 7, 18), Decimal('71.77'), Decimal('26.00'), 18),
 (1, datetime.date(2026, 7, 19), Decimal('117.50'), Decimal('25.55'), 19),
 (1, datetime.date(2026, 7, 20), Decimal('119.22'), Decimal('25.18'), 20),
 (1, datetime.date(2026, 7, 21), Decimal('90.37'), Decimal('24.69'), 21),
 (1, datetime.date(2026, 7, 22), Decimal('128.00'), Decimal('24.72'), 22),
 (1, datetime.date(2026, 7, 23), Decimal('124.67'), Decimal('24.56'), 23),
 (1, datetime.date(2026, 7, 24), Decimal('70.47'), Decimal('24.99'), 24),
 (1, datetime.date(2026, 7, 25), Decimal('73.75'), Decimal('25.14'), 25),
 (1, datetime.date(2026, 7, 26), Decimal('118.88'), Decimal('24.86'), 26),
 (1, datetime.date(2026, 7, 27), Decimal('124.00'), Decimal('24.74'), 27),
 (1, datetime.date(2026, 7, 28), Decimal('104.50'), Decimal('24.28'), 28),
 (1, datetime.date(2026, 7, 29), Decimal('115.44'), Decimal('23.95'), 29),
 (1, datetime.date(2026, 7, 30), Decimal('107.50'), Decimal('23.54'), 30),
 (1, datetime.date(2026, 7, 31), Decimal('118.75'), Decimal('22.82'), 30),
 (1, datetime.date(2026, 8, 1), Decimal('116.75'), Decimal('18.41'), 30),
 (1, datetime.date(2026, 8, 2), Decimal('77.12'), Decimal('19.26'), 30),
 (1, datetime.date(2026, 8, 3), Decimal('120.00'), Decimal('19.30'), 30),
 (1, datetime.date(2026, 8, 4), Decimal('126.67'), Decimal('19.26'), 30),
 (1, datetime.date(2026, 8, 5), Decimal('30.00'), Decimal('23.98'), 30),
 (1, datetime.date(2026, 8, 6), Decimal('107.67'), Decimal('22.57'), 30),
 (1, datetime.date(2026, 8, 7), Decimal('119.10'), Decimal('22.70'), 30),
 (1, datetime.date(2026, 8, 8), Decimal('115.82'), Decimal('22.43'), 30),
 (1, datetime.date(2026, 8, 9), Decimal('114.77'), Decimal('22.48'), 30),
 (1, datetime.date(2026, 8, 10), Decimal('90.00'), Decimal('22.02'), 30),
 (1, datetime.date(2026, 8, 11), Decimal('110.00'), Decimal('22.03'), 30),
 (1, datetime.date(2026, 8, 12), Decimal('105.32'), Decimal('21.92'), 30),
 (1, datetime.date(2026, 8, 13), Decimal('105.67'), Decimal('21.89'), 30),
 (1, datetime.date(2026, 8, 14), Decimal('130.00'), Decimal('22.19'), 30),
 (1, datetime.date(2026, 8, 15), Decimal('108.33'), Decimal('22.13'), 30),
 (1, datetime.date(2026, 8, 16), Decimal('89.45'), Decimal('22.28'), 30),
 (1, datetime.date(2026, 8, 17), Decimal('82.25'), Decimal('21.82'), 30),
 (1, datetime.date(2026, 8, 18), Decimal('57.60'), Decimal('23.36'), 30),
 (1, datetime.date(2026, 8, 19), Decimal('107.89'), Decimal('23.19'), 30),
 (1, datetime.date(2026, 8, 20), Decimal('100.40'), Decimal('23.07'), 30),
 (1, datetime.date(2026, 8, 21), Decimal('115.00'), Decimal('22.71'), 30),
 (1, datetime.date(2026, 8, 22), Decimal('125.00'), Decimal('22.72'), 30),
 (1, datetime.date(2026, 8, 23), Decimal('106.50'), Decimal('21.89'), 30),
 (1, datetime.date(2026, 8, 24), Decimal('83.33'), Decimal('21.49'), 30),
 (1, datetime.date(2026, 8, 25), Decimal('121.96'), Decimal('21.57'), 30),
 (1, datetime.date(2026, 8, 26), Decimal('100.86'), Decimal('21.26'), 30),
 (1, datetime.date(2026, 8, 27), Decimal('103.00'), Decimal('21.26'), 30),
 (1, datetime.date(2026, 8, 28), Decimal('101.50'), Decimal('21.15'), 30),
 (1, datetime.date(2026, 8, 29), Decimal('122.50'), Decimal('21.43'), 30),
 (1, datetime.date(2026, 8, 30), Decimal('50.00'), Decimal('23.36'), 30),
 (1, datetime.date(2026, 8, 31), Decimal('107.40'), Decimal('23.21'), 30),
 (2, datetime.date(2026, 7, 1), None, None, 1),
 (2, datetime.date(2026, 7, 2), None, None, 2),
 (2, datetime.date(2026, 7, 3), None, None, 3),
 (2, datetime.date(2026, 7, 4), Decimal('35.90'), None, 4),
 (2, datetime.date(2026, 7, 5), None, None, 5),
 (2, datetime.date(2026, 7, 6), None, None, 6),
 (2, datetime.date(2026, 7, 7), None, None, 7),
 (2, datetime.date(2026, 7, 8), Decimal('70.00'), Decimal('24.11'), 8),
 (2, datetime.date(2026, 7, 9), None, Decimal('24.11'), 9),
 (2, datetime.date(2026, 7, 10), None, Decimal('24.11'), 10),
 (2, datetime.date(2026, 7, 11), Decimal('71.15'), Decimal('20.03'), 11),
 (2, datetime.date(2026, 7, 12), None, Decimal('20.03'), 12),
 (2, datetime.date(2026, 7, 13), None, Decimal('20.03'), 13),
 (2, datetime.date(2026, 7, 14), None, Decimal('20.03'), 14),
 (2, datetime.date(2026, 7, 15), None, Decimal('20.03'), 15),
 (2, datetime.date(2026, 7, 16), Decimal('32.40'), Decimal('21.08'), 16),
 (2, datetime.date(2026, 7, 17), None, Decimal('21.08'), 17),
 (2, datetime.date(2026, 7, 18), Decimal('19.80'), Decimal('23.35'), 18),
 (2, datetime.date(2026, 7, 19), None, Decimal('23.35'), 19),
 (2, datetime.date(2026, 7, 20), None, Decimal('23.35'), 20),
 (2, datetime.date(2026, 7, 21), Decimal('70.00'), Decimal('23.10'), 21),
 (2, datetime.date(2026, 7, 22), None, Decimal('23.10'), 22),
 (2, datetime.date(2026, 7, 23), Decimal('66.70'), Decimal('22.02'), 23),
 (2, datetime.date(2026, 7, 24), None, Decimal('22.02'), 24),
 (2, datetime.date(2026, 7, 25), None, Decimal('22.02'), 25),
 (2, datetime.date(2026, 7, 26), None, Decimal('22.02'), 26),
 (2, datetime.date(2026, 7, 27), None, Decimal('22.02'), 27),
 (2, datetime.date(2026, 7, 28), None, Decimal('22.02'), 28),
 (2, datetime.date(2026, 7, 29), Decimal('55.50'), Decimal('20.42'), 29),
 (2, datetime.date(2026, 7, 30), Decimal('44.30'), Decimal('19.31'), 30),
 (2, datetime.date(2026, 7, 31), None, Decimal('19.31'), 30),
 (2, datetime.date(2026, 8, 1), None, Decimal('19.31'), 30),
 (2, datetime.date(2026, 8, 2), None, Decimal('19.31'), 30),
 (2, datetime.date(2026, 8, 3), None, Decimal('19.64'), 30),
 (2, datetime.date(2026, 8, 4), None, Decimal('19.64'), 30),
 (2, datetime.date(2026, 8, 5), Decimal('16.30'), Decimal('22.21'), 30),
 (2, datetime.date(2026, 8, 6), None, Decimal('22.21'), 30),
 (2, datetime.date(2026, 8, 7), None, Decimal('22.28'), 30),
 (2, datetime.date(2026, 8, 8), None, Decimal('22.28'), 30),
 (2, datetime.date(2026, 8, 9), None, Decimal('22.28'), 30),
 (2, datetime.date(2026, 8, 10), None, Decimal('21.64'), 30),
 (2, datetime.date(2026, 8, 11), None, Decimal('21.64'), 30),
 (2, datetime.date(2026, 8, 12), Decimal('45.00'), Decimal('20.04'), 30),
 (2, datetime.date(2026, 8, 13), None, Decimal('20.04'), 30),
 (2, datetime.date(2026, 8, 14), None, Decimal('20.04'), 30),
 (2, datetime.date(2026, 8, 15), None, Decimal('21.07'), 30),
 (2, datetime.date(2026, 8, 16), None, Decimal('21.07'), 30),
 (2, datetime.date(2026, 8, 17), None, Decimal('19.50'), 30),
 (2, datetime.date(2026, 8, 18), Decimal('26.80'), Decimal('19.78'), 30),
 (2, datetime.date(2026, 8, 19), None, Decimal('19.78'), 30),
 (2, datetime.date(2026, 8, 20), None, Decimal('18.42'), 30),
 (2, datetime.date(2026, 8, 21), Decimal('151.80'), Decimal('44.63'), 30),
 (2, datetime.date(2026, 8, 22), Decimal('75.10'), Decimal('45.01'), 30),
 (2, datetime.date(2026, 8, 23), None, Decimal('45.01'), 30),
 (2, datetime.date(2026, 8, 24), Decimal('38.00'), Decimal('42.34'), 30),
 (2, datetime.date(2026, 8, 25), None, Decimal('42.34'), 30),
 (2, datetime.date(2026, 8, 26), None, Decimal('42.34'), 30),
 (2, datetime.date(2026, 8, 27), None, Decimal('42.34'), 30),
 (2, datetime.date(2026, 8, 28), None, Decimal('45.73'), 30),
 (2, datetime.date(2026, 8, 29), None, Decimal('49.74'), 30),
 (2, datetime.date(2026, 8, 30), Decimal('70.00'), Decimal('45.60'), 30),
 (2, datetime.date(2026, 8, 31), None, Decimal('45.60'), 30),
 (3, datetime.date(2026, 7, 1), Decimal('24.70'), None, 1),
 (3, datetime.date(2026, 7, 2), None, None, 2),
 (3, datetime.date(2026, 7, 3), None, None, 3),
 (3, datetime.date(2026, 7, 4), Decimal('37.53'), Decimal('9.07'), 4),
 (3, datetime.date(2026, 7, 5), Decimal('36.90'), Decimal('7.23'), 5),
 (3, datetime.date(2026, 7, 6), Decimal('37.22'), Decimal('6.26'), 6),
 (3, datetime.date(2026, 7, 7), Decimal('14.25'), Decimal('10.40'), 7),
 (3, datetime.date(2026, 7, 8), None, Decimal('10.40'), 8),
 (3, datetime.date(2026, 7, 9), Decimal('41.01'), Decimal('10.31'), 9),
 (3, datetime.date(2026, 7, 10), Decimal('17.90'), Decimal('10.80'), 10),
 (3, datetime.date(2026, 7, 11), Decimal('18.22'), Decimal('10.82'), 11),
 (3, datetime.date(2026, 7, 12), Decimal('27.67'), Decimal('10.13'), 12),
 (3, datetime.date(2026, 7, 13), Decimal('17.04'), Decimal('10.20'), 13),
 (3, datetime.date(2026, 7, 14), Decimal('23.90'), Decimal('9.73'), 14),
 (3, datetime.date(2026, 7, 15), Decimal('39.05'), Decimal('9.91'), 15),
 (3, datetime.date(2026, 7, 16), Decimal('59.20'), Decimal('12.85'), 16),
 (3, datetime.date(2026, 7, 17), Decimal('21.83'), Decimal('12.56'), 17),
 (3, datetime.date(2026, 7, 18), Decimal('36.35'), Decimal('12.22'), 18),
 (3, datetime.date(2026, 7, 19), Decimal('24.42'), Decimal('11.89'), 19),
 (3, datetime.date(2026, 7, 20), Decimal('34.36'), Decimal('11.57'), 20),
 (3, datetime.date(2026, 7, 21), Decimal('9.73'), Decimal('12.21'), 21),
 (3, datetime.date(2026, 7, 22), Decimal('27.17'), Decimal('11.87'), 22),
 (3, datetime.date(2026, 7, 23), Decimal('9.43'), Decimal('12.34'), 23),
 (3, datetime.date(2026, 7, 24), Decimal('16.86'), Decimal('12.27'), 24),
 (3, datetime.date(2026, 7, 25), Decimal('15.94'), Decimal('12.22'), 25),
 (3, datetime.date(2026, 7, 26), Decimal('30.69'), Decimal('11.96'), 26),
 (3, datetime.date(2026, 7, 27), Decimal('25.04'), Decimal('11.71'), 27),
 (3, datetime.date(2026, 7, 28), Decimal('30.39'), Decimal('11.48'), 28),
 (3, datetime.date(2026, 7, 29), Decimal('22.54'), Decimal('11.29'), 29),
 (3, datetime.date(2026, 7, 30), Decimal('24.08'), Decimal('11.08'), 30),
 (3, datetime.date(2026, 7, 31), Decimal('18.44'), Decimal('11.19'), 30),
 (3, datetime.date(2026, 8, 1), Decimal('28.58'), Decimal('10.99'), 30),
 (3, datetime.date(2026, 8, 2), Decimal('27.98'), Decimal('10.79'), 30),
 (3, datetime.date(2026, 8, 3), Decimal('10.89'), Decimal('10.97'), 30),
 (3, datetime.date(2026, 8, 4), None, Decimal('10.95'), 30),
 (3, datetime.date(2026, 8, 5), Decimal('26.97'), Decimal('10.71'), 30),
 (3, datetime.date(2026, 8, 6), Decimal('40.21'), Decimal('10.87'), 30),
 (3, datetime.date(2026, 8, 7), Decimal('9.67'), Decimal('11.09'), 30),
 (3, datetime.date(2026, 8, 8), Decimal('24.95'), Decimal('10.68'), 30),
 (3, datetime.date(2026, 8, 9), Decimal('37.86'), Decimal('10.86'), 30),
 (3, datetime.date(2026, 8, 10), Decimal('27.90'), Decimal('10.77'), 30),
 (3, datetime.date(2026, 8, 11), Decimal('8.39'), Decimal('11.24'), 30),
 (3, datetime.date(2026, 8, 12), Decimal('35.90'), Decimal('11.30'), 30),
 (3, datetime.date(2026, 8, 13), Decimal('53.55'), Decimal('12.41'), 30),
 (3, datetime.date(2026, 8, 14), Decimal('21.52'), Decimal('12.22'), 30),
 (3, datetime.date(2026, 8, 15), Decimal('23.46'), Decimal('10.45'), 30),
 (3, datetime.date(2026, 8, 16), Decimal('25.36'), Decimal('10.43'), 30),
 (3, datetime.date(2026, 8, 17), Decimal('43.73'), Decimal('10.80'), 30),
 (3, datetime.date(2026, 8, 18), Decimal('23.24'), Decimal('10.80'), 30),
 (3, datetime.date(2026, 8, 19), Decimal('22.74'), Decimal('10.67'), 30),
 (3, datetime.date(2026, 8, 20), Decimal('18.85'), Decimal('10.34'), 30),
 (3, datetime.date(2026, 8, 21), Decimal('35.36'), Decimal('10.50'), 30),
 (3, datetime.date(2026, 8, 22), Decimal('32.83'), Decimal('10.11'), 30),
 (3, datetime.date(2026, 8, 23), Decimal('30.31'), Decimal('9.97'), 30),
 (3, datetime.date(2026, 8, 24), Decimal('3.00'), Decimal('10.73'), 30),
 (3, datetime.date(2026, 8, 25), Decimal('20.70'), Decimal('10.75'), 30),
 (3, datetime.date(2026, 8, 26), Decimal('31.11'), Decimal('10.79'), 30),
 (3, datetime.date(2026, 8, 27), Decimal('39.34'), Decimal('11.04'), 30),
 (3, datetime.date(2026, 8, 28), Decimal('16.02'), Decimal('11.19'), 30),
 (3, datetime.date(2026, 8, 29), Decimal('27.79'), Decimal('11.18'), 30),
 (3, datetime.date(2026, 8, 30), Decimal('41.85'), Decimal('11.42'), 30),
 (3, datetime.date(2026, 8, 31), Decimal('44.88'), Decimal('11.88'), 30),
 (4, datetime.date(2026, 7, 1), Decimal('18.62'), None, 1),
 (4, datetime.date(2026, 7, 2), Decimal('19.55'), Decimal('0.66'), 2),
 (4, datetime.date(2026, 7, 3), Decimal('17.92'), Decimal('0.82'), 3),
 (4, datetime.date(2026, 7, 4), Decimal('19.11'), Decimal('0.70'), 4),
 (4, datetime.date(2026, 7, 5), Decimal('18.71'), Decimal('0.61'), 5),
 (4, datetime.date(2026, 7, 6), Decimal('19.15'), Decimal('0.56'), 6),
 (4, datetime.date(2026, 7, 7), Decimal('19.56'), Decimal('0.58'), 7),
 (4, datetime.date(2026, 7, 8), Decimal('18.52'), Decimal('0.56'), 8),
 (4, datetime.date(2026, 7, 9), Decimal('18.37'), Decimal('0.55'), 9),
 (4, datetime.date(2026, 7, 10), Decimal('18.00'), Decimal('0.58'), 10),
 (4, datetime.date(2026, 7, 11), Decimal('18.51'), Decimal('0.56'), 11),
 (4, datetime.date(2026, 7, 12), Decimal('19.07'), Decimal('0.54'), 12),
 (4, datetime.date(2026, 7, 13), Decimal('18.42'), Decimal('0.53'), 13),
 (4, datetime.date(2026, 7, 14), Decimal('18.17'), Decimal('0.53'), 14),
 (4, datetime.date(2026, 7, 15), Decimal('19.03'), Decimal('0.52'), 15),
 (4, datetime.date(2026, 7, 16), Decimal('20.38'), Decimal('0.65'), 16),
 (4, datetime.date(2026, 7, 17), Decimal('18.98'), Decimal('0.63'), 17),
 (4, datetime.date(2026, 7, 18), Decimal('19.09'), Decimal('0.61'), 18),
 (4, datetime.date(2026, 7, 19), Decimal('19.25'), Decimal('0.60'), 19),
 (4, datetime.date(2026, 7, 20), Decimal('21.00'), Decimal('0.76'), 20),
 (4, datetime.date(2026, 7, 21), Decimal('18.99'), Decimal('0.74'), 21),
 (4, datetime.date(2026, 7, 22), Decimal('20.04'), Decimal('0.76'), 22),
 (4, datetime.date(2026, 7, 23), Decimal('18.82'), Decimal('0.74'), 23),
 (4, datetime.date(2026, 7, 24), Decimal('18.36'), Decimal('0.74'), 24),
 (4, datetime.date(2026, 7, 25), Decimal('18.61'), Decimal('0.72'), 25),
 (4, datetime.date(2026, 7, 26), Decimal('18.91'), Decimal('0.71'), 26),
 (4, datetime.date(2026, 7, 27), Decimal('18.50'), Decimal('0.70'), 27),
 (4, datetime.date(2026, 7, 28), Decimal('20.41'), Decimal('0.74'), 28),
 (4, datetime.date(2026, 7, 29), Decimal('19.73'), Decimal('0.74'), 29),
 (4, datetime.date(2026, 7, 30), Decimal('20.54'), Decimal('0.78'), 30),
 (4, datetime.date(2026, 7, 31), Decimal('18.55'), Decimal('0.78'), 30),
 (4, datetime.date(2026, 8, 1), Decimal('18.99'), Decimal('0.77'), 30),
 (4, datetime.date(2026, 8, 2), Decimal('19.04'), Decimal('0.74'), 30),
 (4, datetime.date(2026, 8, 3), Decimal('21.92'), Decimal('0.91'), 30),
 (4, datetime.date(2026, 8, 4), Decimal('19.80'), Decimal('0.91'), 30),
 (4, datetime.date(2026, 8, 5), Decimal('19.09'), Decimal('0.91'), 30),
 (4, datetime.date(2026, 8, 6), Decimal('20.18'), Decimal('0.92'), 30),
 (4, datetime.date(2026, 8, 7), Decimal('19.16'), Decimal('0.91'), 30),
 (4, datetime.date(2026, 8, 8), Decimal('19.76'), Decimal('0.90'), 30),
 (4, datetime.date(2026, 8, 9), Decimal('18.60'), Decimal('0.88'), 30),
 (4, datetime.date(2026, 8, 10), Decimal('18.45'), Decimal('0.88'), 30),
 (4, datetime.date(2026, 8, 11), Decimal('19.99'), Decimal('0.89'), 30),
 (4, datetime.date(2026, 8, 12), Decimal('19.52'), Decimal('0.87'), 30),
 (4, datetime.date(2026, 8, 13), Decimal('18.96'), Decimal('0.84'), 30),
 (4, datetime.date(2026, 8, 14), Decimal('19.30'), Decimal('0.84'), 30),
 (4, datetime.date(2026, 8, 15), Decimal('18.54'), Decimal('0.83'), 30),
 (4, datetime.date(2026, 8, 16), Decimal('18.53'), Decimal('0.85'), 30),
 (4, datetime.date(2026, 8, 17), Decimal('19.34'), Decimal('0.84'), 30),
 (4, datetime.date(2026, 8, 18), Decimal('19.95'), Decimal('0.85'), 30),
 (4, datetime.date(2026, 8, 19), Decimal('19.85'), Decimal('0.80'), 30),
 (4, datetime.date(2026, 8, 20), Decimal('19.55'), Decimal('0.80'), 30),
 (4, datetime.date(2026, 8, 21), Decimal('19.04'), Decimal('0.79'), 30),
 (4, datetime.date(2026, 8, 22), Decimal('19.13'), Decimal('0.78'), 30),
 (4, datetime.date(2026, 8, 23), Decimal('18.67'), Decimal('0.77'), 30),
 (4, datetime.date(2026, 8, 24), Decimal('19.38'), Decimal('0.76'), 30),
 (4, datetime.date(2026, 8, 25), Decimal('18.71'), Decimal('0.77'), 30),
 (4, datetime.date(2026, 8, 26), Decimal('19.90'), Decimal('0.75'), 30),
 (4, datetime.date(2026, 8, 27), Decimal('19.85'), Decimal('0.73'), 30),
 (4, datetime.date(2026, 8, 28), Decimal('19.84'), Decimal('0.74'), 30),
 (4, datetime.date(2026, 8, 29), Decimal('19.06'), Decimal('0.71'), 30),
 (4, datetime.date(2026, 8, 30), Decimal('18.81'), Decimal('0.70'), 30),
 (4, datetime.date(2026, 8, 31), Decimal('18.98'), Decimal('0.70'), 30),
 (5, datetime.date(2026, 7, 1), None, None, 1),
 (5, datetime.date(2026, 7, 2), None, None, 2),
 (5, datetime.date(2026, 7, 3), None, None, 3),
 (5, datetime.date(2026, 7, 4), Decimal('37.89'), None, 4),
 (5, datetime.date(2026, 7, 5), None, None, 5),
 (5, datetime.date(2026, 7, 6), None, None, 6),
 (5, datetime.date(2026, 7, 7), None, None, 7),
 (5, datetime.date(2026, 7, 8), None, None, 8),
 (5, datetime.date(2026, 7, 9), None, None, 9),
 (5, datetime.date(2026, 7, 10), None, None, 10),
 (5, datetime.date(2026, 7, 11), None, None, 11),
 (5, datetime.date(2026, 7, 12), None, None, 12),
 (5, datetime.date(2026, 7, 13), None, None, 13),
 (5, datetime.date(2026, 7, 14), None, None, 14),
 (5, datetime.date(2026, 7, 15), None, None, 15),
 (5, datetime.date(2026, 7, 16), None, None, 16),
 (5, datetime.date(2026, 7, 17), None, None, 17),
 (5, datetime.date(2026, 7, 18), None, None, 18),
 (5, datetime.date(2026, 7, 19), None, None, 19),
 (5, datetime.date(2026, 7, 20), None, None, 20),
 (5, datetime.date(2026, 7, 21), None, None, 21),
 (5, datetime.date(2026, 7, 22), None, None, 22),
 (5, datetime.date(2026, 7, 23), None, None, 23),
 (5, datetime.date(2026, 7, 24), None, None, 24),
 (5, datetime.date(2026, 7, 25), None, None, 25),
 (5, datetime.date(2026, 7, 26), Decimal('61.10'), Decimal('16.41'), 26),
 (5, datetime.date(2026, 7, 27), None, Decimal('16.41'), 27),
 (5, datetime.date(2026, 7, 28), None, Decimal('16.41'), 28),
 (5, datetime.date(2026, 7, 29), None, Decimal('16.41'), 29),
 (5, datetime.date(2026, 7, 30), None, Decimal('16.41'), 30),
 (5, datetime.date(2026, 7, 31), None, Decimal('16.41'), 30),
 (5, datetime.date(2026, 8, 1), None, Decimal('16.41'), 30),
 (5, datetime.date(2026, 8, 2), None, Decimal('16.41'), 30),
 (5, datetime.date(2026, 8, 3), Decimal('68.62'), Decimal('5.32'), 30),
 (5, datetime.date(2026, 8, 4), None, Decimal('5.32'), 30),
 (5, datetime.date(2026, 8, 5), None, Decimal('5.32'), 30),
 (5, datetime.date(2026, 8, 6), None, Decimal('5.32'), 30),
 (5, datetime.date(2026, 8, 7), Decimal('67.62'), Decimal('4.08'), 30),
 (5, datetime.date(2026, 8, 8), None, Decimal('4.08'), 30),
 (5, datetime.date(2026, 8, 9), Decimal('37.99'), Decimal('14.29'), 30),
 (5, datetime.date(2026, 8, 10), None, Decimal('14.29'), 30),
 (5, datetime.date(2026, 8, 11), None, Decimal('14.29'), 30),
 (5, datetime.date(2026, 8, 12), None, Decimal('14.29'), 30),
 (5, datetime.date(2026, 8, 13), None, Decimal('14.29'), 30),
 (5, datetime.date(2026, 8, 14), None, Decimal('14.29'), 30),

### Feature 4. Expanding cumulative trips

In [22]:
%%sql
SELECT
    pickup_zone_id,
    ts_day,
    trip_count,
    SUM(trip_count) OVER we AS cumulative_trips,
    (AVG(trip_count) OVER we)::NUMERIC(8, 2) AS expanding_avg_trips
FROM t7_hw_taxi_daily
WINDOW we AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
16182 rows affected.

[(1, datetime.date(2026, 7, 1), 2, 2, Decimal('2.00')),
 (1, datetime.date(2026, 7, 2), 2, 4, Decimal('2.00')),
 (1, datetime.date(2026, 7, 3), 1, 5, Decimal('1.67')),
 (1, datetime.date(2026, 7, 4), 3, 8, Decimal('2.00')),
 (1, datetime.date(2026, 7, 5), 8, 16, Decimal('3.20')),
 (1, datetime.date(2026, 7, 6), 2, 18, Decimal('3.00')),
 (1, datetime.date(2026, 7, 7), 3, 21, Decimal('3.00')),
 (1, datetime.date(2026, 7, 8), 2, 23, Decimal('2.88')),
 (1, datetime.date(2026, 7, 9), 3, 26, Decimal('2.89')),
 (1, datetime.date(2026, 7, 10), 1, 27, Decimal('2.70')),
 (1, datetime.date(2026, 7, 11), 3, 30, Decimal('2.73')),
 (1, datetime.date(2026, 7, 12), 10, 40, Decimal('3.33')),
 (1, datetime.date(2026, 7, 13), 3, 43, Decimal('3.31')),
 (1, datetime.date(2026, 7, 14), 1, 44, Decimal('3.14')),
 (1, datetime.date(2026, 7, 15), 2, 46, Decimal('3.07')),
 (1, datetime.date(2026, 7, 16), 1, 47, Decimal('2.94')),
 (1, datetime.date(2026, 7, 17), 3, 50, Decimal('2.94')),
 (1, datetime.date(2026, 7, 18), 3, 53, Decimal('2.94')),
 (1, datetime.date(2026, 7, 19), 6, 59, Decimal('3.11')),
 (1, datetime.date(2026, 7, 20), 9, 68, Decimal('3.40')),
 (1, datetime.date(2026, 7, 21), 3, 71, Decimal('3.38')),
 (1, datetime.date(2026, 7, 22), 5, 76, Decimal('3.45')),
 (1, datetime.date(2026, 7, 23), 3, 79, Decimal('3.43')),
 (1, datetime.date(2026, 7, 24), 3, 82, Decimal('3.42')),
 (1, datetime.date(2026, 7, 25), 4, 86, Decimal('3.44')),
 (1, datetime.date(2026, 7, 26), 8, 94, Decimal('3.62')),
 (1, datetime.date(2026, 7, 27), 1, 95, Decimal('3.52')),
 (1, datetime.date(2026, 7, 28), 2, 97, Decimal('3.46')),
 (1, datetime.date(2026, 7, 29), 7, 104, Decimal('3.59')),
 (1, datetime.date(2026, 7, 30), 4, 108, Decimal('3.60')),
 (1, datetime.date(2026, 7, 31), 4, 112, Decimal('3.61')),
 (1, datetime.date(2026, 8, 1), 4, 116, Decimal('3.63')),
 (1, datetime.date(2026, 8, 2), 4, 120, Decimal('3.64')),
 (1, datetime.date(2026, 8, 3), 1, 121, Decimal('3.56')),
 (1, datetime.date(2026, 8, 4), 3, 124, Decimal('3.54')),
 (1, datetime.date(2026, 8, 5), 1, 125, Decimal('3.47')),
 (1, datetime.date(2026, 8, 6), 6, 131, Decimal('3.54')),
 (1, datetime.date(2026, 8, 7), 5, 136, Decimal('3.58')),
 (1, datetime.date(2026, 8, 8), 4, 140, Decimal('3.59')),
 (1, datetime.date(2026, 8, 9), 11, 151, Decimal('3.78')),
 (1, datetime.date(2026, 8, 10), 6, 157, Decimal('3.83')),
 (1, datetime.date(2026, 8, 11), 2, 159, Decimal('3.79')),
 (1, datetime.date(2026, 8, 12), 6, 165, Decimal('3.84')),
 (1, datetime.date(2026, 8, 13), 6, 171, Decimal('3.89')),
 (1, datetime.date(2026, 8, 14), 3, 174, Decimal('3.87')),
 (1, datetime.date(2026, 8, 15), 3, 177, Decimal('3.85')),
 (1, datetime.date(2026, 8, 16), 8, 185, Decimal('3.94')),
 (1, datetime.date(2026, 8, 17), 4, 189, Decimal('3.94')),
 (1, datetime.date(2026, 8, 18), 1, 190, Decimal('3.88')),
 (1, datetime.date(2026, 8, 19), 4, 194, Decimal('3.88')),
 (1, datetime.date(2026, 8, 20), 5, 199, Decimal('3.90')),
 (1, datetime.date(2026, 8, 21), 1, 200, Decimal('3.85')),
 (1, datetime.date(2026, 8, 22), 2, 202, Decimal('3.81')),
 (1, datetime.date(2026, 8, 23), 2, 204, Decimal('3.78')),
 (1, datetime.date(2026, 8, 24), 3, 207, Decimal('3.76')),
 (1, datetime.date(2026, 8, 25), 2, 209, Decimal('3.73')),
 (1, datetime.date(2026, 8, 26), 7, 216, Decimal('3.79')),
 (1, datetime.date(2026, 8, 27), 2, 218, Decimal('3.76')),
 (1, datetime.date(2026, 8, 28), 3, 221, Decimal('3.75')),
 (1, datetime.date(2026, 8, 29), 2, 223, Decimal('3.72')),
 (1, datetime.date(2026, 8, 30), 3, 226, Decimal('3.70')),
 (1, datetime.date(2026, 8, 31), 5, 231, Decimal('3.73')),
 (2, datetime.date(2026, 7, 1), 0, 0, Decimal('0.00')),
 (2, datetime.date(2026, 7, 2), 0, 0, Decimal('0.00')),
 (2, datetime.date(2026, 7, 3), 0, 0, Decimal('0.00')),
 (2, datetime.date(2026, 7, 4), 1, 1, Decimal('0.25')),
 (2, datetime.date(2026, 7, 5), 0, 1, Decimal('0.20')),
 (2, datetime.date(2026, 7, 6), 0, 1, Decimal('0.17')),
 (2, datetime.date(2026, 7, 7), 0, 1, Decimal('0.14')),
 (2, datetime.date(2026, 7, 8), 1, 2, Decimal('0.25')),
 (2, datetime.date(2026, 7, 9), 0, 2, Decimal('0.22')),
 (2, datetime.date(2026, 7, 10), 0, 2, Decimal('0.20')),
 (2, datetime.date(2026, 7, 11), 2, 4, Decimal('0.36')),
 (2, datetime.date(2026, 7, 12), 0, 4, Decimal('0.33')),
 (2, datetime.date(2026, 7, 13), 0, 4, Decimal('0.31')),
 (2, datetime.date(2026, 7, 14), 0, 4, Decimal('0.29')),
 (2, datetime.date(2026, 7, 15), 0, 4, Decimal('0.27')),
 (2, datetime.date(2026, 7, 16), 1, 5, Decimal('0.31')),
 (2, datetime.date(2026, 7, 17), 0, 5, Decimal('0.29')),
 (2, datetime.date(2026, 7, 18), 1, 6, Decimal('0.33')),
 (2, datetime.date(2026, 7, 19), 0, 6, Decimal('0.32')),
 (2, datetime.date(2026, 7, 20), 0, 6, Decimal('0.30')),
 (2, datetime.date(2026, 7, 21), 1, 7, Decimal('0.33')),
 (2, datetime.date(2026, 7, 22), 0, 7, Decimal('0.32')),
 (2, datetime.date(2026, 7, 23), 1, 8, Decimal('0.35')),
 (2, datetime.date(2026, 7, 24), 0, 8, Decimal('0.33')),
 (2, datetime.date(2026, 7, 25), 0, 8, Decimal('0.32')),
 (2, datetime.date(2026, 7, 26), 0, 8, Decimal('0.31')),
 (2, datetime.date(2026, 7, 27), 0, 8, Decimal('0.30')),
 (2, datetime.date(2026, 7, 28), 0, 8, Decimal('0.29')),
 (2, datetime.date(2026, 7, 29), 2, 10, Decimal('0.34')),
 (2, datetime.date(2026, 7, 30), 1, 11, Decimal('0.37')),
 (2, datetime.date(2026, 7, 31), 0, 11, Decimal('0.35')),
 (2, datetime.date(2026, 8, 1), 0, 11, Decimal('0.34')),
 (2, datetime.date(2026, 8, 2), 0, 11, Decimal('0.33')),
 (2, datetime.date(2026, 8, 3), 0, 11, Decimal('0.32')),
 (2, datetime.date(2026, 8, 4), 0, 11, Decimal('0.31')),
 (2, datetime.date(2026, 8, 5), 1, 12, Decimal('0.33')),
 (2, datetime.date(2026, 8, 6), 0, 12, Decimal('0.32')),
 (2, datetime.date(2026, 8, 7), 0, 12, Decimal('0.32')),
 (2, datetime.date(2026, 8, 8), 0, 12, Decimal('0.31')),
 (2, datetime.date(2026, 8, 9), 0, 12, Decimal('0.30')),
 (2, datetime.date(2026, 8, 10), 0, 12, Decimal('0.29')),
 (2, datetime.date(2026, 8, 11), 0, 12, Decimal('0.29')),
 (2, datetime.date(2026, 8, 12), 1, 13, Decimal('0.30')),
 (2, datetime.date(2026, 8, 13), 0, 13, Decimal('0.30')),
 (2, datetime.date(2026, 8, 14), 0, 13, Decimal('0.29')),
 (2, datetime.date(2026, 8, 15), 0, 13, Decimal('0.28')),
 (2, datetime.date(2026, 8, 16), 0, 13, Decimal('0.28')),
 (2, datetime.date(2026, 8, 17), 0, 13, Decimal('0.27')),
 (2, datetime.date(2026, 8, 18), 1, 14, Decimal('0.29')),
 (2, datetime.date(2026, 8, 19), 0, 14, Decimal('0.28')),
 (2, datetime.date(2026, 8, 20), 0, 14, Decimal('0.27')),
 (2, datetime.date(2026, 8, 21), 1, 15, Decimal('0.29')),
 (2, datetime.date(2026, 8, 22), 1, 16, Decimal('0.30')),
 (2, datetime.date(2026, 8, 23), 0, 16, Decimal('0.30')),
 (2, datetime.date(2026, 8, 24), 1, 17, Decimal('0.31')),
 (2, datetime.date(2026, 8, 25), 0, 17, Decimal('0.30')),
 (2, datetime.date(2026, 8, 26), 0, 17, Decimal('0.30')),
 (2, datetime.date(2026, 8, 27), 0, 17, Decimal('0.29')),
 (2, datetime.date(2026, 8, 28), 0, 17, Decimal('0.29')),
 (2, datetime.date(2026, 8, 29), 0, 17, Decimal('0.28')),
 (2, datetime.date(2026, 8, 30), 1, 18, Decimal('0.30')),
 (2, datetime.date(2026, 8, 31), 0, 18, Decimal('0.29')),
 (3, datetime.date(2026, 7, 1), 1, 1, Decimal('1.00')),
 (3, datetime.date(2026, 7, 2), 0, 1, Decimal('0.50')),
 (3, datetime.date(2026, 7, 3), 0, 1, Decimal('0.33')),
 (3, datetime.date(2026, 7, 4), 6, 7, Decimal('1.75')),
 (3, datetime.date(2026, 7, 5), 4, 11, Decimal('2.20')),
 (3, datetime.date(2026, 7, 6), 1, 12, Decimal('2.00')),
 (3, datetime.date(2026, 7, 7), 1, 13, Decimal('1.86')),
 (3, datetime.date(2026, 7, 8), 0, 13, Decimal('1.63')),
 (3, datetime.date(2026, 7, 9), 2, 15, Decimal('1.67')),
 (3, datetime.date(2026, 7, 10), 5, 20, Decimal('2.00')),
 (3, datetime.date(2026, 7, 11), 4, 24, Decimal('2.18')),
 (3, datetime.date(2026, 7, 12), 7, 31, Decimal('2.58')),
 (3, datetime.date(2026, 7, 13), 5, 36, Decimal('2.77')),
 (3, datetime.date(2026, 7, 14), 4, 40, Decimal('2.86')),
 (3, datetime.date(2026, 7, 15), 2, 42, Decimal('2.80')),
 (3, datetime.date(2026, 7, 16), 1, 43, Decimal('2.69')),
 (3, datetime.date(2026, 7, 17), 5, 48, Decimal('2.82')),
 (3, datetime.date(2026, 7, 18), 8, 56, Decimal('3.11')),
 (3, datetime.date(2026, 7, 19), 12, 68, Decimal('3.58')),
 (3, datetime.date(2026, 7, 20), 3, 71, Decimal('3.55')),
 (3, datetime.date(2026, 7, 21), 5, 76, Decimal('3.62')),
 (3, datetime.date(2026, 7, 22), 7, 83, Decimal('3.77')),
 (3, datetime.date(2026, 7, 23), 2, 85, Decimal('3.70')),
 (3, datetime.date(2026, 7, 24), 4, 89, Decimal('3.71')),
 (3, datetime.date(2026, 7, 25), 5, 94, Decimal('3.76')),
 (3, datetime.date(2026, 7, 26), 8, 102, Decimal('3.92')),
 (3, datetime.date(2026, 7, 27), 2, 104, Decimal('3.85')),
 (3, datetime.date(2026, 7, 28), 2, 106, Decimal('3.79')),
 (3, datetime.date(2026, 7, 29), 4, 110, Decimal('3.79')),
 (3, datetime.date(2026, 7, 30), 3, 113, Decimal('3.77')),
 (3, datetime.date(2026, 7, 31), 6, 119, Decimal('3.84')),
 (3, datetime.date(2026, 8, 1), 6, 125, Decimal('3.91')),
 (3, datetime.date(2026, 8, 2), 6, 131, Decimal('3.97')),
 (3, datetime.date(2026, 8, 3), 6, 137, Decimal('4.03')),
 (3, datetime.date(2026, 8, 4), 0, 137, Decimal('3.91')),
 (3, datetime.date(2026, 8, 5), 1, 138, Decimal('3.83')),
 (3, datetime.date(2026, 8, 6), 3, 141, Decimal('3.81')),
 (3, datetime.date(2026, 8, 7), 6, 147, Decimal('3.87')),
 (3, datetime.date(2026, 8, 8), 3, 150, Decimal('3.85')),
 (3, datetime.date(2026, 8, 9), 3, 153, Decimal('3.83')),
 (3, datetime.date(2026, 8, 10), 3, 156, Decimal('3.80')),
 (3, datetime.date(2026, 8, 11), 1, 157, Decimal('3.74')),
 (3, datetime.date(2026, 8, 12), 5, 162, Decimal('3.77')),
 (3, datetime.date(2026, 8, 13), 5, 167, Decimal('3.80')),
 (3, datetime.date(2026, 8, 14), 5, 172, Decimal('3.82')),
 (3, datetime.date(2026, 8, 15), 4, 176, Decimal('3.83')),
 (3, datetime.date(2026, 8, 16), 5, 181, Decimal('3.85')),
 (3, datetime.date(2026, 8, 17), 3, 184, Decimal('3.83')),
 (3, datetime.date(2026, 8, 18), 3, 187, Decimal('3.82')),
 (3, datetime.date(2026, 8, 19), 4, 191, Decimal('3.82')),
 (3, datetime.date(2026, 8, 20), 3, 194, Decimal('3.80')),
 (3, datetime.date(2026, 8, 21), 4, 198, Decimal('3.81')),
 (3, datetime.date(2026, 8, 22), 3, 201, Decimal('3.79')),
 (3, datetime.date(2026, 8, 23), 5, 206, Decimal('3.81')),
 (3, datetime.date(2026, 8, 24), 1, 207, Decimal('3.76')),
 (3, datetime.date(2026, 8, 25), 2, 209, Decimal('3.73')),
 (3, datetime.date(2026, 8, 26), 4, 213, Decimal('3.74')),
 (3, datetime.date(2026, 8, 27), 1, 214, Decimal('3.69')),
 (3, datetime.date(2026, 8, 28), 5, 219, Decimal('3.71')),
 (3, datetime.date(2026, 8, 29), 6, 225, Decimal('3.75')),
 (3, datetime.date(2026, 8, 30), 5, 230, Decimal('3.77')),
 (3, datetime.date(2026, 8, 31), 4, 234, Decimal('3.77')),
 (4, datetime.date(2026, 7, 1), 372, 372, Decimal('372.00')),
 (4, datetime.date(2026, 7, 2), 462, 834, Decimal('417.00')),
 (4, datetime.date(2026, 7, 3), 454, 1288, Decimal('429.33')),
 (4, datetime.date(2026, 7, 4), 537, 1825, Decimal('456.25')),
 (4, datetime.date(2026, 7, 5), 369, 2194, Decimal('438.80')),
 (4, datetime.date(2026, 7, 6), 231, 2425, Decimal('404.17')),
 (4, datetime.date(2026, 7, 7), 246, 2671, Decimal('381.57')),
 (4, datetime.date(2026, 7, 8), 323, 2994, Decimal('374.25')),
 (4, datetime.date(2026, 7, 9), 360, 3354, Decimal('372.67')),
 (4, datetime.date(2026, 7, 10), 521, 3875, Decimal('387.50')),
 (4, datetime.date(2026, 7, 11), 837, 4712, Decimal('428.36')),
 (4, datetime.date(2026, 7, 12), 752, 5464, Decimal('455.33')),
 (4, datetime.date(2026, 7, 13), 257, 5721, Decimal('440.08')),
 (4, datetime.date(2026, 7, 14), 387, 6108, Decimal('436.29')),
 (4, datetime.date(2026, 7, 15), 377, 6485, Decimal('432.33')),
 (4, datetime.date(2026, 7, 16), 424, 6909, Decimal('431.81')),
 (4, datetime.date(2026, 7, 17), 623, 7532, Decimal('443.06')),
 (4, datetime.date(2026, 7, 18), 967, 8499, Decimal('472.17')),
 (4, datetime.date(2026, 7, 19), 871, 9370, Decimal('493.16')),
 (4, datetime.date(2026, 7, 20), 292, 9662, Decimal('483.10')),
 (4, datetime.date(2026, 7, 21), 315, 9977, Decimal('475.10')),
 (4, datetime.date(2026, 7, 22), 366, 10343, Decimal('470.14')),
 (4, datetime.date(2026, 7, 23), 447, 10790, Decimal('469.13')),
 (4, datetime.date(2026, 7, 24), 555, 11345, Decimal('472.71')),
 (4, datetime.date(2026, 7, 25), 902, 12247, Decimal('489.88')),
 (4, datetime.date(2026, 7, 26), 724, 12971, Decimal('498.88')),
 (4, datetime.date(2026, 7, 27), 276, 13247, Decimal('490.63')),
 (4, datetime.date(2026, 7, 28), 338, 13585, Decimal('485.18')),
 (4, datetime.date(2026, 7, 29), 399, 13984, Decimal('482.21')),
 (4, datetime.date(2026, 7, 30), 393, 14377, Decimal('479.23')),
 (4, datetime.date(2026, 7, 31), 606, 14983, Decimal('483.32')),
 (4, datetime.date(2026, 8, 1), 881, 15864, Decimal('495.75')),
 (4, datetime.date(2026, 8, 2), 682, 16546, Decimal('501.39')),
 (4, datetime.date(2026, 8, 3), 282, 16828, Decimal('494.94')),
 (4, datetime.date(2026, 8, 4), 371, 17199, Decimal('491.40')),
 (4, datetime.date(2026, 8, 5), 391, 17590, Decimal('488.61')),
 (4, datetime.date(2026, 8, 6), 454, 18044, Decimal('487.68')),
 (4, datetime.date(2026, 8, 7), 639, 18683, Decimal('491.66')),
 (4, datetime.date(2026, 8, 8), 904, 19587, Decimal('502.23')),
 (4, datetime.date(2026, 8, 9), 684, 20271, Decimal('506.78')),
 (4, datetime.date(2026, 8, 10), 277, 20548, Decimal('501.17')),
 (4, datetime.date(2026, 8, 11), 353, 20901, Decimal('497.64')),
 (4, datetime.date(2026, 8, 12), 392, 21293, Decimal('495.19')),
 (4, datetime.date(2026, 8, 13), 450, 21743, Decimal('494.16')),
 (4, datetime.date(2026, 8, 14), 575, 22318, Decimal('495.96')),
 (4, datetime.date(2026, 8, 15), 852, 23170, Decimal('503.70')),
 (4, datetime.date(2026, 8, 16), 709, 23879, Decimal('508.06')),
 (4, datetime.date(2026, 8, 17), 306, 24185, Decimal('503.85')),
 (4, datetime.date(2026, 8, 18), 350, 24535, Decimal('500.71')),
 (4, datetime.date(2026, 8, 19), 366, 24901, Decimal('498.02')),
 (4, datetime.date(2026, 8, 20), 478, 25379, Decimal('497.63')),
 (4, datetime.date(2026, 8, 21), 504, 25883, Decimal('497.75')),
 (4, datetime.date(2026, 8, 22), 877, 26760, Decimal('504.91')),
 (4, datetime.date(2026, 8, 23), 732, 27492, Decimal('509.11')),
 (4, datetime.date(2026, 8, 24), 259, 27751, Decimal('504.56')),
 (4, datetime.date(2026, 8, 25), 325, 28076, Decimal('501.36')),
 (4, datetime.date(2026, 8, 26), 372, 28448, Decimal('499.09')),
 (4, datetime.date(2026, 8, 27), 411, 28859, Decimal('497.57')),
 (4, datetime.date(2026, 8, 28), 570, 29429, Decimal('498.80')),
 (4, datetime.date(2026, 8, 29), 880, 30309, Decimal('505.15')),
 (4, datetime.date(2026, 8, 30), 734, 31043, Decimal('508.90')),
 (4, datetime.date(2026, 8, 31), 313, 31356, Decimal('505.74')),
 (5, datetime.date(2026, 7, 1), 0, 0, Decimal('0.00')),
 (5, datetime.date(2026, 7, 2), 0, 0, Decimal('0.00')),
 (5, datetime.date(2026, 7, 3), 0, 0, Decimal('0.00')),
 (5, datetime.date(2026, 7, 4), 1, 1, Decimal('0.25')),
 (5, datetime.date(2026, 7, 5), 0, 1, Decimal('0.20')),
 (5, datetime.date(2026, 7, 6), 0, 1, Decimal('0.17')),
 (5, datetime.date(2026, 7, 7), 0, 1, Decimal('0.14')),
 (5, datetime.date(2026, 7, 8), 0, 1, Decimal('0.13')),
 (5, datetime.date(2026, 7, 9), 0, 1, Decimal('0.11')),
 (5, datetime.date(2026, 7, 10), 0, 1, Decimal('0.10')),
 (5, datetime.date(2026, 7, 11), 0, 1, Decimal('0.09')),
 (5, datetime.date(2026, 7, 12), 0, 1, Decimal('0.08')),
 (5, datetime.date(2026, 7, 13), 0, 1, Decimal('0.08')),
 (5, datetime.date(2026, 7, 14), 0, 1, Decimal('0.07')),
 (5, datetime.date(2026, 7, 15), 0, 1, Decimal('0.07')),
 (5, datetime.date(2026, 7, 16), 0, 1, Decimal('0.06')),
 (5, datetime.date(2026, 7, 17), 0, 1, Decimal('0.06')),
 (5, datetime.date(2026, 7, 18), 0, 1, Decimal('0.06')),
 (5, datetime.date(2026, 7, 19), 0, 1, Decimal('0.05')),
 (5, datetime.date(2026, 7, 20), 0, 1, Decimal('0.05')),
 (5, datetime.date(2026, 7, 21), 0, 1, Decimal('0.05')),
 (5, datetime.date(2026, 7, 22), 0, 1, Decimal('0.05')),
 (5, datetime.date(2026, 7, 23), 0, 1, Decimal('0.04')),
 (5, datetime.date(2026, 7, 24), 0, 1, Decimal('0.04')),
 (5, datetime.date(2026, 7, 25), 0, 1, Decimal('0.04')),
 (5, datetime.date(2026, 7, 26), 1, 2, Decimal('0.08')),
 (5, datetime.date(2026, 7, 27), 0, 2, Decimal('0.07')),
 (5, datetime.date(2026, 7, 28), 0, 2, Decimal('0.07')),
 (5, datetime.date(2026, 7, 29), 0, 2, Decimal('0.07')),
 (5, datetime.date(2026, 7, 30), 0, 2, Decimal('0.07')),
 (5, datetime.date(2026, 7, 31), 0, 2, Decimal('0.06')),
 (5, datetime.date(2026, 8, 1), 0, 2, Decimal('0.06')),
 (5, datetime.date(2026, 8, 2), 0, 2, Decimal('0.06')),
 (5, datetime.date(2026, 8, 3), 2, 4, Decimal('0.12')),
 (5, datetime.date(2026, 8, 4), 0, 4, Decimal('0.11')),
 (5, datetime.date(2026, 8, 5), 0, 4, Decimal('0.11')),
 (5, datetime.date(2026, 8, 6), 0, 4, Decimal('0.11')),
 (5, datetime.date(2026, 8, 7), 1, 5, Decimal('0.13')),
 (5, datetime.date(2026, 8, 8), 0, 5, Decimal('0.13')),
 (5, datetime.date(2026, 8, 9), 1, 6, Decimal('0.15')),
 (5, datetime.date(2026, 8, 10), 0, 6, Decimal('0.15')),
 (5, datetime.date(2026, 8, 11), 0, 6, Decimal('0.14')),
 (5, datetime.date(2026, 8, 12), 0, 6, Decimal('0.14')),
 (5, datetime.date(2026, 8, 13), 0, 6, Decimal('0.14')),
 (5, datetime.date(2026, 8, 14), 0, 6, Decimal('0.13')),
 (5, datetime.date(2026, 8, 15), 0, 6, Decimal('0.13')),
 (5, datetime.date(2026, 8, 16), 0, 6, Decimal('0.13')),
 (5, datetime.date(2026, 8, 17), 0, 6, Decimal('0.13')),
 (5, datetime.date(2026, 8, 18), 0, 6, Decimal('0.12')),
 (5, datetime.date(2026, 8, 19), 0, 6, Decimal('0.12')),
 (5, datetime.date(2026, 8, 20), 2, 8, Decimal('0.16')),
 (5, datetime.date(2026, 8, 21), 0, 8, Decimal('0.15')),
 (5, datetime.date(2026, 8, 22), 0, 8, Decimal('0.15')),
 (5, datetime.date(2026, 8, 23), 0, 8, Decimal('0.15')),
 (5, datetime.date(2026, 8, 24), 0, 8, Decimal('0.15')),
 (5, datetime.date(2026, 8, 25), 0, 8, Decimal('0.14')),
 (5, datetime.date(2026, 8, 26), 0, 8, Decimal('0.14')),
 (5, datetime.date(2026, 8, 27), 0, 8, Decimal('0.14')),
 (5, datetime.date(2026, 8, 28), 0, 8, Decimal('0.14')),
 (5, datetime.date(2026, 8, 29), 0, 8, Decimal('0.13')),
 (5, datetime.date(2026, 8, 30), 0, 8, Decimal('0.13')),
 (5, datetime.date(2026, 8, 31), 0, 8, Decimal('0.13')),
 (6, datetime.date(2026, 7, 1), 2, 2, Decimal('2.00')),
 (6, datetime.date(2026, 7, 2), 2, 4, Decimal('2.00')),
 (6, datetime.date(2026, 7, 3), 0, 4, Decimal('1.33')),
 (6, datetime.date(2026, 7, 4), 4, 8, Decimal('2.00')),
 (6, datetime.date(2026, 7, 5), 3, 11, Decimal('2.20')),
 (6, datetime.date(2026, 7, 6), 2, 13, Decimal('2.17')),
 (6, datetime.date(2026, 7, 7), 1, 14, Decimal('2.00')),
 (6, datetime.date(2026, 7, 8), 1, 15, Decimal('1.88')),
 (6, datetime.date(2026, 7, 9), 2, 17, Decimal('1.89')),
 (6, datetime.date(2026, 7, 10), 4, 21, Decimal('2.10')),
 (6, datetime.date(2026, 7, 11), 2, 23, Decimal('2.09')),
 (6, datetime.date(2026, 7, 12), 1, 24, Decimal('2.00')),
 (6, datetime.date(2026, 7, 13), 2, 26, Decimal('2.00')),
 (6, datetime.date(2026, 7, 14), 1, 27, Decimal('1.93')),
 (6, datetime.date(2026, 7, 15), 1, 28, Decimal('1.87')),
 (6, datetime.date(2026, 7, 16), 2, 30, Decimal('1.88')),
 (6, datetime.date(2026, 7, 17), 1, 31, Decimal('1.82')),
 (6, datetime.date(2026, 7, 18), 3, 34, Decimal('1.89')),
 (6, datetime.date(2026, 7, 19), 3, 37, Decimal('1.95')),
 (6, datetime.date(2026, 7, 20), 2, 39, Decimal('1.95')),
 (6, datetime.date(2026, 7, 21), 1, 40, Decimal('1.90')),
 (6, datetime.date(2026, 7, 22), 2, 42, Decimal('1.91')),
 (6, datetime.date(2026, 7, 23), 1, 43, Decimal('1.87')),
 (6, datetime.date(2026, 7, 24), 2, 45, Decimal('1.88')),
 (6, datetime.date(2026, 7, 25), 2, 47, Decimal('1.88')),
 (6, datetime.date(2026, 7, 26), 2, 49, Decimal('1.88')),
 (6, datetime.date(2026, 7, 27), 1, 50, Decimal('1.85')),
 (6, datetime.date(2026, 7, 28), 3, 53, Decimal('1.89')),
 (6, datetime.date(2026, 7, 29), 2, 55, Decimal('1.90')),

### `ROWS` vs `RANGE`: демонстрація off-by-one на ряді з пропусками

Штучно видаляємо 2 дні (05.07–06.07) для найактивнішої зони. `ROWS 6 PRECEDING` все одно бере 7 *рядків* і "дотягується" у минуле на 9 календарних днів; `RANGE INTERVAL '6 days'` чесно бере тільки дні з `[t-6, t]`.

In [23]:
%%sql
WITH top_zone AS (
    SELECT pickup_zone_id
    FROM t7_hw_taxi_daily
    GROUP BY pickup_zone_id
    ORDER BY SUM(trip_count) DESC, pickup_zone_id
    LIMIT 1
),
gappy AS (
    SELECT d.*
    FROM t7_hw_taxi_daily d
    JOIN top_zone USING (pickup_zone_id)
    WHERE d.ts_day NOT IN (DATE '2026-07-05', DATE '2026-07-06')
),
w AS (
    SELECT
        pickup_zone_id,
        ts_day,
        COUNT(*)    OVER w_rows  AS rows_frame_n,
        MIN(ts_day) OVER w_rows  AS rows_frame_start,
        COUNT(*)    OVER w_range AS range_frame_n,
        MIN(ts_day) OVER w_range AS range_frame_start
    FROM gappy
    WINDOW
        w_rows  AS (
            PARTITION BY pickup_zone_id ORDER BY ts_day
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ),
        w_range AS (
            PARTITION BY pickup_zone_id ORDER BY ts_day::TIMESTAMP
            RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW
        )
)
SELECT *
FROM w
WHERE ts_day BETWEEN DATE '2026-07-07' AND DATE '2026-07-13'
ORDER BY ts_day;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
7 rows affected.

[(132, datetime.date(2026, 7, 7), 5, datetime.date(2026, 7, 1), 5, datetime.date(2026, 7, 1)),
 (132, datetime.date(2026, 7, 8), 6, datetime.date(2026, 7, 1), 5, datetime.date(2026, 7, 2)),
 (132, datetime.date(2026, 7, 9), 7, datetime.date(2026, 7, 1), 5, datetime.date(2026, 7, 3)),
 (132, datetime.date(2026, 7, 10), 7, datetime.date(2026, 7, 2), 5, datetime.date(2026, 7, 4)),
 (132, datetime.date(2026, 7, 11), 7, datetime.date(2026, 7, 3), 5, datetime.date(2026, 7, 7)),
 (132, datetime.date(2026, 7, 12), 7, datetime.date(2026, 7, 4), 6, datetime.date(2026, 7, 7)),
 (132, datetime.date(2026, 7, 13), 7, datetime.date(2026, 7, 7), 7, datetime.date(2026, 7, 7))]

### Combined feature view `v_t7_hw_taxi_features`

Додатково $-$ ML-target `target_trips_next_1d` (`LEAD`). Усі ознаки використовують лише дані `≤ t`, а target $-$ `t+1`, тож у одному рядку немає data leakage. Рядки без повної 30-денної історії відфільтровані (`trips_lag_30d IS NOT NULL`).

In [27]:
%%sql
DROP VIEW IF EXISTS v_t7_hw_taxi_features;

CREATE VIEW v_t7_hw_taxi_features AS
WITH features_basic AS (
    SELECT
        pickup_zone_id,
        ts_day,
        trip_count,
        avg_fare,
        total_distance,

        LAG(trip_count, 1)  OVER w_pid AS trips_lag_1d,
        LAG(trip_count, 7)  OVER w_pid AS trips_lag_7d,
        LAG(trip_count, 30) OVER w_pid AS trips_lag_30d,

        (AVG(avg_fare) OVER w7)::NUMERIC(8, 2) AS rolling_avg_fare_7d,
        (
            STDDEV_SAMP(avg_fare) OVER w30
        )::NUMERIC(8, 2) AS rolling_std_fare_30d,

        SUM(trip_count) OVER we AS cumulative_trips,
        (AVG(trip_count) OVER we)::NUMERIC(8, 2) AS expanding_avg_trips,

        LEAD(trip_count, 1) OVER w_pid AS target_trips_next_1d
    FROM t7_hw_taxi_daily
    WINDOW
        w_pid AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day
        ),
        w7 AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day::TIMESTAMP
            RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW
        ),
        w30 AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day::TIMESTAMP
            RANGE BETWEEN INTERVAL '29 days' PRECEDING AND CURRENT ROW
        ),
        we AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        )
)
SELECT *
FROM features_basic
WHERE trips_lag_30d IS NOT NULL;

SELECT *
FROM v_t7_hw_taxi_features
ORDER BY pickup_zone_id, ts_day;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
Done.
Done.
8352 rows affected.

[(1, datetime.date(2026, 7, 31), 4, Decimal('118.75'), Decimal('0.42'), 4, 3, 2, Decimal('108.97'), Decimal('22.82'), 112, Decimal('3.61'), 4),
 (1, datetime.date(2026, 8, 1), 4, Decimal('116.75'), Decimal('0.43'), 4, 4, 2, Decimal('115.12'), Decimal('18.41'), 116, Decimal('3.63'), 4),
 (1, datetime.date(2026, 8, 2), 4, Decimal('77.12'), Decimal('0.24'), 4, 8, 1, Decimal('109.15'), Decimal('19.26'), 120, Decimal('3.64'), 1),
 (1, datetime.date(2026, 8, 3), 1, Decimal('120.00'), Decimal('0.01'), 4, 1, 3, Decimal('108.58'), Decimal('19.30'), 121, Decimal('3.56'), 3),
 (1, datetime.date(2026, 8, 4), 3, Decimal('126.67'), Decimal('0.29'), 1, 2, 8, Decimal('111.75'), Decimal('19.26'), 124, Decimal('3.54'), 1),
 (1, datetime.date(2026, 8, 5), 1, Decimal('30.00'), Decimal('0.01'), 3, 7, 2, Decimal('99.54'), Decimal('23.98'), 125, Decimal('3.47'), 6),
 (1, datetime.date(2026, 8, 6), 6, Decimal('107.67'), Decimal('0.95'), 1, 4, 3, Decimal('99.57'), Decimal('22.57'), 131, Decimal('3.54'), 5),
 (1, datetime.date(2026, 8, 7), 5, Decimal('119.10'), Decimal('0.85'), 6, 4, 2, Decimal('99.62'), Decimal('22.70'), 136, Decimal('3.58'), 4),
 (1, datetime.date(2026, 8, 8), 4, Decimal('115.82'), Decimal('0.80'), 5, 4, 3, Decimal('99.48'), Decimal('22.43'), 140, Decimal('3.59'), 11),
 (1, datetime.date(2026, 8, 9), 11, Decimal('114.77'), Decimal('1.63'), 4, 4, 1, Decimal('104.86'), Decimal('22.48'), 151, Decimal('3.78'), 6),
 (1, datetime.date(2026, 8, 10), 6, Decimal('90.00'), Decimal('2.42'), 11, 1, 3, Decimal('100.58'), Decimal('22.02'), 157, Decimal('3.83'), 2),
 (1, datetime.date(2026, 8, 11), 2, Decimal('110.00'), Decimal('0.23'), 6, 3, 10, Decimal('98.19'), Decimal('22.03'), 159, Decimal('3.79'), 6),
 (1, datetime.date(2026, 8, 12), 6, Decimal('105.32'), Decimal('35.83'), 2, 1, 3, Decimal('108.95'), Decimal('21.92'), 165, Decimal('3.84'), 6),
 (1, datetime.date(2026, 8, 13), 6, Decimal('105.67'), Decimal('19.62'), 6, 6, 1, Decimal('108.67'), Decimal('21.89'), 171, Decimal('3.89'), 3),
 (1, datetime.date(2026, 8, 14), 3, Decimal('130.00'), Decimal('0.09'), 6, 5, 2, Decimal('110.23'), Decimal('22.19'), 174, Decimal('3.87'), 3),
 (1, datetime.date(2026, 8, 15), 3, Decimal('108.33'), Decimal('0.15'), 3, 4, 1, Decimal('109.16'), Decimal('22.13'), 177, Decimal('3.85'), 8),
 (1, datetime.date(2026, 8, 16), 8, Decimal('89.45'), Decimal('48.64'), 3, 11, 3, Decimal('105.54'), Decimal('22.28'), 185, Decimal('3.94'), 4),
 (1, datetime.date(2026, 8, 17), 4, Decimal('82.25'), Decimal('0.22'), 8, 6, 3, Decimal('104.43'), Decimal('21.82'), 189, Decimal('3.94'), 1),
 (1, datetime.date(2026, 8, 18), 1, Decimal('57.60'), Decimal('14.80'), 4, 2, 6, Decimal('96.95'), Decimal('23.36'), 190, Decimal('3.88'), 4),
 (1, datetime.date(2026, 8, 19), 4, Decimal('107.89'), Decimal('15.34'), 1, 6, 9, Decimal('97.31'), Decimal('23.19'), 194, Decimal('3.88'), 5),
 (1, datetime.date(2026, 8, 20), 5, Decimal('100.40'), Decimal('0.39'), 4, 6, 3, Decimal('96.56'), Decimal('23.07'), 199, Decimal('3.90'), 1),
 (1, datetime.date(2026, 8, 21), 1, Decimal('115.00'), Decimal('0.38'), 5, 3, 5, Decimal('94.42'), Decimal('22.71'), 200, Decimal('3.85'), 2),
 (1, datetime.date(2026, 8, 22), 2, Decimal('125.00'), Decimal('0.02'), 1, 3, 3, Decimal('96.80'), Decimal('22.72'), 202, Decimal('3.81'), 2),
 (1, datetime.date(2026, 8, 23), 2, Decimal('106.50'), Decimal('0.19'), 2, 8, 3, Decimal('99.23'), Decimal('21.89'), 204, Decimal('3.78'), 3),
 (1, datetime.date(2026, 8, 24), 3, Decimal('83.33'), Decimal('0.45'), 2, 4, 4, Decimal('99.39'), Decimal('21.49'), 207, Decimal('3.76'), 2),
 (1, datetime.date(2026, 8, 25), 2, Decimal('121.96'), Decimal('0.77'), 3, 1, 8, Decimal('108.58'), Decimal('21.57'), 209, Decimal('3.73'), 7),
 (1, datetime.date(2026, 8, 26), 7, Decimal('100.86'), Decimal('52.36'), 2, 4, 1, Decimal('107.58'), Decimal('21.26'), 216, Decimal('3.79'), 2),
 (1, datetime.date(2026, 8, 27), 2, Decimal('103.00'), Decimal('0.03'), 7, 5, 2, Decimal('107.95'), Decimal('21.26'), 218, Decimal('3.76'), 3),
 (1, datetime.date(2026, 8, 28), 3, Decimal('101.50'), Decimal('37.40'), 2, 1, 7, Decimal('106.02'), Decimal('21.15'), 221, Decimal('3.75'), 2),
 (1, datetime.date(2026, 8, 29), 2, Decimal('122.50'), Decimal('0.15'), 3, 2, 4, Decimal('105.66'), Decimal('21.43'), 223, Decimal('3.72'), 3),
 (1, datetime.date(2026, 8, 30), 3, Decimal('50.00'), Decimal('0.03'), 2, 2, 4, Decimal('97.59'), Decimal('23.36'), 226, Decimal('3.70'), 5),
 (1, datetime.date(2026, 8, 31), 5, Decimal('107.40'), Decimal('0.35'), 3, 3, 4, Decimal('101.03'), Decimal('23.21'), 231, Decimal('3.73'), None),
 (2, datetime.date(2026, 7, 31), 0, None, Decimal('0.00'), 1, 0, 0, Decimal('49.90'), Decimal('19.31'), 11, Decimal('0.35'), 0),
 (2, datetime.date(2026, 8, 1), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('49.90'), Decimal('19.31'), 11, Decimal('0.34'), 0),
 (2, datetime.date(2026, 8, 2), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('49.90'), Decimal('19.31'), 11, Decimal('0.33'), 0),
 (2, datetime.date(2026, 8, 3), 0, None, Decimal('0.00'), 0, 0, 1, Decimal('49.90'), Decimal('19.64'), 11, Decimal('0.32'), 0),
 (2, datetime.date(2026, 8, 4), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('49.90'), Decimal('19.64'), 11, Decimal('0.31'), 1),
 (2, datetime.date(2026, 8, 5), 1, Decimal('16.30'), Decimal('4.94'), 0, 2, 0, Decimal('30.30'), Decimal('22.21'), 12, Decimal('0.33'), 0),
 (2, datetime.date(2026, 8, 6), 0, None, Decimal('0.00'), 1, 1, 0, Decimal('16.30'), Decimal('22.21'), 12, Decimal('0.32'), 0),
 (2, datetime.date(2026, 8, 7), 0, None, Decimal('0.00'), 0, 0, 1, Decimal('16.30'), Decimal('22.28'), 12, Decimal('0.32'), 0),
 (2, datetime.date(2026, 8, 8), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('16.30'), Decimal('22.28'), 12, Decimal('0.31'), 0),
 (2, datetime.date(2026, 8, 9), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('16.30'), Decimal('22.28'), 12, Decimal('0.30'), 0),
 (2, datetime.date(2026, 8, 10), 0, None, Decimal('0.00'), 0, 0, 2, Decimal('16.30'), Decimal('21.64'), 12, Decimal('0.29'), 0),
 (2, datetime.date(2026, 8, 11), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('16.30'), Decimal('21.64'), 12, Decimal('0.29'), 1),
 (2, datetime.date(2026, 8, 12), 1, Decimal('45.00'), Decimal('9.50'), 0, 1, 0, Decimal('45.00'), Decimal('20.04'), 13, Decimal('0.30'), 0),
 (2, datetime.date(2026, 8, 13), 0, None, Decimal('0.00'), 1, 0, 0, Decimal('45.00'), Decimal('20.04'), 13, Decimal('0.30'), 0),
 (2, datetime.date(2026, 8, 14), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('45.00'), Decimal('20.04'), 13, Decimal('0.29'), 0),
 (2, datetime.date(2026, 8, 15), 0, None, Decimal('0.00'), 0, 0, 1, Decimal('45.00'), Decimal('21.07'), 13, Decimal('0.28'), 0),
 (2, datetime.date(2026, 8, 16), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('45.00'), Decimal('21.07'), 13, Decimal('0.28'), 0),
 (2, datetime.date(2026, 8, 17), 0, None, Decimal('0.00'), 0, 0, 1, Decimal('45.00'), Decimal('19.50'), 13, Decimal('0.27'), 1),
 (2, datetime.date(2026, 8, 18), 1, Decimal('26.80'), Decimal('5.68'), 0, 0, 0, Decimal('35.90'), Decimal('19.78'), 14, Decimal('0.29'), 0),
 (2, datetime.date(2026, 8, 19), 0, None, Decimal('0.00'), 1, 1, 0, Decimal('26.80'), Decimal('19.78'), 14, Decimal('0.28'), 0),
 (2, datetime.date(2026, 8, 20), 0, None, Decimal('0.00'), 0, 0, 1, Decimal('26.80'), Decimal('18.42'), 14, Decimal('0.27'), 1),
 (2, datetime.date(2026, 8, 21), 1, Decimal('151.80'), Decimal('37.89'), 0, 0, 0, Decimal('89.30'), Decimal('44.63'), 15, Decimal('0.29'), 1),
 (2, datetime.date(2026, 8, 22), 1, Decimal('75.10'), Decimal('19.66'), 1, 0, 1, Decimal('84.57'), Decimal('45.01'), 16, Decimal('0.30'), 0),
 (2, datetime.date(2026, 8, 23), 0, None, Decimal('0.00'), 1, 0, 0, Decimal('84.57'), Decimal('45.01'), 16, Decimal('0.30'), 1),
 (2, datetime.date(2026, 8, 24), 1, Decimal('38.00'), Decimal('12.11'), 0, 0, 0, Decimal('72.93'), Decimal('42.34'), 17, Decimal('0.31'), 0),
 (2, datetime.date(2026, 8, 25), 0, None, Decimal('0.00'), 1, 1, 0, Decimal('88.30'), Decimal('42.34'), 17, Decimal('0.30'), 0),
 (2, datetime.date(2026, 8, 26), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('88.30'), Decimal('42.34'), 17, Decimal('0.30'), 0),
 (2, datetime.date(2026, 8, 27), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('88.30'), Decimal('42.34'), 17, Decimal('0.29'), 0),
 (2, datetime.date(2026, 8, 28), 0, None, Decimal('0.00'), 0, 1, 2, Decimal('56.55'), Decimal('45.73'), 17, Decimal('0.29'), 0),
 (2, datetime.date(2026, 8, 29), 0, None, Decimal('0.00'), 0, 1, 1, Decimal('38.00'), Decimal('49.74'), 17, Decimal('0.28'), 1),
 (2, datetime.date(2026, 8, 30), 1, Decimal('70.00'), Decimal('17.13'), 0, 0, 0, Decimal('54.00'), Decimal('45.60'), 18, Decimal('0.30'), 0),
 (2, datetime.date(2026, 8, 31), 0, None, Decimal('0.00'), 1, 1, 0, Decimal('70.00'), Decimal('45.60'), 18, Decimal('0.29'), None),
 (3, datetime.date(2026, 7, 31), 6, Decimal('18.44'), Decimal('23.87'), 3, 4, 1, Decimal('23.87'), Decimal('11.19'), 119, Decimal('3.84'), 6),
 (3, datetime.date(2026, 8, 1), 6, Decimal('28.58'), Decimal('42.12'), 6, 5, 0, Decimal('25.68'), Decimal('10.99'), 125, Decimal('3.91'), 6),
 (3, datetime.date(2026, 8, 2), 6, Decimal('27.98'), Decimal('46.89'), 6, 8, 0, Decimal('25.29'), Decimal('10.79'), 131, Decimal('3.97'), 6),
 (3, datetime.date(2026, 8, 3), 6, Decimal('10.89'), Decimal('9.98'), 6, 2, 6, Decimal('23.27'), Decimal('10.97'), 137, Decimal('4.03'), 0),
 (3, datetime.date(2026, 8, 4), 0, None, Decimal('0.00'), 6, 2, 4, Decimal('22.09'), Decimal('10.95'), 137, Decimal('3.91'), 1),
 (3, datetime.date(2026, 8, 5), 1, Decimal('26.97'), Decimal('6.85'), 0, 4, 1, Decimal('22.82'), Decimal('10.71'), 138, Decimal('3.83'), 3),
 (3, datetime.date(2026, 8, 6), 3, Decimal('40.21'), Decimal('32.75'), 1, 3, 1, Decimal('25.51'), Decimal('10.87'), 141, Decimal('3.81'), 6),
 (3, datetime.date(2026, 8, 7), 6, Decimal('9.67'), Decimal('11.09'), 3, 6, 0, Decimal('24.05'), Decimal('11.09'), 147, Decimal('3.87'), 3),
 (3, datetime.date(2026, 8, 8), 3, Decimal('24.95'), Decimal('25.78'), 6, 6, 2, Decimal('23.45'), Decimal('10.68'), 150, Decimal('3.85'), 3),
 (3, datetime.date(2026, 8, 9), 3, Decimal('37.86'), Decimal('32.36'), 3, 6, 5, Decimal('25.09'), Decimal('10.86'), 153, Decimal('3.83'), 3),
 (3, datetime.date(2026, 8, 10), 3, Decimal('27.90'), Decimal('16.11'), 3, 6, 4, Decimal('27.93'), Decimal('10.77'), 156, Decimal('3.80'), 1),
 (3, datetime.date(2026, 8, 11), 1, Decimal('8.39'), Decimal('1.16'), 3, 0, 7, Decimal('25.14'), Decimal('11.24'), 157, Decimal('3.74'), 5),
 (3, datetime.date(2026, 8, 12), 5, Decimal('35.90'), Decimal('50.39'), 1, 1, 5, Decimal('26.41'), Decimal('11.30'), 162, Decimal('3.77'), 5),
 (3, datetime.date(2026, 8, 13), 5, Decimal('53.55'), Decimal('50.79'), 5, 3, 4, Decimal('28.32'), Decimal('12.41'), 167, Decimal('3.80'), 5),
 (3, datetime.date(2026, 8, 14), 5, Decimal('21.52'), Decimal('29.46'), 5, 6, 2, Decimal('30.01'), Decimal('12.22'), 172, Decimal('3.82'), 4),
 (3, datetime.date(2026, 8, 15), 4, Decimal('23.46'), Decimal('16.85'), 5, 3, 1, Decimal('29.80'), Decimal('10.45'), 176, Decimal('3.83'), 5),
 (3, datetime.date(2026, 8, 16), 5, Decimal('25.36'), Decimal('40.80'), 4, 3, 5, Decimal('28.01'), Decimal('10.43'), 181, Decimal('3.85'), 3),
 (3, datetime.date(2026, 8, 17), 3, Decimal('43.73'), Decimal('34.81'), 5, 3, 8, Decimal('30.27'), Decimal('10.80'), 184, Decimal('3.83'), 3),
 (3, datetime.date(2026, 8, 18), 3, Decimal('23.24'), Decimal('21.20'), 3, 1, 12, Decimal('32.39'), Decimal('10.80'), 187, Decimal('3.82'), 4),
 (3, datetime.date(2026, 8, 19), 4, Decimal('22.74'), Decimal('35.43'), 3, 5, 3, Decimal('30.51'), Decimal('10.67'), 191, Decimal('3.82'), 3),
 (3, datetime.date(2026, 8, 20), 3, Decimal('18.85'), Decimal('10.77'), 4, 5, 5, Decimal('25.56'), Decimal('10.34'), 194, Decimal('3.80'), 4),
 (3, datetime.date(2026, 8, 21), 4, Decimal('35.36'), Decimal('31.49'), 3, 5, 7, Decimal('27.53'), Decimal('10.50'), 198, Decimal('3.81'), 3),
 (3, datetime.date(2026, 8, 22), 3, Decimal('32.83'), Decimal('30.90'), 4, 4, 2, Decimal('28.87'), Decimal('10.11'), 201, Decimal('3.79'), 5),
 (3, datetime.date(2026, 8, 23), 5, Decimal('30.31'), Decimal('70.12'), 3, 5, 4, Decimal('29.58'), Decimal('9.97'), 206, Decimal('3.81'), 1),
 (3, datetime.date(2026, 8, 24), 1, Decimal('3.00'), Decimal('14.91'), 5, 3, 5, Decimal('23.76'), Decimal('10.73'), 207, Decimal('3.76'), 2),
 (3, datetime.date(2026, 8, 25), 2, Decimal('20.70'), Decimal('5.81'), 1, 3, 8, Decimal('23.40'), Decimal('10.75'), 209, Decimal('3.73'), 4),
 (3, datetime.date(2026, 8, 26), 4, Decimal('31.11'), Decimal('32.57'), 2, 4, 2, Decimal('24.59'), Decimal('10.79'), 213, Decimal('3.74'), 1),
 (3, datetime.date(2026, 8, 27), 1, Decimal('39.34'), Decimal('8.03'), 4, 3, 2, Decimal('27.52'), Decimal('11.04'), 214, Decimal('3.69'), 5),
 (3, datetime.date(2026, 8, 28), 5, Decimal('16.02'), Decimal('12.08'), 1, 4, 4, Decimal('24.76'), Decimal('11.19'), 219, Decimal('3.71'), 6),
 (3, datetime.date(2026, 8, 29), 6, Decimal('27.79'), Decimal('46.10'), 5, 3, 3, Decimal('24.04'), Decimal('11.18'), 225, Decimal('3.75'), 5),
 (3, datetime.date(2026, 8, 30), 5, Decimal('41.85'), Decimal('78.57'), 6, 5, 6, Decimal('25.69'), Decimal('11.42'), 230, Decimal('3.77'), 4),
 (3, datetime.date(2026, 8, 31), 4, Decimal('44.88'), Decimal('49.98'), 5, 1, 6, Decimal('31.67'), Decimal('11.88'), 234, Decimal('3.77'), None),
 (4, datetime.date(2026, 7, 31), 606, Decimal('18.55'), Decimal('2029.65'), 393, 555, 372, Decimal('19.32'), Decimal('0.78'), 14983, Decimal('483.32'), 881),
 (4, datetime.date(2026, 8, 1), 881, Decimal('18.99'), Decimal('2857.64'), 606, 902, 462, Decimal('19.38'), Decimal('0.77'), 15864, Decimal('495.75'), 682),
 (4, datetime.date(2026, 8, 2), 682, Decimal('19.04'), Decimal('2462.90'), 881, 724, 454, Decimal('19.39'), Decimal('0.74'), 16546, Decimal('501.39'), 282),
 (4, datetime.date(2026, 8, 3), 282, Decimal('21.92'), Decimal('1018.32'), 682, 276, 537, Decimal('19.88'), Decimal('0.91'), 16828, Decimal('494.94'), 371),
 (4, datetime.date(2026, 8, 4), 371, Decimal('19.80'), Decimal('1246.03'), 282, 338, 369, Decimal('19.80'), Decimal('0.91'), 17199, Decimal('491.40'), 391),
 (4, datetime.date(2026, 8, 5), 391, Decimal('19.09'), Decimal('1322.89'), 371, 399, 231, Decimal('19.70'), Decimal('0.91'), 17590, Decimal('488.61'), 454),
 (4, datetime.date(2026, 8, 6), 454, Decimal('20.18'), Decimal('1572.61'), 391, 393, 246, Decimal('19.65'), Decimal('0.92'), 18044, Decimal('487.68'), 639),
 (4, datetime.date(2026, 8, 7), 639, Decimal('19.16'), Decimal('2018.32'), 454, 606, 323, Decimal('19.74'), Decimal('0.91'), 18683, Decimal('491.66'), 904),
 (4, datetime.date(2026, 8, 8), 904, Decimal('19.76'), Decimal('3232.76'), 639, 881, 360, Decimal('19.85'), Decimal('0.90'), 19587, Decimal('502.23'), 684),
 (4, datetime.date(2026, 8, 9), 684, Decimal('18.60'), Decimal('2407.06'), 904, 682, 521, Decimal('19.79'), Decimal('0.88'), 20271, Decimal('506.78'), 277),
 (4, datetime.date(2026, 8, 10), 277, Decimal('18.45'), Decimal('1027.10'), 684, 282, 837, Decimal('19.29'), Decimal('0.88'), 20548, Decimal('501.17'), 353),
 (4, datetime.date(2026, 8, 11), 353, Decimal('19.99'), Decimal('1314.46'), 277, 371, 752, Decimal('19.32'), Decimal('0.89'), 20901, Decimal('497.64'), 392),
 (4, datetime.date(2026, 8, 12), 392, Decimal('19.52'), Decimal('1411.16'), 353, 391, 257, Decimal('19.38'), Decimal('0.87'), 21293, Decimal('495.19'), 450),
 (4, datetime.date(2026, 8, 13), 450, Decimal('18.96'), Decimal('1494.78'), 392, 454, 387, Decimal('19.21'), Decimal('0.84'), 21743, Decimal('494.16'), 575),
 (4, datetime.date(2026, 8, 14), 575, Decimal('19.30'), Decimal('2069.73'), 450, 639, 377, Decimal('19.23'), Decimal('0.84'), 22318, Decimal('495.96'), 852),
 (4, datetime.date(2026, 8, 15), 852, Decimal('18.54'), Decimal('3007.14'), 575, 904, 424, Decimal('19.05'), Decimal('0.83'), 23170, Decimal('503.70'), 709),
 (4, datetime.date(2026, 8, 16), 709, Decimal('18.53'), Decimal('2448.76'), 852, 684, 623, Decimal('19.04'), Decimal('0.85'), 23879, Decimal('508.06'), 306),
 (4, datetime.date(2026, 8, 17), 306, Decimal('19.34'), Decimal('1171.74'), 709, 277, 967, Decimal('19.17'), Decimal('0.84'), 24185, Decimal('503.85'), 350),
 (4, datetime.date(2026, 8, 18), 350, Decimal('19.95'), Decimal('1313.72'), 306, 353, 871, Decimal('19.16'), Decimal('0.85'), 24535, Decimal('500.71'), 366),
 (4, datetime.date(2026, 8, 19), 366, Decimal('19.85'), Decimal('1356.55'), 350, 392, 292, Decimal('19.21'), Decimal('0.80'), 24901, Decimal('498.02'), 478),
 (4, datetime.date(2026, 8, 20), 478, Decimal('19.55'), Decimal('1483.04'), 366, 450, 315, Decimal('19.29'), Decimal('0.80'), 25379, Decimal('497.63'), 504),
 (4, datetime.date(2026, 8, 21), 504, Decimal('19.04'), Decimal('1770.56'), 478, 575, 366, Decimal('19.26'), Decimal('0.79'), 25883, Decimal('497.75'), 877),
 (4, datetime.date(2026, 8, 22), 877, Decimal('19.13'), Decimal('3341.97'), 504, 852, 447, Decimal('19.34'), Decimal('0.78'), 26760, Decimal('504.91'), 732),
 (4, datetime.date(2026, 8, 23), 732, Decimal('18.67'), Decimal('2792.26'), 877, 709, 555, Decimal('19.36'), Decimal('0.77'), 27492, Decimal('509.11'), 259),
 (4, datetime.date(2026, 8, 24), 259, Decimal('19.38'), Decimal('967.42'), 732, 306, 902, Decimal('19.37'), Decimal('0.76'), 27751, Decimal('504.56'), 325),
 (4, datetime.date(2026, 8, 25), 325, Decimal('18.71'), Decimal('1140.49'), 259, 350, 724, Decimal('19.19'), Decimal('0.77'), 28076, Decimal('501.36'), 372),
 (4, datetime.date(2026, 8, 26), 372, Decimal('19.90'), Decimal('1428.01'), 325, 366, 276, Decimal('19.20'), Decimal('0.75'), 28448, Decimal('499.09'), 411),
 (4, datetime.date(2026, 8, 27), 411, Decimal('19.85'), Decimal('1458.16'), 372, 478, 338, Decimal('19.24'), Decimal('0.73'), 28859, Decimal('497.57'), 570),
 (4, datetime.date(2026, 8, 28), 570, Decimal('19.84'), Decimal('2019.04'), 411, 504, 399, Decimal('19.35'), Decimal('0.74'), 29429, Decimal('498.80'), 880),
 (4, datetime.date(2026, 8, 29), 880, Decimal('19.06'), Decimal('3145.98'), 570, 877, 393, Decimal('19.34'), Decimal('0.71'), 30309, Decimal('505.15'), 734),
 (4, datetime.date(2026, 8, 30), 734, Decimal('18.81'), Decimal('2780.17'), 880, 732, 606, Decimal('19.36'), Decimal('0.70'), 31043, Decimal('508.90'), 313),
 (4, datetime.date(2026, 8, 31), 313, Decimal('18.98'), Decimal('1142.56'), 734, 259, 881, Decimal('19.31'), Decimal('0.70'), 31356, Decimal('505.74'), None),
 (5, datetime.date(2026, 7, 31), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('61.10'), Decimal('16.41'), 2, Decimal('0.06'), 0),
 (5, datetime.date(2026, 8, 1), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('61.10'), Decimal('16.41'), 2, Decimal('0.06'), 0),
 (5, datetime.date(2026, 8, 2), 0, None, Decimal('0.00'), 0, 1, 0, None, Decimal('16.41'), 2, Decimal('0.06'), 2),
 (5, datetime.date(2026, 8, 3), 2, Decimal('68.62'), Decimal('43.96'), 0, 0, 1, Decimal('68.62'), Decimal('5.32'), 4, Decimal('0.12'), 0),
 (5, datetime.date(2026, 8, 4), 0, None, Decimal('0.00'), 2, 0, 0, Decimal('68.62'), Decimal('5.32'), 4, Decimal('0.11'), 0),
 (5, datetime.date(2026, 8, 5), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('68.62'), Decimal('5.32'), 4, Decimal('0.11'), 0),
 (5, datetime.date(2026, 8, 6), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('68.62'), Decimal('5.32'), 4, Decimal('0.11'), 1),
 (5, datetime.date(2026, 8, 7), 1, Decimal('67.62'), Decimal('19.81'), 0, 0, 0, Decimal('68.12'), Decimal('4.08'), 5, Decimal('0.13'), 0),
 (5, datetime.date(2026, 8, 8), 0, None, Decimal('0.00'), 1, 0, 0, Decimal('68.12'), Decimal('4.08'), 5, Decimal('0.13'), 1),
 (5, datetime.date(2026, 8, 9), 1, Decimal('37.99'), Decimal('7.10'), 0, 0, 0, Decimal('58.08'), Decimal('14.29'), 6, Decimal('0.15'), 0),
 (5, datetime.date(2026, 8, 10), 0, None, Decimal('0.00'), 1, 2, 0, Decimal('52.81'), Decimal('14.29'), 6, Decimal('0.15'), 0),
 (5, datetime.date(2026, 8, 11), 0, None, Decimal('0.00'), 0, 0, 0, Decimal('52.81'), Decimal('14.29'), 6, Decimal('0.14'), 0),

### Sanity-check ознак (assertions)
Перевірrа, що `LAG(…, k)` дорівнює значенню з дати `ts_day - k` **тієї ж зони** (немає off-by-one і "перетікання" між зонами),
а `cumulative_trips` збігається з незалежно порахованою сумою.

In [28]:
checks = pd.read_sql('''
    SELECT
        COUNT(*) AS n_feature_rows,
        COUNT(DISTINCT f.pickup_zone_id) AS n_zones,
        COUNT(*) FILTER (
            WHERE f.trips_lag_1d
            IS DISTINCT FROM d1.trip_count
        )                                AS lag1_mismatch,
        COUNT(*) FILTER (
            WHERE f.trips_lag_7d
            IS DISTINCT FROM d7.trip_count
        )                                AS lag7_mismatch,
        COUNT(*) FILTER (
            WHERE f.trips_lag_30d
            IS DISTINCT FROM d30.trip_count
        )                                AS lag30_mismatch,
        COUNT(*) FILTER (
            WHERE f.cumulative_trips
            IS DISTINCT FROM (
                SELECT SUM(x.trip_count)
                FROM t7_hw_taxi_daily x
                WHERE x.pickup_zone_id = f.pickup_zone_id
                    AND x.ts_day <= f.ts_day
                )
        )                                AS cumsum_mismatch
    FROM v_t7_hw_taxi_features f
    LEFT JOIN t7_hw_taxi_daily d1
        ON d1.pickup_zone_id = f.pickup_zone_id
            AND d1.ts_day  = f.ts_day - 1
    LEFT JOIN t7_hw_taxi_daily d7
        ON d7.pickup_zone_id  = f.pickup_zone_id
            AND d7.ts_day  = f.ts_day - 7
    LEFT JOIN t7_hw_taxi_daily d30
        ON d30.pickup_zone_id = f.pickup_zone_id
            AND d30.ts_day = f.ts_day - 30
    ''',
    engine
)
display(checks)
row = checks.iloc[0]
assert row.n_feature_rows > 0
assert \
    row.lag1_mismatch == \
    row.lag7_mismatch == \
    row.lag30_mismatch == \
    row.cumsum_mismatch == 0
print("OK: lag/expanding features are calendar-correct and partitioned by zone")

,n_feature_rows,n_zones,lag1_mismatch,lag7_mismatch,lag30_mismatch,cumsum_mismatch
0,8352,261,0,0,0,0

OK: lag/expanding features are calendar-correct and partitioned by zone

## 3. JSONB event-log `t7_hw_events`

50 000 синтетичних подій, 5 event-типів, у кожного — своя схема `payload`:

<br>

| event_type | ключі payload |
|---|---|
| `page_view` | `url`, <br><br> `referrer`, <br><br> `device` |
| `click` | `element_id`, <br><br> `page_url`, <br><br> `device` |
| `add_to_cart` | `product_id`, <br><br> `price`, <br><br> `quantity`, <br><br> `tags[]` |
| `checkout` | `order_id`, <br><br> `total`, <br><br> `items_count`, <br><br> `payment_method` |
| `recommendation_shown` | `model_name`, <br><br> `model_version`, <br><br> `recommendations[]`, <br><br> `experiment` |

<br>

`event_ts` $-$ `TIMESTAMPTZ` (абсолютний момент події), значення детерміновані (від фіксованої дати, а не `NOW()`). `DROP INDEX` не потрібен: індекси видаляються разом із таблицею.

In [29]:
%%sql
DROP TABLE IF EXISTS t7_hw_checkouts_norm;
DROP TABLE IF EXISTS t7_hw_events;

CREATE TABLE t7_hw_events (
    event_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    event_ts    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    event_type  TEXT NOT NULL,
    payload     JSONB NOT NULL
);

INSERT INTO t7_hw_events (user_id, event_ts, event_type, payload)
SELECT
    (n % 1000) + 1 AS user_id,
    TIMESTAMPTZ '2026-09-01 00:00:00+00'
        - ((n % 60) || ' days')::INTERVAL AS event_ts,
    CASE (n % 5)
        WHEN 0 THEN 'page_view'
        WHEN 1 THEN 'click'
        WHEN 2 THEN 'add_to_cart'
        WHEN 3 THEN 'checkout'
        ELSE        'recommendation_shown'
    END AS event_type,
    CASE (n % 5)
        WHEN 0 THEN jsonb_build_object(
            'url', '/product/' || ((n % 200) + 1),
            'referrer', (ARRAY['google','direct','email','fb'])[(n % 4) + 1],
            'device', (ARRAY['mobile','desktop','tablet'])[(n % 3) + 1]
        )
        WHEN 1 THEN jsonb_build_object(
            'element_id', 'btn_' || ((n % 50) + 1),
            'page_url', '/category/' || ((n % 20) + 1),
            'device', (ARRAY['mobile','desktop'])[(n % 2) + 1]
        )
        WHEN 2 THEN jsonb_build_object(
            'product_id', (n % 200) + 1,
            'price', ((n % 100) + 10)::NUMERIC(10, 2),
            'quantity', (n % 5) + 1,
            'tags', jsonb_build_array(
                (ARRAY['promo','new','clearance'])[(n % 3) + 1]
            )
        )
        WHEN 3 THEN jsonb_build_object(
            'order_id', 'o_' || (n + 100000),
            'total', ((n % 500) + 50)::NUMERIC(10, 2),
            'items_count', (n % 10) + 1,
            'payment_method', (ARRAY['card','paypal','crypto'])[(n % 3) + 1]
        )
        ELSE jsonb_build_object(
            'model_name', 'rec_v' || ((n % 5) + 1),
            'model_version', '1.' || (n % 10),
            'recommendations', jsonb_build_array(
                (n % 200) + 1,
                ((n + 1) % 200) + 1,
                ((n + 2) % 200) + 1
            ),
            'experiment', 'exp_' || ((n % 3) + 1)
        )
    END AS payload
FROM generate_series(1, 50000) AS n;

ANALYZE t7_hw_events;

SELECT
    event_type,
    COUNT(*) AS n_events
FROM t7_hw_events
GROUP BY event_type
ORDER BY event_type;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
Done.
Done.
Done.
50000 rows affected.
Done.
5 rows affected.

[('add_to_cart', 10000),
 ('checkout', 10000),
 ('click', 10000),
 ('page_view', 10000),
 ('recommendation_shown', 10000)]

In [30]:
%%sql
-- різні схеми payload: набір top-level ключів для кожного event_type
SELECT
    event_type,
    (
        SELECT
            string_agg(k, ', ' ORDER BY k)
        FROM jsonb_object_keys(payload) AS k
    ) AS payload_keys,
    COUNT(*) AS n
FROM t7_hw_events
GROUP BY 1, 2
ORDER BY 1;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
5 rows affected.

[('add_to_cart', 'price, product_id, quantity, tags', 10000),
 ('checkout', 'items_count, order_id, payment_method, total', 10000),
 ('click', 'device, element_id, page_url', 10000),
 ('page_view', 'device, referrer, url', 10000),
 ('recommendation_shown', 'experiment, model_name, model_version, recommendations', 10000)]

### JSONB Query 1. Containment `@>`

In [31]:
%%sql
SELECT
    event_id,
    user_id,
    event_ts,
    payload
FROM t7_hw_events
WHERE event_type = 'checkout'
  AND payload @> jsonb_build_object('payment_method', 'card')
ORDER BY event_id;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
3334 rows affected.

[(3, 4, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 53.0, 'order_id': 'o_100003', 'items_count': 4, 'payment_method': 'card'}),
 (18, 19, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 68.0, 'order_id': 'o_100018', 'items_count': 9, 'payment_method': 'card'}),
 (33, 34, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 83.0, 'order_id': 'o_100033', 'items_count': 4, 'payment_method': 'card'}),
 (48, 49, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 98.0, 'order_id': 'o_100048', 'items_count': 9, 'payment_method': 'card'}),
 (63, 64, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 113.0, 'order_id': 'o_100063', 'items_count': 4, 'payment_method': 'card'}),
 (78, 79, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 128.0, 'order_id': 'o_100078', 'items_count': 9, 'payment_method': 'card'}),
 (93, 94, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 143.0, 'order_id': 'o_100093', 'items_count': 4, 'payment_method': 'card'}),
 (108, 109, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 158.0, 'order_id': 'o_100108', 'items_count': 9, 'payment_method': 'card'}),
 (123, 124, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 173.0, 'order_id': 'o_100123', 'items_count': 4, 'payment_method': 'card'}),
 (138, 139, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 188.0, 'order_id': 'o_100138', 'items_count': 9, 'payment_method': 'card'}),
 (153, 154, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 203.0, 'order_id': 'o_100153', 'items_count': 4, 'payment_method': 'card'}),
 (168, 169, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 218.0, 'order_id': 'o_100168', 'items_count': 9, 'payment_method': 'card'}),
 (183, 184, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 233.0, 'order_id': 'o_100183', 'items_count': 4, 'payment_method': 'card'}),
 (198, 199, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 248.0, 'order_id': 'o_100198', 'items_count': 9, 'payment_method': 'card'}),
 (213, 214, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 263.0, 'order_id': 'o_100213', 'items_count': 4, 'payment_method': 'card'}),
 (228, 229, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 278.0, 'order_id': 'o_100228', 'items_count': 9, 'payment_method': 'card'}),
 (243, 244, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 293.0, 'order_id': 'o_100243', 'items_count': 4, 'payment_method': 'card'}),
 (258, 259, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 308.0, 'order_id': 'o_100258', 'items_count': 9, 'payment_method': 'card'}),
 (273, 274, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 323.0, 'order_id': 'o_100273', 'items_count': 4, 'payment_method': 'card'}),
 (288, 289, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 338.0, 'order_id': 'o_100288', 'items_count': 9, 'payment_method': 'card'}),
 (303, 304, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 353.0, 'order_id': 'o_100303', 'items_count': 4, 'payment_method': 'card'}),
 (318, 319, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 368.0, 'order_id': 'o_100318', 'items_count': 9, 'payment_method': 'card'}),
 (333, 334, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 383.0, 'order_id': 'o_100333', 'items_count': 4, 'payment_method': 'card'}),
 (348, 349, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 398.0, 'order_id': 'o_100348', 'items_count': 9, 'payment_method': 'card'}),
 (363, 364, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 413.0, 'order_id': 'o_100363', 'items_count': 4, 'payment_method': 'card'}),
 (378, 379, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 428.0, 'order_id': 'o_100378', 'items_count': 9, 'payment_method': 'card'}),
 (393, 394, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 443.0, 'order_id': 'o_100393', 'items_count': 4, 'payment_method': 'card'}),
 (408, 409, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 458.0, 'order_id': 'o_100408', 'items_count': 9, 'payment_method': 'card'}),
 (423, 424, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 473.0, 'order_id': 'o_100423', 'items_count': 4, 'payment_method': 'card'}),
 (438, 439, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 488.0, 'order_id': 'o_100438', 'items_count': 9, 'payment_method': 'card'}),
 (453, 454, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 503.0, 'order_id': 'o_100453', 'items_count': 4, 'payment_method': 'card'}),
 (468, 469, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 518.0, 'order_id': 'o_100468', 'items_count': 9, 'payment_method': 'card'}),
 (483, 484, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 533.0, 'order_id': 'o_100483', 'items_count': 4, 'payment_method': 'card'}),
 (498, 499, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 548.0, 'order_id': 'o_100498', 'items_count': 9, 'payment_method': 'card'}),
 (513, 514, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 63.0, 'order_id': 'o_100513', 'items_count': 4, 'payment_method': 'card'}),
 (528, 529, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 78.0, 'order_id': 'o_100528', 'items_count': 9, 'payment_method': 'card'}),
 (543, 544, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 93.0, 'order_id': 'o_100543', 'items_count': 4, 'payment_method': 'card'}),
 (558, 559, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 108.0, 'order_id': 'o_100558', 'items_count': 9, 'payment_method': 'card'}),
 (573, 574, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 123.0, 'order_id': 'o_100573', 'items_count': 4, 'payment_method': 'card'}),
 (588, 589, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 138.0, 'order_id': 'o_100588', 'items_count': 9, 'payment_method': 'card'}),
 (603, 604, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 153.0, 'order_id': 'o_100603', 'items_count': 4, 'payment_method': 'card'}),
 (618, 619, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 168.0, 'order_id': 'o_100618', 'items_count': 9, 'payment_method': 'card'}),
 (633, 634, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 183.0, 'order_id': 'o_100633', 'items_count': 4, 'payment_method': 'card'}),
 (648, 649, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 198.0, 'order_id': 'o_100648', 'items_count': 9, 'payment_method': 'card'}),
 (663, 664, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 213.0, 'order_id': 'o_100663', 'items_count': 4, 'payment_method': 'card'}),
 (678, 679, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 228.0, 'order_id': 'o_100678', 'items_count': 9, 'payment_method': 'card'}),
 (693, 694, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 243.0, 'order_id': 'o_100693', 'items_count': 4, 'payment_method': 'card'}),
 (708, 709, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 258.0, 'order_id': 'o_100708', 'items_count': 9, 'payment_method': 'card'}),
 (723, 724, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 273.0, 'order_id': 'o_100723', 'items_count': 4, 'payment_method': 'card'}),
 (738, 739, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 288.0, 'order_id': 'o_100738', 'items_count': 9, 'payment_method': 'card'}),
 (753, 754, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 303.0, 'order_id': 'o_100753', 'items_count': 4, 'payment_method': 'card'}),
 (768, 769, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 318.0, 'order_id': 'o_100768', 'items_count': 9, 'payment_method': 'card'}),
 (783, 784, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 333.0, 'order_id': 'o_100783', 'items_count': 4, 'payment_method': 'card'}),
 (798, 799, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 348.0, 'order_id': 'o_100798', 'items_count': 9, 'payment_method': 'card'}),
 (813, 814, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 363.0, 'order_id': 'o_100813', 'items_count': 4, 'payment_method': 'card'}),
 (828, 829, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 378.0, 'order_id': 'o_100828', 'items_count': 9, 'payment_method': 'card'}),
 (843, 844, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 393.0, 'order_id': 'o_100843', 'items_count': 4, 'payment_method': 'card'}),
 (858, 859, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 408.0, 'order_id': 'o_100858', 'items_count': 9, 'payment_method': 'card'}),
 (873, 874, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 423.0, 'order_id': 'o_100873', 'items_count': 4, 'payment_method': 'card'}),
 (888, 889, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 438.0, 'order_id': 'o_100888', 'items_count': 9, 'payment_method': 'card'}),
 (903, 904, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 453.0, 'order_id': 'o_100903', 'items_count': 4, 'payment_method': 'card'}),
 (918, 919, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 468.0, 'order_id': 'o_100918', 'items_count': 9, 'payment_method': 'card'}),
 (933, 934, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 483.0, 'order_id': 'o_100933', 'items_count': 4, 'payment_method': 'card'}),
 (948, 949, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 498.0, 'order_id': 'o_100948', 'items_count': 9, 'payment_method': 'card'}),
 (963, 964, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 513.0, 'order_id': 'o_100963', 'items_count': 4, 'payment_method': 'card'}),
 (978, 979, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 528.0, 'order_id': 'o_100978', 'items_count': 9, 'payment_method': 'card'}),
 (993, 994, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 543.0, 'order_id': 'o_100993', 'items_count': 4, 'payment_method': 'card'}),
 (1008, 9, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 58.0, 'order_id': 'o_101008', 'items_count': 9, 'payment_method': 'card'}),
 (1023, 24, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 73.0, 'order_id': 'o_101023', 'items_count': 4, 'payment_method': 'card'}),
 (1038, 39, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 88.0, 'order_id': 'o_101038', 'items_count': 9, 'payment_method': 'card'}),
 (1053, 54, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 103.0, 'order_id': 'o_101053', 'items_count': 4, 'payment_method': 'card'}),
 (1068, 69, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 118.0, 'order_id': 'o_101068', 'items_count': 9, 'payment_method': 'card'}),
 (1083, 84, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 133.0, 'order_id': 'o_101083', 'items_count': 4, 'payment_method': 'card'}),
 (1098, 99, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 148.0, 'order_id': 'o_101098', 'items_count': 9, 'payment_method': 'card'}),
 (1113, 114, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 163.0, 'order_id': 'o_101113', 'items_count': 4, 'payment_method': 'card'}),
 (1128, 129, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 178.0, 'order_id': 'o_101128', 'items_count': 9, 'payment_method': 'card'}),
 (1143, 144, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 193.0, 'order_id': 'o_101143', 'items_count': 4, 'payment_method': 'card'}),
 (1158, 159, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 208.0, 'order_id': 'o_101158', 'items_count': 9, 'payment_method': 'card'}),
 (1173, 174, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 223.0, 'order_id': 'o_101173', 'items_count': 4, 'payment_method': 'card'}),
 (1188, 189, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 238.0, 'order_id': 'o_101188', 'items_count': 9, 'payment_method': 'card'}),
 (1203, 204, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 253.0, 'order_id': 'o_101203', 'items_count': 4, 'payment_method': 'card'}),
 (1218, 219, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 268.0, 'order_id': 'o_101218', 'items_count': 9, 'payment_method': 'card'}),
 (1233, 234, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 283.0, 'order_id': 'o_101233', 'items_count': 4, 'payment_method': 'card'}),
 (1248, 249, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 298.0, 'order_id': 'o_101248', 'items_count': 9, 'payment_method': 'card'}),
 (1263, 264, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 313.0, 'order_id': 'o_101263', 'items_count': 4, 'payment_method': 'card'}),
 (1278, 279, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 328.0, 'order_id': 'o_101278', 'items_count': 9, 'payment_method': 'card'}),
 (1293, 294, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 343.0, 'order_id': 'o_101293', 'items_count': 4, 'payment_method': 'card'}),
 (1308, 309, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 358.0, 'order_id': 'o_101308', 'items_count': 9, 'payment_method': 'card'}),
 (1323, 324, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 373.0, 'order_id': 'o_101323', 'items_count': 4, 'payment_method': 'card'}),
 (1338, 339, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 388.0, 'order_id': 'o_101338', 'items_count': 9, 'payment_method': 'card'}),
 (1353, 354, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 403.0, 'order_id': 'o_101353', 'items_count': 4, 'payment_method': 'card'}),
 (1368, 369, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 418.0, 'order_id': 'o_101368', 'items_count': 9, 'payment_method': 'card'}),
 (1383, 384, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 433.0, 'order_id': 'o_101383', 'items_count': 4, 'payment_method': 'card'}),
 (1398, 399, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 448.0, 'order_id': 'o_101398', 'items_count': 9, 'payment_method': 'card'}),
 (1413, 414, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 463.0, 'order_id': 'o_101413', 'items_count': 4, 'payment_method': 'card'}),
 (1428, 429, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 478.0, 'order_id': 'o_101428', 'items_count': 9, 'payment_method': 'card'}),
 (1443, 444, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 493.0, 'order_id': 'o_101443', 'items_count': 4, 'payment_method': 'card'}),
 (1458, 459, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 508.0, 'order_id': 'o_101458', 'items_count': 9, 'payment_method': 'card'}),
 (1473, 474, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 523.0, 'order_id': 'o_101473', 'items_count': 4, 'payment_method': 'card'}),
 (1488, 489, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 538.0, 'order_id': 'o_101488', 'items_count': 9, 'payment_method': 'card'}),
 (1503, 504, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 53.0, 'order_id': 'o_101503', 'items_count': 4, 'payment_method': 'card'}),
 (1518, 519, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 68.0, 'order_id': 'o_101518', 'items_count': 9, 'payment_method': 'card'}),
 (1533, 534, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 83.0, 'order_id': 'o_101533', 'items_count': 4, 'payment_method': 'card'}),
 (1548, 549, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 98.0, 'order_id': 'o_101548', 'items_count': 9, 'payment_method': 'card'}),
 (1563, 564, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 113.0, 'order_id': 'o_101563', 'items_count': 4, 'payment_method': 'card'}),
 (1578, 579, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 128.0, 'order_id': 'o_101578', 'items_count': 9, 'payment_method': 'card'}),
 (1593, 594, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 143.0, 'order_id': 'o_101593', 'items_count': 4, 'payment_method': 'card'}),
 (1608, 609, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 158.0, 'order_id': 'o_101608', 'items_count': 9, 'payment_method': 'card'}),
 (1623, 624, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 173.0, 'order_id': 'o_101623', 'items_count': 4, 'payment_method': 'card'}),
 (1638, 639, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 188.0, 'order_id': 'o_101638', 'items_count': 9, 'payment_method': 'card'}),
 (1653, 654, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 203.0, 'order_id': 'o_101653', 'items_count': 4, 'payment_method': 'card'}),
 (1668, 669, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 218.0, 'order_id': 'o_101668', 'items_count': 9, 'payment_method': 'card'}),
 (1683, 684, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 233.0, 'order_id': 'o_101683', 'items_count': 4, 'payment_method': 'card'}),
 (1698, 699, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 248.0, 'order_id': 'o_101698', 'items_count': 9, 'payment_method': 'card'}),
 (1713, 714, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 263.0, 'order_id': 'o_101713', 'items_count': 4, 'payment_method': 'card'}),
 (1728, 729, datetime.datetime(2026, 7, 15, 0, 0, tzinfo=datetime.timezone.utc), {'total': 278.0, 'order_id': 'o_101728', 'items_count': 9, 'payment_method': 'card'}),
 (1743, 744, datetime.datetime(2026, 8, 29, 0, 0, tzinfo=datetime.timezone.utc), {'total': 293.0, 'order_id': 'o_101743', 'items_count': 4, 'payment_method': 'card'}),
 (1758, 759, datetime.datetime(2026, 8, 14, 0, 0, tzinfo=datetime.timezone.utc), {'total': 308.0, 'order_id': 'o_101758', 'items_count': 9, 'payment_method': 'card'}),
 (1773, 774, datetime.datetime(2026, 7, 30, 0, 0, tzinfo=datetime.timezone.utc), {'total': 323.0, 'order_id': 'o_101773', 'items_count': 4, 'payment_method': 'card'}),

### JSONB Query 2. Key existence `?` та `?|`
`?`, `?|`, `?&` перевіряють **top-level** ключі. Для GIN-індексації таких запитів потрібен default `jsonb_ops`, а не `jsonb_path_ops` (див. Завдання **4, Step 5**).

In [32]:
%%sql
SELECT
    event_id,
    event_type,
    payload
FROM t7_hw_events
WHERE payload ? 'tags'
ORDER BY event_id;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
10000 rows affected.

[(2, 'add_to_cart', {'tags': ['clearance'], 'price': 12.0, 'quantity': 3, 'product_id': 3}),
 (7, 'add_to_cart', {'tags': ['new'], 'price': 17.0, 'quantity': 3, 'product_id': 8}),
 (12, 'add_to_cart', {'tags': ['promo'], 'price': 22.0, 'quantity': 3, 'product_id': 13}),
 (17, 'add_to_cart', {'tags': ['clearance'], 'price': 27.0, 'quantity': 3, 'product_id': 18}),
 (22, 'add_to_cart', {'tags': ['new'], 'price': 32.0, 'quantity': 3, 'product_id': 23}),
 (27, 'add_to_cart', {'tags': ['promo'], 'price': 37.0, 'quantity': 3, 'product_id': 28}),
 (32, 'add_to_cart', {'tags': ['clearance'], 'price': 42.0, 'quantity': 3, 'product_id': 33}),
 (37, 'add_to_cart', {'tags': ['new'], 'price': 47.0, 'quantity': 3, 'product_id': 38}),
 (42, 'add_to_cart', {'tags': ['promo'], 'price': 52.0, 'quantity': 3, 'product_id': 43}),
 (47, 'add_to_cart', {'tags': ['clearance'], 'price': 57.0, 'quantity': 3, 'product_id': 48}),
 (52, 'add_to_cart', {'tags': ['new'], 'price': 62.0, 'quantity': 3, 'product_id': 53}),
 (57, 'add_to_cart', {'tags': ['promo'], 'price': 67.0, 'quantity': 3, 'product_id': 58}),
 (62, 'add_to_cart', {'tags': ['clearance'], 'price': 72.0, 'quantity': 3, 'product_id': 63}),
 (67, 'add_to_cart', {'tags': ['new'], 'price': 77.0, 'quantity': 3, 'product_id': 68}),
 (72, 'add_to_cart', {'tags': ['promo'], 'price': 82.0, 'quantity': 3, 'product_id': 73}),
 (77, 'add_to_cart', {'tags': ['clearance'], 'price': 87.0, 'quantity': 3, 'product_id': 78}),
 (82, 'add_to_cart', {'tags': ['new'], 'price': 92.0, 'quantity': 3, 'product_id': 83}),
 (87, 'add_to_cart', {'tags': ['promo'], 'price': 97.0, 'quantity': 3, 'product_id': 88}),
 (92, 'add_to_cart', {'tags': ['clearance'], 'price': 102.0, 'quantity': 3, 'product_id': 93}),
 (97, 'add_to_cart', {'tags': ['new'], 'price': 107.0, 'quantity': 3, 'product_id': 98}),
 (102, 'add_to_cart', {'tags': ['promo'], 'price': 12.0, 'quantity': 3, 'product_id': 103}),
 (107, 'add_to_cart', {'tags': ['clearance'], 'price': 17.0, 'quantity': 3, 'product_id': 108}),
 (112, 'add_to_cart', {'tags': ['new'], 'price': 22.0, 'quantity': 3, 'product_id': 113}),
 (117, 'add_to_cart', {'tags': ['promo'], 'price': 27.0, 'quantity': 3, 'product_id': 118}),
 (122, 'add_to_cart', {'tags': ['clearance'], 'price': 32.0, 'quantity': 3, 'product_id': 123}),
 (127, 'add_to_cart', {'tags': ['new'], 'price': 37.0, 'quantity': 3, 'product_id': 128}),
 (132, 'add_to_cart', {'tags': ['promo'], 'price': 42.0, 'quantity': 3, 'product_id': 133}),
 (137, 'add_to_cart', {'tags': ['clearance'], 'price': 47.0, 'quantity': 3, 'product_id': 138}),
 (142, 'add_to_cart', {'tags': ['new'], 'price': 52.0, 'quantity': 3, 'product_id': 143}),
 (147, 'add_to_cart', {'tags': ['promo'], 'price': 57.0, 'quantity': 3, 'product_id': 148}),
 (152, 'add_to_cart', {'tags': ['clearance'], 'price': 62.0, 'quantity': 3, 'product_id': 153}),
 (157, 'add_to_cart', {'tags': ['new'], 'price': 67.0, 'quantity': 3, 'product_id': 158}),
 (162, 'add_to_cart', {'tags': ['promo'], 'price': 72.0, 'quantity': 3, 'product_id': 163}),
 (167, 'add_to_cart', {'tags': ['clearance'], 'price': 77.0, 'quantity': 3, 'product_id': 168}),
 (172, 'add_to_cart', {'tags': ['new'], 'price': 82.0, 'quantity': 3, 'product_id': 173}),
 (177, 'add_to_cart', {'tags': ['promo'], 'price': 87.0, 'quantity': 3, 'product_id': 178}),
 (182, 'add_to_cart', {'tags': ['clearance'], 'price': 92.0, 'quantity': 3, 'product_id': 183}),
 (187, 'add_to_cart', {'tags': ['new'], 'price': 97.0, 'quantity': 3, 'product_id': 188}),
 (192, 'add_to_cart', {'tags': ['promo'], 'price': 102.0, 'quantity': 3, 'product_id': 193}),
 (197, 'add_to_cart', {'tags': ['clearance'], 'price': 107.0, 'quantity': 3, 'product_id': 198}),
 (202, 'add_to_cart', {'tags': ['new'], 'price': 12.0, 'quantity': 3, 'product_id': 3}),
 (207, 'add_to_cart', {'tags': ['promo'], 'price': 17.0, 'quantity': 3, 'product_id': 8}),
 (212, 'add_to_cart', {'tags': ['clearance'], 'price': 22.0, 'quantity': 3, 'product_id': 13}),
 (217, 'add_to_cart', {'tags': ['new'], 'price': 27.0, 'quantity': 3, 'product_id': 18}),
 (222, 'add_to_cart', {'tags': ['promo'], 'price': 32.0, 'quantity': 3, 'product_id': 23}),
 (227, 'add_to_cart', {'tags': ['clearance'], 'price': 37.0, 'quantity': 3, 'product_id': 28}),
 (232, 'add_to_cart', {'tags': ['new'], 'price': 42.0, 'quantity': 3, 'product_id': 33}),
 (237, 'add_to_cart', {'tags': ['promo'], 'price': 47.0, 'quantity': 3, 'product_id': 38}),
 (242, 'add_to_cart', {'tags': ['clearance'], 'price': 52.0, 'quantity': 3, 'product_id': 43}),
 (247, 'add_to_cart', {'tags': ['new'], 'price': 57.0, 'quantity': 3, 'product_id': 48}),
 (252, 'add_to_cart', {'tags': ['promo'], 'price': 62.0, 'quantity': 3, 'product_id': 53}),
 (257, 'add_to_cart', {'tags': ['clearance'], 'price': 67.0, 'quantity': 3, 'product_id': 58}),
 (262, 'add_to_cart', {'tags': ['new'], 'price': 72.0, 'quantity': 3, 'product_id': 63}),
 (267, 'add_to_cart', {'tags': ['promo'], 'price': 77.0, 'quantity': 3, 'product_id': 68}),
 (272, 'add_to_cart', {'tags': ['clearance'], 'price': 82.0, 'quantity': 3, 'product_id': 73}),
 (277, 'add_to_cart', {'tags': ['new'], 'price': 87.0, 'quantity': 3, 'product_id': 78}),
 (282, 'add_to_cart', {'tags': ['promo'], 'price': 92.0, 'quantity': 3, 'product_id': 83}),
 (287, 'add_to_cart', {'tags': ['clearance'], 'price': 97.0, 'quantity': 3, 'product_id': 88}),
 (292, 'add_to_cart', {'tags': ['new'], 'price': 102.0, 'quantity': 3, 'product_id': 93}),
 (297, 'add_to_cart', {'tags': ['promo'], 'price': 107.0, 'quantity': 3, 'product_id': 98}),
 (302, 'add_to_cart', {'tags': ['clearance'], 'price': 12.0, 'quantity': 3, 'product_id': 103}),
 (307, 'add_to_cart', {'tags': ['new'], 'price': 17.0, 'quantity': 3, 'product_id': 108}),
 (312, 'add_to_cart', {'tags': ['promo'], 'price': 22.0, 'quantity': 3, 'product_id': 113}),
 (317, 'add_to_cart', {'tags': ['clearance'], 'price': 27.0, 'quantity': 3, 'product_id': 118}),
 (322, 'add_to_cart', {'tags': ['new'], 'price': 32.0, 'quantity': 3, 'product_id': 123}),
 (327, 'add_to_cart', {'tags': ['promo'], 'price': 37.0, 'quantity': 3, 'product_id': 128}),
 (332, 'add_to_cart', {'tags': ['clearance'], 'price': 42.0, 'quantity': 3, 'product_id': 133}),
 (337, 'add_to_cart', {'tags': ['new'], 'price': 47.0, 'quantity': 3, 'product_id': 138}),
 (342, 'add_to_cart', {'tags': ['promo'], 'price': 52.0, 'quantity': 3, 'product_id': 143}),
 (347, 'add_to_cart', {'tags': ['clearance'], 'price': 57.0, 'quantity': 3, 'product_id': 148}),
 (352, 'add_to_cart', {'tags': ['new'], 'price': 62.0, 'quantity': 3, 'product_id': 153}),
 (357, 'add_to_cart', {'tags': ['promo'], 'price': 67.0, 'quantity': 3, 'product_id': 158}),
 (362, 'add_to_cart', {'tags': ['clearance'], 'price': 72.0, 'quantity': 3, 'product_id': 163}),
 (367, 'add_to_cart', {'tags': ['new'], 'price': 77.0, 'quantity': 3, 'product_id': 168}),
 (372, 'add_to_cart', {'tags': ['promo'], 'price': 82.0, 'quantity': 3, 'product_id': 173}),
 (377, 'add_to_cart', {'tags': ['clearance'], 'price': 87.0, 'quantity': 3, 'product_id': 178}),
 (382, 'add_to_cart', {'tags': ['new'], 'price': 92.0, 'quantity': 3, 'product_id': 183}),
 (387, 'add_to_cart', {'tags': ['promo'], 'price': 97.0, 'quantity': 3, 'product_id': 188}),
 (392, 'add_to_cart', {'tags': ['clearance'], 'price': 102.0, 'quantity': 3, 'product_id': 193}),
 (397, 'add_to_cart', {'tags': ['new'], 'price': 107.0, 'quantity': 3, 'product_id': 198}),
 (402, 'add_to_cart', {'tags': ['promo'], 'price': 12.0, 'quantity': 3, 'product_id': 3}),
 (407, 'add_to_cart', {'tags': ['clearance'], 'price': 17.0, 'quantity': 3, 'product_id': 8}),
 (412, 'add_to_cart', {'tags': ['new'], 'price': 22.0, 'quantity': 3, 'product_id': 13}),
 (417, 'add_to_cart', {'tags': ['promo'], 'price': 27.0, 'quantity': 3, 'product_id': 18}),
 (422, 'add_to_cart', {'tags': ['clearance'], 'price': 32.0, 'quantity': 3, 'product_id': 23}),
 (427, 'add_to_cart', {'tags': ['new'], 'price': 37.0, 'quantity': 3, 'product_id': 28}),
 (432, 'add_to_cart', {'tags': ['promo'], 'price': 42.0, 'quantity': 3, 'product_id': 33}),
 (437, 'add_to_cart', {'tags': ['clearance'], 'price': 47.0, 'quantity': 3, 'product_id': 38}),
 (442, 'add_to_cart', {'tags': ['new'], 'price': 52.0, 'quantity': 3, 'product_id': 43}),
 (447, 'add_to_cart', {'tags': ['promo'], 'price': 57.0, 'quantity': 3, 'product_id': 48}),
 (452, 'add_to_cart', {'tags': ['clearance'], 'price': 62.0, 'quantity': 3, 'product_id': 53}),
 (457, 'add_to_cart', {'tags': ['new'], 'price': 67.0, 'quantity': 3, 'product_id': 58}),
 (462, 'add_to_cart', {'tags': ['promo'], 'price': 72.0, 'quantity': 3, 'product_id': 63}),
 (467, 'add_to_cart', {'tags': ['clearance'], 'price': 77.0, 'quantity': 3, 'product_id': 68}),
 (472, 'add_to_cart', {'tags': ['new'], 'price': 82.0, 'quantity': 3, 'product_id': 73}),
 (477, 'add_to_cart', {'tags': ['promo'], 'price': 87.0, 'quantity': 3, 'product_id': 78}),
 (482, 'add_to_cart', {'tags': ['clearance'], 'price': 92.0, 'quantity': 3, 'product_id': 83}),
 (487, 'add_to_cart', {'tags': ['new'], 'price': 97.0, 'quantity': 3, 'product_id': 88}),
 (492, 'add_to_cart', {'tags': ['promo'], 'price': 102.0, 'quantity': 3, 'product_id': 93}),
 (497, 'add_to_cart', {'tags': ['clearance'], 'price': 107.0, 'quantity': 3, 'product_id': 98}),
 (502, 'add_to_cart', {'tags': ['new'], 'price': 12.0, 'quantity': 3, 'product_id': 103}),
 (507, 'add_to_cart', {'tags': ['promo'], 'price': 17.0, 'quantity': 3, 'product_id': 108}),
 (512, 'add_to_cart', {'tags': ['clearance'], 'price': 22.0, 'quantity': 3, 'product_id': 113}),
 (517, 'add_to_cart', {'tags': ['new'], 'price': 27.0, 'quantity': 3, 'product_id': 118}),
 (522, 'add_to_cart', {'tags': ['promo'], 'price': 32.0, 'quantity': 3, 'product_id': 123}),
 (527, 'add_to_cart', {'tags': ['clearance'], 'price': 37.0, 'quantity': 3, 'product_id': 128}),
 (532, 'add_to_cart', {'tags': ['new'], 'price': 42.0, 'quantity': 3, 'product_id': 133}),
 (537, 'add_to_cart', {'tags': ['promo'], 'price': 47.0, 'quantity': 3, 'product_id': 138}),
 (542, 'add_to_cart', {'tags': ['clearance'], 'price': 52.0, 'quantity': 3, 'product_id': 143}),
 (547, 'add_to_cart', {'tags': ['new'], 'price': 57.0, 'quantity': 3, 'product_id': 148}),
 (552, 'add_to_cart', {'tags': ['promo'], 'price': 62.0, 'quantity': 3, 'product_id': 153}),
 (557, 'add_to_cart', {'tags': ['clearance'], 'price': 67.0, 'quantity': 3, 'product_id': 158}),
 (562, 'add_to_cart', {'tags': ['new'], 'price': 72.0, 'quantity': 3, 'product_id': 163}),
 (567, 'add_to_cart', {'tags': ['promo'], 'price': 77.0, 'quantity': 3, 'product_id': 168}),
 (572, 'add_to_cart', {'tags': ['clearance'], 'price': 82.0, 'quantity': 3, 'product_id': 173}),
 (577, 'add_to_cart', {'tags': ['new'], 'price': 87.0, 'quantity': 3, 'product_id': 178}),
 (582, 'add_to_cart', {'tags': ['promo'], 'price': 92.0, 'quantity': 3, 'product_id': 183}),
 (587, 'add_to_cart', {'tags': ['clearance'], 'price': 97.0, 'quantity': 3, 'product_id': 188}),
 (592, 'add_to_cart', {'tags': ['new'], 'price': 102.0, 'quantity': 3, 'product_id': 193}),
 (597, 'add_to_cart', {'tags': ['promo'], 'price': 107.0, 'quantity': 3, 'product_id': 198}),
 (602, 'add_to_cart', {'tags': ['clearance'], 'price': 12.0, 'quantity': 3, 'product_id': 3}),
 (607, 'add_to_cart', {'tags': ['new'], 'price': 17.0, 'quantity': 3, 'product_id': 8}),
 (612, 'add_to_cart', {'tags': ['promo'], 'price': 22.0, 'quantity': 3, 'product_id': 13}),
 (617, 'add_to_cart', {'tags': ['clearance'], 'price': 27.0, 'quantity': 3, 'product_id': 18}),
 (622, 'add_to_cart', {'tags': ['new'], 'price': 32.0, 'quantity': 3, 'product_id': 23}),
 (627, 'add_to_cart', {'tags': ['promo'], 'price': 37.0, 'quantity': 3, 'product_id': 28}),
 (632, 'add_to_cart', {'tags': ['clearance'], 'price': 42.0, 'quantity': 3, 'product_id': 33}),
 (637, 'add_to_cart', {'tags': ['new'], 'price': 47.0, 'quantity': 3, 'product_id': 38}),
 (642, 'add_to_cart', {'tags': ['promo'], 'price': 52.0, 'quantity': 3, 'product_id': 43}),
 (647, 'add_to_cart', {'tags': ['clearance'], 'price': 57.0, 'quantity': 3, 'product_id': 48}),
 (652, 'add_to_cart', {'tags': ['new'], 'price': 62.0, 'quantity': 3, 'product_id': 53}),
 (657, 'add_to_cart', {'tags': ['promo'], 'price': 67.0, 'quantity': 3, 'product_id': 58}),
 (662, 'add_to_cart', {'tags': ['clearance'], 'price': 72.0, 'quantity': 3, 'product_id': 63}),
 (667, 'add_to_cart', {'tags': ['new'], 'price': 77.0, 'quantity': 3, 'product_id': 68}),
 (672, 'add_to_cart', {'tags': ['promo'], 'price': 82.0, 'quantity': 3, 'product_id': 73}),
 (677, 'add_to_cart', {'tags': ['clearance'], 'price': 87.0, 'quantity': 3, 'product_id': 78}),
 (682, 'add_to_cart', {'tags': ['new'], 'price': 92.0, 'quantity': 3, 'product_id': 83}),
 (687, 'add_to_cart', {'tags': ['promo'], 'price': 97.0, 'quantity': 3, 'product_id': 88}),
 (692, 'add_to_cart', {'tags': ['clearance'], 'price': 102.0, 'quantity': 3, 'product_id': 93}),
 (697, 'add_to_cart', {'tags': ['new'], 'price': 107.0, 'quantity': 3, 'product_id': 98}),
 (702, 'add_to_cart', {'tags': ['promo'], 'price': 12.0, 'quantity': 3, 'product_id': 103}),
 (707, 'add_to_cart', {'tags': ['clearance'], 'price': 17.0, 'quantity': 3, 'product_id': 108}),
 (712, 'add_to_cart', {'tags': ['new'], 'price': 22.0, 'quantity': 3, 'product_id': 113}),
 (717, 'add_to_cart', {'tags': ['promo'], 'price': 27.0, 'quantity': 3, 'product_id': 118}),
 (722, 'add_to_cart', {'tags': ['clearance'], 'price': 32.0, 'quantity': 3, 'product_id': 123}),
 (727, 'add_to_cart', {'tags': ['new'], 'price': 37.0, 'quantity': 3, 'product_id': 128}),
 (732, 'add_to_cart', {'tags': ['promo'], 'price': 42.0, 'quantity': 3, 'product_id': 133}),
 (737, 'add_to_cart', {'tags': ['clearance'], 'price': 47.0, 'quantity': 3, 'product_id': 138}),
 (742, 'add_to_cart', {'tags': ['new'], 'price': 52.0, 'quantity': 3, 'product_id': 143}),
 (747, 'add_to_cart', {'tags': ['promo'], 'price': 57.0, 'quantity': 3, 'product_id': 148}),
 (752, 'add_to_cart', {'tags': ['clearance'], 'price': 62.0, 'quantity': 3, 'product_id': 153}),
 (757, 'add_to_cart', {'tags': ['new'], 'price': 67.0, 'quantity': 3, 'product_id': 158}),
 (762, 'add_to_cart', {'tags': ['promo'], 'price': 72.0, 'quantity': 3, 'product_id': 163}),
 (767, 'add_to_cart', {'tags': ['clearance'], 'price': 77.0, 'quantity': 3, 'product_id': 168}),
 (772, 'add_to_cart', {'tags': ['new'], 'price': 82.0, 'quantity': 3, 'product_id': 173}),
 (777, 'add_to_cart', {'tags': ['promo'], 'price': 87.0, 'quantity': 3, 'product_id': 178}),
 (782, 'add_to_cart', {'tags': ['clearance'], 'price': 92.0, 'quantity': 3, 'product_id': 183}),
 (787, 'add_to_cart', {'tags': ['new'], 'price': 97.0, 'quantity': 3, 'product_id': 188}),
 (792, 'add_to_cart', {'tags': ['promo'], 'price': 102.0, 'quantity': 3, 'product_id': 193}),
 (797, 'add_to_cart', {'tags': ['clearance'], 'price': 107.0, 'quantity': 3, 'product_id': 198}),
 (802, 'add_to_cart', {'tags': ['new'], 'price': 12.0, 'quantity': 3, 'product_id': 3}),
 (807, 'add_to_cart', {'tags': ['promo'], 'price': 17.0, 'quantity': 3, 'product_id': 8}),
 (812, 'add_to_cart', {'tags': ['clearance'], 'price': 22.0, 'quantity': 3, 'product_id': 13}),
 (817, 'add_to_cart', {'tags': ['new'], 'price': 27.0, 'quantity': 3, 'product_id': 18}),
 (822, 'add_to_cart', {'tags': ['promo'], 'price': 32.0, 'quantity': 3, 'product_id': 23}),
 (827, 'add_to_cart', {'tags': ['clearance'], 'price': 37.0, 'quantity': 3, 'product_id': 28}),
 (832, 'add_to_cart', {'tags': ['new'], 'price': 42.0, 'quantity': 3, 'product_id': 33}),
 (837, 'add_to_cart', {'tags': ['promo'], 'price': 47.0, 'quantity': 3, 'product_id': 38}),
 (842, 'add_to_cart', {'tags': ['clearance'], 'price': 52.0, 'quantity': 3, 'product_id': 43}),
 (847, 'add_to_cart', {'tags': ['new'], 'price': 57.0, 'quantity': 3, 'product_id': 48}),
 (852, 'add_to_cart', {'tags': ['promo'], 'price': 62.0, 'quantity': 3, 'product_id': 53}),
 (857, 'add_to_cart', {'tags': ['clearance'], 'price': 67.0, 'quantity': 3, 'product_id': 58}),
 (862, 'add_to_cart', {'tags': ['new'], 'price': 72.0, 'quantity': 3, 'product_id': 63}),
 (867, 'add_to_cart', {'tags': ['promo'], 'price': 77.0, 'quantity': 3, 'product_id': 68}),
 (872, 'add_to_cart', {'tags': ['clearance'], 'price': 82.0, 'quantity': 3, 'product_id': 73}),
 (877, 'add_to_cart', {'tags': ['new'], 'price': 87.0, 'quantity': 3, 'product_id': 78}),
 (882, 'add_to_cart', {'tags': ['promo'], 'price': 92.0, 'quantity': 3, 'product_id': 83}),
 (887, 'add_to_cart', {'tags': ['clearance'], 'price': 97.0, 'quantity': 3, 'product_id': 88}),
 (892, 'add_to_cart', {'tags': ['new'], 'price': 102.0, 'quantity': 3, 'product_id': 93}),
 (897, 'add_to_cart', {'tags': ['promo'], 'price': 107.0, 'quantity': 3, 'product_id': 98}),
 (902, 'add_to_cart', {'tags': ['clearance'], 'price': 12.0, 'quantity': 3, 'product_id': 103}),
 (907, 'add_to_cart', {'tags': ['new'], 'price': 17.0, 'quantity': 3, 'product_id': 108}),
 (912, 'add_to_cart', {'tags': ['promo'], 'price': 22.0, 'quantity': 3, 'product_id': 113}),
 (917, 'add_to_cart', {'tags': ['clearance'], 'price': 27.0, 'quantity': 3, 'product_id': 118}),
 (922, 'add_to_cart', {'tags': ['new'], 'price': 32.0, 'quantity': 3, 'product_id': 123}),
 (927, 'add_to_cart', {'tags': ['promo'], 'price': 37.0, 'quantity': 3, 'product_id': 128}),
 (932, 'add_to_cart', {'tags': ['clearance'], 'price': 42.0, 'quantity': 3, 'product_id': 133}),
 (937, 'add_to_cart', {'tags': ['new'], 'price': 47.0, 'quantity': 3, 'product_id': 138}),
 (942, 'add_to_cart', {'tags': ['promo'], 'price': 52.0, 'quantity': 3, 'product_id': 143}),
 (947, 'add_to_cart', {'tags': ['clearance'], 'price': 57.0, 'quantity': 3, 'product_id': 148}),
 (952, 'add_to_cart', {'tags': ['new'], 'price': 62.0, 'quantity': 3, 'product_id': 153}),
 (957, 'add_to_cart', {'tags': ['promo'], 'price': 67.0, 'quantity': 3, 'product_id': 158}),
 (962, 'add_to_cart', {'tags': ['clearance'], 'price': 72.0, 'quantity': 3, 'product_id': 163}),
 (967, 'add_to_cart', {'tags': ['new'], 'price': 77.0, 'quantity': 3, 'product_id': 168}),
 (972, 'add_to_cart', {'tags': ['promo'], 'price': 82.0, 'quantity': 3, 'product_id': 173}),
 (977, 'add_to_cart', {'tags': ['clearance'], 'price': 87.0, 'quantity': 3, 'product_id': 178}),
 (982, 'add_to_cart', {'tags': ['new'], 'price': 92.0, 'quantity': 3, 'product_id': 183}),
 (987, 'add_to_cart', {'tags': ['promo'], 'price': 97.0, 'quantity': 3, 'product_id': 188}),
 (992, 'add_to_cart', {'tags': ['clearance'], 'price': 102.0, 'quantity': 3, 'product_id': 193}),
 (997, 'add_to_cart', {'tags': ['new'], 'price': 107.0, 'quantity': 3, 'product_id': 198}),
 (1002, 'add_to_cart', {'tags': ['promo'], 'price': 12.0, 'quantity': 3, 'product_id': 3}),
 (1007, 'add_to_cart', {'tags': ['clearance'], 'price': 17.0, 'quantity': 3, 'product_id': 8}),
 (1012, 'add_to_cart', {'tags': ['new'], 'price': 22.0, 'quantity': 3, 'product_id': 13}),
 (1017, 'add_to_cart', {'tags': ['promo'], 'price': 27.0, 'quantity': 3, 'product_id': 18}),
 (1022, 'add_to_cart', {'tags': ['clearance'], 'price': 32.0, 'quantity': 3, 'product_id': 23}),
 (1027, 'add_to_cart', {'tags': ['new'], 'price': 37.0, 'quantity': 3, 'product_id': 28}),
 (1032, 'add_to_cart', {'tags': ['promo'], 'price': 42.0, 'quantity': 3, 'product_id': 33}),
 (1037, 'add_to_cart', {'tags': ['clearance'], 'price': 47.0, 'quantity': 3, 'product_id': 38}),
 (1042, 'add_to_cart', {'tags': ['new'], 'price': 52.0, 'quantity': 3, 'product_id': 43}),
 (1047, 'add_to_cart', {'tags': ['promo'], 'price': 57.0, 'quantity': 3, 'product_id': 48}),
 (1052, 'add_to_cart', {'tags': ['clearance'], 'price': 62.0, 'quantity': 3, 'product_id': 53}),
 (1057, 'add_to_cart', {'tags': ['new'], 'price': 67.0, 'quantity': 3, 'product_id': 58}),
 (1062, 'add_to_cart', {'tags': ['promo'], 'price': 72.0, 'quantity': 3, 'product_id': 63}),
 (1067, 'add_to_cart', {'tags': ['clearance'], 'price': 77.0, 'quantity': 3, 'product_id': 68}),

In [33]:
%%sql
SELECT
    event_id,
    event_type,
    payload
FROM t7_hw_events
WHERE payload ?| ARRAY['experiment', 'model_version']
ORDER BY event_id;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
10000 rows affected.

[(4, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [5, 6, 7]}),
 (9, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [10, 11, 12]}),
 (14, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [15, 16, 17]}),
 (19, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [20, 21, 22]}),
 (24, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [25, 26, 27]}),
 (29, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [30, 31, 32]}),
 (34, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [35, 36, 37]}),
 (39, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [40, 41, 42]}),
 (44, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [45, 46, 47]}),
 (49, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [50, 51, 52]}),
 (54, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [55, 56, 57]}),
 (59, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [60, 61, 62]}),
 (64, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [65, 66, 67]}),
 (69, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [70, 71, 72]}),
 (74, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [75, 76, 77]}),
 (79, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [80, 81, 82]}),
 (84, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [85, 86, 87]}),
 (89, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [90, 91, 92]}),
 (94, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [95, 96, 97]}),
 (99, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [100, 101, 102]}),
 (104, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [105, 106, 107]}),
 (109, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [110, 111, 112]}),
 (114, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [115, 116, 117]}),
 (119, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [120, 121, 122]}),
 (124, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [125, 126, 127]}),
 (129, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [130, 131, 132]}),
 (134, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [135, 136, 137]}),
 (139, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [140, 141, 142]}),
 (144, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [145, 146, 147]}),
 (149, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [150, 151, 152]}),
 (154, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [155, 156, 157]}),
 (159, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [160, 161, 162]}),
 (164, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [165, 166, 167]}),
 (169, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [170, 171, 172]}),
 (174, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [175, 176, 177]}),
 (179, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [180, 181, 182]}),
 (184, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [185, 186, 187]}),
 (189, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [190, 191, 192]}),
 (194, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [195, 196, 197]}),
 (199, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [200, 1, 2]}),
 (204, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [5, 6, 7]}),
 (209, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [10, 11, 12]}),
 (214, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [15, 16, 17]}),
 (219, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [20, 21, 22]}),
 (224, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [25, 26, 27]}),
 (229, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [30, 31, 32]}),
 (234, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [35, 36, 37]}),
 (239, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [40, 41, 42]}),
 (244, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [45, 46, 47]}),
 (249, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [50, 51, 52]}),
 (254, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [55, 56, 57]}),
 (259, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [60, 61, 62]}),
 (264, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [65, 66, 67]}),
 (269, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [70, 71, 72]}),
 (274, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [75, 76, 77]}),
 (279, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [80, 81, 82]}),
 (284, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [85, 86, 87]}),
 (289, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [90, 91, 92]}),
 (294, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [95, 96, 97]}),
 (299, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [100, 101, 102]}),
 (304, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [105, 106, 107]}),
 (309, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [110, 111, 112]}),
 (314, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [115, 116, 117]}),
 (319, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [120, 121, 122]}),
 (324, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [125, 126, 127]}),
 (329, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [130, 131, 132]}),
 (334, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [135, 136, 137]}),
 (339, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [140, 141, 142]}),
 (344, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [145, 146, 147]}),
 (349, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [150, 151, 152]}),
 (354, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [155, 156, 157]}),
 (359, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [160, 161, 162]}),
 (364, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [165, 166, 167]}),
 (369, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [170, 171, 172]}),
 (374, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [175, 176, 177]}),
 (379, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [180, 181, 182]}),
 (384, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [185, 186, 187]}),
 (389, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [190, 191, 192]}),
 (394, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [195, 196, 197]}),
 (399, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [200, 1, 2]}),
 (404, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [5, 6, 7]}),
 (409, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [10, 11, 12]}),
 (414, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [15, 16, 17]}),
 (419, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [20, 21, 22]}),
 (424, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [25, 26, 27]}),
 (429, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [30, 31, 32]}),
 (434, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [35, 36, 37]}),
 (439, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [40, 41, 42]}),
 (444, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [45, 46, 47]}),
 (449, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [50, 51, 52]}),
 (454, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [55, 56, 57]}),
 (459, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [60, 61, 62]}),
 (464, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [65, 66, 67]}),
 (469, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [70, 71, 72]}),
 (474, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [75, 76, 77]}),
 (479, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [80, 81, 82]}),
 (484, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [85, 86, 87]}),
 (489, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [90, 91, 92]}),
 (494, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [95, 96, 97]}),
 (499, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [100, 101, 102]}),
 (504, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [105, 106, 107]}),
 (509, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [110, 111, 112]}),
 (514, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [115, 116, 117]}),
 (519, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [120, 121, 122]}),
 (524, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [125, 126, 127]}),
 (529, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [130, 131, 132]}),
 (534, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [135, 136, 137]}),
 (539, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [140, 141, 142]}),
 (544, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [145, 146, 147]}),
 (549, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [150, 151, 152]}),
 (554, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [155, 156, 157]}),
 (559, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [160, 161, 162]}),
 (564, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [165, 166, 167]}),
 (569, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [170, 171, 172]}),
 (574, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [175, 176, 177]}),
 (579, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [180, 181, 182]}),
 (584, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [185, 186, 187]}),
 (589, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [190, 191, 192]}),
 (594, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [195, 196, 197]}),
 (599, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [200, 1, 2]}),
 (604, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [5, 6, 7]}),
 (609, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [10, 11, 12]}),
 (614, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [15, 16, 17]}),
 (619, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [20, 21, 22]}),
 (624, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [25, 26, 27]}),
 (629, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [30, 31, 32]}),
 (634, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [35, 36, 37]}),
 (639, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [40, 41, 42]}),
 (644, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [45, 46, 47]}),
 (649, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [50, 51, 52]}),
 (654, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [55, 56, 57]}),
 (659, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [60, 61, 62]}),
 (664, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [65, 66, 67]}),
 (669, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [70, 71, 72]}),
 (674, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [75, 76, 77]}),
 (679, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [80, 81, 82]}),
 (684, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [85, 86, 87]}),
 (689, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [90, 91, 92]}),
 (694, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [95, 96, 97]}),
 (699, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [100, 101, 102]}),
 (704, 'recommendation_shown', {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [105, 106, 107]}),
 (709, 'recommendation_shown', {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [110, 111, 112]}),
 (714, 'recommendation_shown', {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [115, 116, 117]}),

### JSONB Query 3. JSONPath (`jsonb_path_query`, `jsonb_path_exists`)

In [34]:
%%sql
SELECT
    event_id,
    jsonb_path_query(payload, '$.recommendations[*]') AS recommended_pid
FROM t7_hw_events
WHERE event_type = 'recommendation_shown'
ORDER BY event_id;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
30000 rows affected.

[(4, 5),
 (4, 6),
 (4, 7),
 (9, 10),
 (9, 11),
 (9, 12),
 (14, 15),
 (14, 16),
 (14, 17),
 (19, 20),
 (19, 21),
 (19, 22),
 (24, 25),
 (24, 26),
 (24, 27),
 (29, 30),
 (29, 31),
 (29, 32),
 (34, 35),
 (34, 36),
 (34, 37),
 (39, 40),
 (39, 41),
 (39, 42),
 (44, 45),
 (44, 46),
 (44, 47),
 (49, 50),
 (49, 51),
 (49, 52),
 (54, 55),
 (54, 56),
 (54, 57),
 (59, 60),
 (59, 61),
 (59, 62),
 (64, 65),
 (64, 66),
 (64, 67),
 (69, 70),
 (69, 71),
 (69, 72),
 (74, 75),
 (74, 76),
 (74, 77),
 (79, 80),
 (79, 81),
 (79, 82),
 (84, 85),
 (84, 86),
 (84, 87),
 (89, 90),
 (89, 91),
 (89, 92),
 (94, 95),
 (94, 96),
 (94, 97),
 (99, 100),
 (99, 101),
 (99, 102),
 (104, 105),
 (104, 106),
 (104, 107),
 (109, 110),
 (109, 111),
 (109, 112),
 (114, 115),
 (114, 116),
 (114, 117),
 (119, 120),
 (119, 121),
 (119, 122),
 (124, 125),
 (124, 126),
 (124, 127),
 (129, 130),
 (129, 131),
 (129, 132),
 (134, 135),
 (134, 136),
 (134, 137),
 (139, 140),
 (139, 141),
 (139, 142),
 (144, 145),
 (144, 146),
 (144, 147),
 (149, 150),
 (149, 151),
 (149, 152),
 (154, 155),
 (154, 156),
 (154, 157),
 (159, 160),
 (159, 161),
 (159, 162),
 (164, 165),
 (164, 166),
 (164, 167),
 (169, 170),
 (169, 171),
 (169, 172),
 (174, 175),
 (174, 176),
 (174, 177),
 (179, 180),
 (179, 181),
 (179, 182),
 (184, 185),
 (184, 186),
 (184, 187),
 (189, 190),
 (189, 191),
 (189, 192),
 (194, 195),
 (194, 196),
 (194, 197),
 (199, 200),
 (199, 1),
 (199, 2),
 (204, 5),
 (204, 6),
 (204, 7),
 (209, 10),
 (209, 11),
 (209, 12),
 (214, 15),
 (214, 16),
 (214, 17),
 (219, 20),
 (219, 21),
 (219, 22),
 (224, 25),
 (224, 26),
 (224, 27),
 (229, 30),
 (229, 31),
 (229, 32),
 (234, 35),
 (234, 36),
 (234, 37),
 (239, 40),
 (239, 41),
 (239, 42),
 (244, 45),
 (244, 46),
 (244, 47),
 (249, 50),
 (249, 51),
 (249, 52),
 (254, 55),
 (254, 56),
 (254, 57),
 (259, 60),
 (259, 61),
 (259, 62),
 (264, 65),
 (264, 66),
 (264, 67),
 (269, 70),
 (269, 71),
 (269, 72),
 (274, 75),
 (274, 76),
 (274, 77),
 (279, 80),
 (279, 81),
 (279, 82),
 (284, 85),
 (284, 86),
 (284, 87),
 (289, 90),
 (289, 91),
 (289, 92),
 (294, 95),
 (294, 96),
 (294, 97),
 (299, 100),
 (299, 101),
 (299, 102),
 (304, 105),
 (304, 106),
 (304, 107),
 (309, 110),
 (309, 111),
 (309, 112),
 (314, 115),
 (314, 116),
 (314, 117),
 (319, 120),
 (319, 121),
 (319, 122),
 (324, 125),
 (324, 126),
 (324, 127),
 (329, 130),
 (329, 131),
 (329, 132),
 (334, 135),
 (334, 136),
 (334, 137),
 (339, 140),
 (339, 141),
 (339, 142),
 (344, 145),
 (344, 146),
 (344, 147),
 (349, 150),
 (349, 151),
 (349, 152),
 (354, 155),
 (354, 156),
 (354, 157),
 (359, 160),
 (359, 161),
 (359, 162),
 (364, 165),
 (364, 166),
 (364, 167),
 (369, 170),
 (369, 171),
 (369, 172),
 (374, 175),
 (374, 176),
 (374, 177),
 (379, 180),
 (379, 181),
 (379, 182),
 (384, 185),
 (384, 186),
 (384, 187),
 (389, 190),
 (389, 191),
 (389, 192),
 (394, 195),
 (394, 196),
 (394, 197),
 (399, 200),
 (399, 1),
 (399, 2),
 (404, 5),
 (404, 6),
 (404, 7),
 (409, 10),
 (409, 11),
 (409, 12),
 (414, 15),
 (414, 16),
 (414, 17),
 (419, 20),
 (419, 21),
 (419, 22),
 (424, 25),
 (424, 26),
 (424, 27),
 (429, 30),
 (429, 31),
 (429, 32),
 (434, 35),
 (434, 36),
 (434, 37),
 (439, 40),
 (439, 41),
 (439, 42),
 (444, 45),
 (444, 46),
 (444, 47),
 (449, 50),
 (449, 51),
 (449, 52),
 (454, 55),
 (454, 56),
 (454, 57),
 (459, 60),
 (459, 61),
 (459, 62),
 (464, 65),
 (464, 66),
 (464, 67),
 (469, 70),
 (469, 71),
 (469, 72),
 (474, 75),
 (474, 76),
 (474, 77),
 (479, 80),
 (479, 81),
 (479, 82),
 (484, 85),
 (484, 86),
 (484, 87),
 (489, 90),
 (489, 91),
 (489, 92),
 (494, 95),
 (494, 96),
 (494, 97),
 (499, 100),
 (499, 101),
 (499, 102),
 (504, 105),
 (504, 106),
 (504, 107),
 (509, 110),
 (509, 111),
 (509, 112),
 (514, 115),
 (514, 116),
 (514, 117),
 (519, 120),
 (519, 121),
 (519, 122),
 (524, 125),
 (524, 126),
 (524, 127),
 (529, 130),
 (529, 131),
 (529, 132),
 (534, 135),
 (534, 136),
 (534, 137),
 (539, 140),
 (539, 141),
 (539, 142),
 (544, 145),
 (544, 146),
 (544, 147),
 (549, 150),
 (549, 151),
 (549, 152),
 (554, 155),
 (554, 156),
 (554, 157),
 (559, 160),
 (559, 161),
 (559, 162),
 (564, 165),
 (564, 166),
 (564, 167),
 (569, 170),
 (569, 171),
 (569, 172),
 (574, 175),
 (574, 176),
 (574, 177),
 (579, 180),
 (579, 181),
 (579, 182),
 (584, 185),
 (584, 186),
 (584, 187),
 (589, 190),
 (589, 191),
 (589, 192),
 (594, 195),
 (594, 196),
 (594, 197),
 (599, 200),
 (599, 1),
 (599, 2),
 (604, 5),
 (604, 6),
 (604, 7),
 (609, 10),
 (609, 11),
 (609, 12),
 (614, 15),
 (614, 16),
 (614, 17),
 (619, 20),
 (619, 21),
 (619, 22),
 (624, 25),
 (624, 26),
 (624, 27),
 (629, 30),
 (629, 31),
 (629, 32),
 (634, 35),
 (634, 36),
 (634, 37),
 (639, 40),
 (639, 41),
 (639, 42),
 (644, 45),
 (644, 46),
 (644, 47),
 (649, 50),
 (649, 51),
 (649, 52),
 (654, 55),
 (654, 56),
 (654, 57),
 (659, 60),
 (659, 61),
 (659, 62),
 (664, 65),
 (664, 66),
 (664, 67),
 (669, 70),
 (669, 71),
 (669, 72),
 (674, 75),
 (674, 76),
 (674, 77),
 (679, 80),
 (679, 81),
 (679, 82),
 (684, 85),
 (684, 86),
 (684, 87),
 (689, 90),
 (689, 91),
 (689, 92),
 (694, 95),
 (694, 96),
 (694, 97),
 (699, 100),
 (699, 101),
 (699, 102),
 (704, 105),
 (704, 106),
 (704, 107),
 (709, 110),
 (709, 111),
 (709, 112),
 (714, 115),
 (714, 116),
 (714, 117),
 (719, 120),
 (719, 121),
 (719, 122),
 (724, 125),
 (724, 126),
 (724, 127),
 (729, 130),
 (729, 131),
 (729, 132),
 (734, 135),
 (734, 136),
 (734, 137),
 (739, 140),
 (739, 141),
 (739, 142),
 (744, 145),
 (744, 146),
 (744, 147),
 (749, 150),
 (749, 151),
 (749, 152),
 (754, 155),
 (754, 156),
 (754, 157),
 (759, 160),
 (759, 161),
 (759, 162),
 (764, 165),
 (764, 166),
 (764, 167),
 (769, 170),
 (769, 171),
 (769, 172),
 (774, 175),
 (774, 176),
 (774, 177),
 (779, 180),
 (779, 181),
 (779, 182),
 (784, 185),
 (784, 186),
 (784, 187),
 (789, 190),
 (789, 191),
 (789, 192),
 (794, 195),
 (794, 196),
 (794, 197),
 (799, 200),
 (799, 1),
 (799, 2),
 (804, 5),
 (804, 6),
 (804, 7),
 (809, 10),
 (809, 11),
 (809, 12),
 (814, 15),
 (814, 16),
 (814, 17),
 (819, 20),
 (819, 21),
 (819, 22),
 (824, 25),
 (824, 26),
 (824, 27),
 (829, 30),
 (829, 31),
 (829, 32),
 (834, 35),
 (834, 36),
 (834, 37),
 (839, 40),
 (839, 41),
 (839, 42),
 (844, 45),
 (844, 46),
 (844, 47),
 (849, 50),
 (849, 51),
 (849, 52),
 (854, 55),
 (854, 56),
 (854, 57),
 (859, 60),
 (859, 61),
 (859, 62),
 (864, 65),
 (864, 66),
 (864, 67),
 (869, 70),
 (869, 71),
 (869, 72),
 (874, 75),
 (874, 76),
 (874, 77),
 (879, 80),
 (879, 81),
 (879, 82),
 (884, 85),
 (884, 86),
 (884, 87),
 (889, 90),
 (889, 91),
 (889, 92),
 (894, 95),
 (894, 96),
 (894, 97),
 (899, 100),
 (899, 101),
 (899, 102),
 (904, 105),
 (904, 106),
 (904, 107),
 (909, 110),
 (909, 111),
 (909, 112),
 (914, 115),
 (914, 116),
 (914, 117),
 (919, 120),
 (919, 121),
 (919, 122),
 (924, 125),
 (924, 126),
 (924, 127),
 (929, 130),
 (929, 131),
 (929, 132),
 (934, 135),
 (934, 136),
 (934, 137),
 (939, 140),
 (939, 141),
 (939, 142),
 (944, 145),
 (944, 146),
 (944, 147),
 (949, 150),
 (949, 151),
 (949, 152),
 (954, 155),
 (954, 156),
 (954, 157),
 (959, 160),
 (959, 161),
 (959, 162),
 (964, 165),
 (964, 166),
 (964, 167),
 (969, 170),
 (969, 171),
 (969, 172),
 (974, 175),
 (974, 176),
 (974, 177),
 (979, 180),
 (979, 181),
 (979, 182),
 (984, 185),
 (984, 186),
 (984, 187),
 (989, 190),
 (989, 191),
 (989, 192),
 (994, 195),
 (994, 196),
 (994, 197),
 (999, 200),
 (999, 1),
 (999, 2),
 (1004, 5),
 (1004, 6),
 (1004, 7),
 (1009, 10),
 (1009, 11),
 (1009, 12),
 (1014, 15),
 (1014, 16),
 (1014, 17),
 (1019, 20),
 (1019, 21),
 (1019, 22),
 (1024, 25),
 (1024, 26),
 (1024, 27),
 (1029, 30),
 (1029, 31),
 (1029, 32),
 (1034, 35),
 (1034, 36),
 (1034, 37),
 (1039, 40),
 (1039, 41),
 (1039, 42),
 (1044, 45),
 (1044, 46),
 (1044, 47),
 (1049, 50),
 (1049, 51),
 (1049, 52),
 (1054, 55),
 (1054, 56),
 (1054, 57),
 (1059, 60),
 (1059, 61),
 (1059, 62),
 (1064, 65),
 (1064, 66),
 (1064, 67),
 (1069, 70),
 (1069, 71),
 (1069, 72),
 (1074, 75),
 (1074, 76),
 (1074, 77),
 (1079, 80),
 (1079, 81),
 (1079, 82),
 (1084, 85),
 (1084, 86),
 (1084, 87),
 (1089, 90),
 (1089, 91),
 (1089, 92),
 (1094, 95),
 (1094, 96),
 (1094, 97),
 (1099, 100),
 (1099, 101),
 (1099, 102),
 (1104, 105),
 (1104, 106),
 (1104, 107),
 (1109, 110),
 (1109, 111),
 (1109, 112),
 (1114, 115),
 (1114, 116),
 (1114, 117),
 (1119, 120),
 (1119, 121),
 (1119, 122),
 (1124, 125),
 (1124, 126),
 (1124, 127),
 (1129, 130),
 (1129, 131),
 (1129, 132),
 (1134, 135),
 (1134, 136),
 (1134, 137),
 (1139, 140),
 (1139, 141),
 (1139, 142),
 (1144, 145),
 (1144, 146),
 (1144, 147),
 (1149, 150),
 (1149, 151),
 (1149, 152),
 (1154, 155),
 (1154, 156),
 (1154, 157),
 (1159, 160),
 (1159, 161),
 (1159, 162),
 (1164, 165),
 (1164, 166),
 (1164, 167),
 (1169, 170),
 (1169, 171),
 (1169, 172),
 (1174, 175),
 (1174, 176),
 (1174, 177),
 (1179, 180),
 (1179, 181),
 (1179, 182),
 (1184, 185),
 (1184, 186),
 (1184, 187),
 (1189, 190),
 (1189, 191),
 (1189, 192),
 (1194, 195),
 (1194, 196),
 (1194, 197),
 (1199, 200),
 (1199, 1),
 (1199, 2),
 (1204, 5),
 (1204, 6),
 (1204, 7),
 (1209, 10),
 (1209, 11),
 (1209, 12),
 (1214, 15),
 (1214, 16),
 (1214, 17),
 (1219, 20),
 (1219, 21),
 (1219, 22),
 (1224, 25),
 (1224, 26),
 (1224, 27),
 (1229, 30),
 (1229, 31),
 (1229, 32),
 (1234, 35),
 (1234, 36),
 (1234, 37),
 (1239, 40),
 (1239, 41),
 (1239, 42),
 (1244, 45),
 (1244, 46),
 (1244, 47),
 (1249, 50),
 (1249, 51),
 (1249, 52),
 (1254, 55),
 (1254, 56),
 (1254, 57),
 (1259, 60),
 (1259, 61),
 (1259, 62),
 (1264, 65),
 (1264, 66),
 (1264, 67),
 (1269, 70),
 (1269, 71),
 (1269, 72),
 (1274, 75),
 (1274, 76),
 (1274, 77),
 (1279, 80),
 (1279, 81),
 (1279, 82),
 (1284, 85),
 (1284, 86),
 (1284, 87),
 (1289, 90),
 (1289, 91),
 (1289, 92),
 (1294, 95),
 (1294, 96),
 (1294, 97),
 (1299, 100),
 (1299, 101),
 (1299, 102),
 (1304, 105),
 (1304, 106),
 (1304, 107),
 (1309, 110),
 (1309, 111),
 (1309, 112),
 (1314, 115),
 (1314, 116),
 (1314, 117),
 (1319, 120),
 (1319, 121),
 (1319, 122),
 (1324, 125),
 (1324, 126),
 (1324, 127),
 (1329, 130),
 (1329, 131),
 (1329, 132),
 (1334, 135),
 (1334, 136),
 (1334, 137),
 (1339, 140),
 (1339, 141),
 (1339, 142),
 (1344, 145),
 (1344, 146),
 (1344, 147),
 (1349, 150),
 (1349, 151),
 (1349, 152),
 (1354, 155),
 (1354, 156),
 (1354, 157),
 (1359, 160),
 (1359, 161),
 (1359, 162),
 (1364, 165),
 (1364, 166),
 (1364, 167),
 (1369, 170),
 (1369, 171),
 (1369, 172),
 (1374, 175),
 (1374, 176),
 (1374, 177),
 (1379, 180),
 (1379, 181),
 (1379, 182),
 (1384, 185),
 (1384, 186),
 (1384, 187),
 (1389, 190),
 (1389, 191),
 (1389, 192),
 (1394, 195),
 (1394, 196),
 (1394, 197),
 (1399, 200),
 (1399, 1),
 (1399, 2),
 (1404, 5),
 (1404, 6),
 (1404, 7),
 (1409, 10),
 (1409, 11),
 (1409, 12),
 (1414, 15),
 (1414, 16),
 (1414, 17),
 (1419, 20),
 (1419, 21),
 (1419, 22),
 (1424, 25),
 (1424, 26),
 (1424, 27),
 (1429, 30),
 (1429, 31),
 (1429, 32),
 (1434, 35),
 (1434, 36),
 (1434, 37),
 (1439, 40),
 (1439, 41),
 (1439, 42),
 (1444, 45),
 (1444, 46),
 (1444, 47),
 (1449, 50),
 (1449, 51),
 (1449, 52),
 (1454, 55),
 (1454, 56),
 (1454, 57),
 (1459, 60),
 (1459, 61),
 (1459, 62),
 (1464, 65),
 (1464, 66),
 (1464, 67),
 (1469, 70),
 (1469, 71),
 (1469, 72),
 (1474, 75),
 (1474, 76),
 (1474, 77),
 (1479, 80),
 (1479, 81),
 (1479, 82),
 (1484, 85),
 (1484, 86),
 (1484, 87),
 (1489, 90),
 (1489, 91),
 (1489, 92),
 (1494, 95),
 (1494, 96),
 (1494, 97),
 (1499, 100),
 (1499, 101),
 (1499, 102),
 (1504, 105),
 (1504, 106),
 (1504, 107),
 (1509, 110),
 (1509, 111),
 (1509, 112),
 (1514, 115),
 (1514, 116),
 (1514, 117),
 (1519, 120),
 (1519, 121),
 (1519, 122),
 (1524, 125),
 (1524, 126),
 (1524, 127),
 (1529, 130),
 (1529, 131),
 (1529, 132),
 (1534, 135),
 (1534, 136),
 (1534, 137),
 (1539, 140),
 (1539, 141),
 (1539, 142),
 (1544, 145),
 (1544, 146),
 (1544, 147),
 (1549, 150),
 (1549, 151),
 (1549, 152),
 (1554, 155),
 (1554, 156),
 (1554, 157),
 (1559, 160),
 (1559, 161),
 (1559, 162),
 (1564, 165),
 (1564, 166),
 (1564, 167),
 (1569, 170),
 (1569, 171),
 (1569, 172),
 (1574, 175),
 (1574, 176),
 (1574, 177),
 (1579, 180),
 (1579, 181),
 (1579, 182),
 (1584, 185),
 (1584, 186),
 (1584, 187),
 (1589, 190),
 (1589, 191),
 (1589, 192),
 (1594, 195),
 (1594, 196),
 (1594, 197),
 (1599, 200),
 (1599, 1),
 (1599, 2),
 (1604, 5),
 (1604, 6),
 (1604, 7),
 (1609, 10),
 (1609, 11),
 (1609, 12),
 (1614, 15),
 (1614, 16),
 (1614, 17),
 (1619, 20),
 (1619, 21),
 (1619, 22),
 (1624, 25),
 (1624, 26),
 (1624, 27),
 (1629, 30),
 (1629, 31),
 (1629, 32),
 (1634, 35),
 (1634, 36),
 (1634, 37),
 (1639, 40),
 (1639, 41),
 (1639, 42),
 (1644, 45),
 (1644, 46),
 (1644, 47),
 (1649, 50),
 (1649, 51),
 (1649, 52),
 (1654, 55),
 (1654, 56),
 (1654, 57),
 (1659, 60),
 (1659, 61),
 (1659, 62),
 (1664, 65),
 (1664, 66),
 (1664, 67),
 (1669, 70),
 ...]

In [35]:
%%sql
SELECT
    event_id,
    payload ->> 'order_id' AS order_id,
    (payload ->> 'total')::NUMERIC(10, 2) AS total
FROM t7_hw_events
WHERE event_type = 'checkout'
  AND jsonb_path_exists(payload, '$.total ? (@ > 300)')
ORDER BY event_id;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
5000 rows affected.

[(253, 'o_100253', Decimal('303.00')),
 (258, 'o_100258', Decimal('308.00')),
 (263, 'o_100263', Decimal('313.00')),
 (268, 'o_100268', Decimal('318.00')),
 (273, 'o_100273', Decimal('323.00')),
 (278, 'o_100278', Decimal('328.00')),
 (283, 'o_100283', Decimal('333.00')),
 (288, 'o_100288', Decimal('338.00')),
 (293, 'o_100293', Decimal('343.00')),
 (298, 'o_100298', Decimal('348.00')),
 (303, 'o_100303', Decimal('353.00')),
 (308, 'o_100308', Decimal('358.00')),
 (313, 'o_100313', Decimal('363.00')),
 (318, 'o_100318', Decimal('368.00')),
 (323, 'o_100323', Decimal('373.00')),
 (328, 'o_100328', Decimal('378.00')),
 (333, 'o_100333', Decimal('383.00')),
 (338, 'o_100338', Decimal('388.00')),
 (343, 'o_100343', Decimal('393.00')),
 (348, 'o_100348', Decimal('398.00')),
 (353, 'o_100353', Decimal('403.00')),
 (358, 'o_100358', Decimal('408.00')),
 (363, 'o_100363', Decimal('413.00')),
 (368, 'o_100368', Decimal('418.00')),
 (373, 'o_100373', Decimal('423.00')),
 (378, 'o_100378', Decimal('428.00')),
 (383, 'o_100383', Decimal('433.00')),
 (388, 'o_100388', Decimal('438.00')),
 (393, 'o_100393', Decimal('443.00')),
 (398, 'o_100398', Decimal('448.00')),
 (403, 'o_100403', Decimal('453.00')),
 (408, 'o_100408', Decimal('458.00')),
 (413, 'o_100413', Decimal('463.00')),
 (418, 'o_100418', Decimal('468.00')),
 (423, 'o_100423', Decimal('473.00')),
 (428, 'o_100428', Decimal('478.00')),
 (433, 'o_100433', Decimal('483.00')),
 (438, 'o_100438', Decimal('488.00')),
 (443, 'o_100443', Decimal('493.00')),
 (448, 'o_100448', Decimal('498.00')),
 (453, 'o_100453', Decimal('503.00')),
 (458, 'o_100458', Decimal('508.00')),
 (463, 'o_100463', Decimal('513.00')),
 (468, 'o_100468', Decimal('518.00')),
 (473, 'o_100473', Decimal('523.00')),
 (478, 'o_100478', Decimal('528.00')),
 (483, 'o_100483', Decimal('533.00')),
 (488, 'o_100488', Decimal('538.00')),
 (493, 'o_100493', Decimal('543.00')),
 (498, 'o_100498', Decimal('548.00')),
 (753, 'o_100753', Decimal('303.00')),
 (758, 'o_100758', Decimal('308.00')),
 (763, 'o_100763', Decimal('313.00')),
 (768, 'o_100768', Decimal('318.00')),
 (773, 'o_100773', Decimal('323.00')),
 (778, 'o_100778', Decimal('328.00')),
 (783, 'o_100783', Decimal('333.00')),
 (788, 'o_100788', Decimal('338.00')),
 (793, 'o_100793', Decimal('343.00')),
 (798, 'o_100798', Decimal('348.00')),
 (803, 'o_100803', Decimal('353.00')),
 (808, 'o_100808', Decimal('358.00')),
 (813, 'o_100813', Decimal('363.00')),
 (818, 'o_100818', Decimal('368.00')),
 (823, 'o_100823', Decimal('373.00')),
 (828, 'o_100828', Decimal('378.00')),
 (833, 'o_100833', Decimal('383.00')),
 (838, 'o_100838', Decimal('388.00')),
 (843, 'o_100843', Decimal('393.00')),
 (848, 'o_100848', Decimal('398.00')),
 (853, 'o_100853', Decimal('403.00')),
 (858, 'o_100858', Decimal('408.00')),
 (863, 'o_100863', Decimal('413.00')),
 (868, 'o_100868', Decimal('418.00')),
 (873, 'o_100873', Decimal('423.00')),
 (878, 'o_100878', Decimal('428.00')),
 (883, 'o_100883', Decimal('433.00')),
 (888, 'o_100888', Decimal('438.00')),
 (893, 'o_100893', Decimal('443.00')),
 (898, 'o_100898', Decimal('448.00')),
 (903, 'o_100903', Decimal('453.00')),
 (908, 'o_100908', Decimal('458.00')),
 (913, 'o_100913', Decimal('463.00')),
 (918, 'o_100918', Decimal('468.00')),
 (923, 'o_100923', Decimal('473.00')),
 (928, 'o_100928', Decimal('478.00')),
 (933, 'o_100933', Decimal('483.00')),
 (938, 'o_100938', Decimal('488.00')),
 (943, 'o_100943', Decimal('493.00')),
 (948, 'o_100948', Decimal('498.00')),
 (953, 'o_100953', Decimal('503.00')),
 (958, 'o_100958', Decimal('508.00')),
 (963, 'o_100963', Decimal('513.00')),
 (968, 'o_100968', Decimal('518.00')),
 (973, 'o_100973', Decimal('523.00')),
 (978, 'o_100978', Decimal('528.00')),
 (983, 'o_100983', Decimal('533.00')),
 (988, 'o_100988', Decimal('538.00')),
 (993, 'o_100993', Decimal('543.00')),
 (998, 'o_100998', Decimal('548.00')),
 (1253, 'o_101253', Decimal('303.00')),
 (1258, 'o_101258', Decimal('308.00')),
 (1263, 'o_101263', Decimal('313.00')),
 (1268, 'o_101268', Decimal('318.00')),
 (1273, 'o_101273', Decimal('323.00')),
 (1278, 'o_101278', Decimal('328.00')),
 (1283, 'o_101283', Decimal('333.00')),
 (1288, 'o_101288', Decimal('338.00')),
 (1293, 'o_101293', Decimal('343.00')),
 (1298, 'o_101298', Decimal('348.00')),
 (1303, 'o_101303', Decimal('353.00')),
 (1308, 'o_101308', Decimal('358.00')),
 (1313, 'o_101313', Decimal('363.00')),
 (1318, 'o_101318', Decimal('368.00')),
 (1323, 'o_101323', Decimal('373.00')),
 (1328, 'o_101328', Decimal('378.00')),
 (1333, 'o_101333', Decimal('383.00')),
 (1338, 'o_101338', Decimal('388.00')),
 (1343, 'o_101343', Decimal('393.00')),
 (1348, 'o_101348', Decimal('398.00')),
 (1353, 'o_101353', Decimal('403.00')),
 (1358, 'o_101358', Decimal('408.00')),
 (1363, 'o_101363', Decimal('413.00')),
 (1368, 'o_101368', Decimal('418.00')),
 (1373, 'o_101373', Decimal('423.00')),
 (1378, 'o_101378', Decimal('428.00')),
 (1383, 'o_101383', Decimal('433.00')),
 (1388, 'o_101388', Decimal('438.00')),
 (1393, 'o_101393', Decimal('443.00')),
 (1398, 'o_101398', Decimal('448.00')),
 (1403, 'o_101403', Decimal('453.00')),
 (1408, 'o_101408', Decimal('458.00')),
 (1413, 'o_101413', Decimal('463.00')),
 (1418, 'o_101418', Decimal('468.00')),
 (1423, 'o_101423', Decimal('473.00')),
 (1428, 'o_101428', Decimal('478.00')),
 (1433, 'o_101433', Decimal('483.00')),
 (1438, 'o_101438', Decimal('488.00')),
 (1443, 'o_101443', Decimal('493.00')),
 (1448, 'o_101448', Decimal('498.00')),
 (1453, 'o_101453', Decimal('503.00')),
 (1458, 'o_101458', Decimal('508.00')),
 (1463, 'o_101463', Decimal('513.00')),
 (1468, 'o_101468', Decimal('518.00')),
 (1473, 'o_101473', Decimal('523.00')),
 (1478, 'o_101478', Decimal('528.00')),
 (1483, 'o_101483', Decimal('533.00')),
 (1488, 'o_101488', Decimal('538.00')),
 (1493, 'o_101493', Decimal('543.00')),
 (1498, 'o_101498', Decimal('548.00')),
 (1753, 'o_101753', Decimal('303.00')),
 (1758, 'o_101758', Decimal('308.00')),
 (1763, 'o_101763', Decimal('313.00')),
 (1768, 'o_101768', Decimal('318.00')),
 (1773, 'o_101773', Decimal('323.00')),
 (1778, 'o_101778', Decimal('328.00')),
 (1783, 'o_101783', Decimal('333.00')),
 (1788, 'o_101788', Decimal('338.00')),
 (1793, 'o_101793', Decimal('343.00')),
 (1798, 'o_101798', Decimal('348.00')),
 (1803, 'o_101803', Decimal('353.00')),
 (1808, 'o_101808', Decimal('358.00')),
 (1813, 'o_101813', Decimal('363.00')),
 (1818, 'o_101818', Decimal('368.00')),
 (1823, 'o_101823', Decimal('373.00')),
 (1828, 'o_101828', Decimal('378.00')),
 (1833, 'o_101833', Decimal('383.00')),
 (1838, 'o_101838', Decimal('388.00')),
 (1843, 'o_101843', Decimal('393.00')),
 (1848, 'o_101848', Decimal('398.00')),
 (1853, 'o_101853', Decimal('403.00')),
 (1858, 'o_101858', Decimal('408.00')),
 (1863, 'o_101863', Decimal('413.00')),
 (1868, 'o_101868', Decimal('418.00')),
 (1873, 'o_101873', Decimal('423.00')),
 (1878, 'o_101878', Decimal('428.00')),
 (1883, 'o_101883', Decimal('433.00')),
 (1888, 'o_101888', Decimal('438.00')),
 (1893, 'o_101893', Decimal('443.00')),
 (1898, 'o_101898', Decimal('448.00')),
 (1903, 'o_101903', Decimal('453.00')),
 (1908, 'o_101908', Decimal('458.00')),
 (1913, 'o_101913', Decimal('463.00')),
 (1918, 'o_101918', Decimal('468.00')),
 (1923, 'o_101923', Decimal('473.00')),
 (1928, 'o_101928', Decimal('478.00')),
 (1933, 'o_101933', Decimal('483.00')),
 (1938, 'o_101938', Decimal('488.00')),
 (1943, 'o_101943', Decimal('493.00')),
 (1948, 'o_101948', Decimal('498.00')),
 (1953, 'o_101953', Decimal('503.00')),
 (1958, 'o_101958', Decimal('508.00')),
 (1963, 'o_101963', Decimal('513.00')),
 (1968, 'o_101968', Decimal('518.00')),
 (1973, 'o_101973', Decimal('523.00')),
 (1978, 'o_101978', Decimal('528.00')),
 (1983, 'o_101983', Decimal('533.00')),
 (1988, 'o_101988', Decimal('538.00')),
 (1993, 'o_101993', Decimal('543.00')),
 (1998, 'o_101998', Decimal('548.00')),
 (2253, 'o_102253', Decimal('303.00')),
 (2258, 'o_102258', Decimal('308.00')),
 (2263, 'o_102263', Decimal('313.00')),
 (2268, 'o_102268', Decimal('318.00')),
 (2273, 'o_102273', Decimal('323.00')),
 (2278, 'o_102278', Decimal('328.00')),
 (2283, 'o_102283', Decimal('333.00')),
 (2288, 'o_102288', Decimal('338.00')),
 (2293, 'o_102293', Decimal('343.00')),
 (2298, 'o_102298', Decimal('348.00')),
 (2303, 'o_102303', Decimal('353.00')),
 (2308, 'o_102308', Decimal('358.00')),
 (2313, 'o_102313', Decimal('363.00')),
 (2318, 'o_102318', Decimal('368.00')),
 (2323, 'o_102323', Decimal('373.00')),
 (2328, 'o_102328', Decimal('378.00')),
 (2333, 'o_102333', Decimal('383.00')),
 (2338, 'o_102338', Decimal('388.00')),
 (2343, 'o_102343', Decimal('393.00')),
 (2348, 'o_102348', Decimal('398.00')),
 (2353, 'o_102353', Decimal('403.00')),
 (2358, 'o_102358', Decimal('408.00')),
 (2363, 'o_102363', Decimal('413.00')),
 (2368, 'o_102368', Decimal('418.00')),
 (2373, 'o_102373', Decimal('423.00')),
 (2378, 'o_102378', Decimal('428.00')),
 (2383, 'o_102383', Decimal('433.00')),
 (2388, 'o_102388', Decimal('438.00')),
 (2393, 'o_102393', Decimal('443.00')),
 (2398, 'o_102398', Decimal('448.00')),
 (2403, 'o_102403', Decimal('453.00')),
 (2408, 'o_102408', Decimal('458.00')),
 (2413, 'o_102413', Decimal('463.00')),
 (2418, 'o_102418', Decimal('468.00')),
 (2423, 'o_102423', Decimal('473.00')),
 (2428, 'o_102428', Decimal('478.00')),
 (2433, 'o_102433', Decimal('483.00')),
 (2438, 'o_102438', Decimal('488.00')),
 (2443, 'o_102443', Decimal('493.00')),
 (2448, 'o_102448', Decimal('498.00')),
 (2453, 'o_102453', Decimal('503.00')),
 (2458, 'o_102458', Decimal('508.00')),
 (2463, 'o_102463', Decimal('513.00')),
 (2468, 'o_102468', Decimal('518.00')),
 (2473, 'o_102473', Decimal('523.00')),
 (2478, 'o_102478', Decimal('528.00')),
 (2483, 'o_102483', Decimal('533.00')),
 (2488, 'o_102488', Decimal('538.00')),
 (2493, 'o_102493', Decimal('543.00')),
 (2498, 'o_102498', Decimal('548.00')),
 (2753, 'o_102753', Decimal('303.00')),
 (2758, 'o_102758', Decimal('308.00')),
 (2763, 'o_102763', Decimal('313.00')),
 (2768, 'o_102768', Decimal('318.00')),
 (2773, 'o_102773', Decimal('323.00')),
 (2778, 'o_102778', Decimal('328.00')),
 (2783, 'o_102783', Decimal('333.00')),
 (2788, 'o_102788', Decimal('338.00')),
 (2793, 'o_102793', Decimal('343.00')),
 (2798, 'o_102798', Decimal('348.00')),
 (2803, 'o_102803', Decimal('353.00')),
 (2808, 'o_102808', Decimal('358.00')),
 (2813, 'o_102813', Decimal('363.00')),
 (2818, 'o_102818', Decimal('368.00')),
 (2823, 'o_102823', Decimal('373.00')),
 (2828, 'o_102828', Decimal('378.00')),
 (2833, 'o_102833', Decimal('383.00')),
 (2838, 'o_102838', Decimal('388.00')),
 (2843, 'o_102843', Decimal('393.00')),
 (2848, 'o_102848', Decimal('398.00')),
 (2853, 'o_102853', Decimal('403.00')),
 (2858, 'o_102858', Decimal('408.00')),
 (2863, 'o_102863', Decimal('413.00')),
 (2868, 'o_102868', Decimal('418.00')),
 (2873, 'o_102873', Decimal('423.00')),
 (2878, 'o_102878', Decimal('428.00')),
 (2883, 'o_102883', Decimal('433.00')),
 (2888, 'o_102888', Decimal('438.00')),
 (2893, 'o_102893', Decimal('443.00')),
 (2898, 'o_102898', Decimal('448.00')),
 (2903, 'o_102903', Decimal('453.00')),
 (2908, 'o_102908', Decimal('458.00')),
 (2913, 'o_102913', Decimal('463.00')),
 (2918, 'o_102918', Decimal('468.00')),
 (2923, 'o_102923', Decimal('473.00')),
 (2928, 'o_102928', Decimal('478.00')),
 (2933, 'o_102933', Decimal('483.00')),
 (2938, 'o_102938', Decimal('488.00')),
 (2943, 'o_102943', Decimal('493.00')),
 (2948, 'o_102948', Decimal('498.00')),
 (2953, 'o_102953', Decimal('503.00')),
 (2958, 'o_102958', Decimal('508.00')),
 (2963, 'o_102963', Decimal('513.00')),
 (2968, 'o_102968', Decimal('518.00')),
 (2973, 'o_102973', Decimal('523.00')),
 (2978, 'o_102978', Decimal('528.00')),
 (2983, 'o_102983', Decimal('533.00')),
 (2988, 'o_102988', Decimal('538.00')),
 (2993, 'o_102993', Decimal('543.00')),
 (2998, 'o_102998', Decimal('548.00')),
 (3253, 'o_103253', Decimal('303.00')),
 (3258, 'o_103258', Decimal('308.00')),
 (3263, 'o_103263', Decimal('313.00')),
 (3268, 'o_103268', Decimal('318.00')),
 (3273, 'o_103273', Decimal('323.00')),
 (3278, 'o_103278', Decimal('328.00')),
 (3283, 'o_103283', Decimal('333.00')),
 (3288, 'o_103288', Decimal('338.00')),
 (3293, 'o_103293', Decimal('343.00')),
 (3298, 'o_103298', Decimal('348.00')),
 (3303, 'o_103303', Decimal('353.00')),
 (3308, 'o_103308', Decimal('358.00')),
 (3313, 'o_103313', Decimal('363.00')),
 (3318, 'o_103318', Decimal('368.00')),
 (3323, 'o_103323', Decimal('373.00')),
 (3328, 'o_103328', Decimal('378.00')),
 (3333, 'o_103333', Decimal('383.00')),
 (3338, 'o_103338', Decimal('388.00')),
 (3343, 'o_103343', Decimal('393.00')),
 (3348, 'o_103348', Decimal('398.00')),
 (3353, 'o_103353', Decimal('403.00')),
 (3358, 'o_103358', Decimal('408.00')),
 (3363, 'o_103363', Decimal('413.00')),
 (3368, 'o_103368', Decimal('418.00')),
 (3373, 'o_103373', Decimal('423.00')),
 (3378, 'o_103378', Decimal('428.00')),
 (3383, 'o_103383', Decimal('433.00')),
 (3388, 'o_103388', Decimal('438.00')),
 (3393, 'o_103393', Decimal('443.00')),
 (3398, 'o_103398', Decimal('448.00')),
 (3403, 'o_103403', Decimal('453.00')),
 (3408, 'o_103408', Decimal('458.00')),
 (3413, 'o_103413', Decimal('463.00')),
 (3418, 'o_103418', Decimal('468.00')),
 (3423, 'o_103423', Decimal('473.00')),
 (3428, 'o_103428', Decimal('478.00')),
 (3433, 'o_103433', Decimal('483.00')),
 (3438, 'o_103438', Decimal('488.00')),
 (3443, 'o_103443', Decimal('493.00')),
 (3448, 'o_103448', Decimal('498.00')),
 (3453, 'o_103453', Decimal('503.00')),
 (3458, 'o_103458', Decimal('508.00')),
 (3463, 'o_103463', Decimal('513.00')),
 (3468, 'o_103468', Decimal('518.00')),
 (3473, 'o_103473', Decimal('523.00')),
 (3478, 'o_103478', Decimal('528.00')),
 (3483, 'o_103483', Decimal('533.00')),
 (3488, 'o_103488', Decimal('538.00')),
 (3493, 'o_103493', Decimal('543.00')),
 (3498, 'o_103498', Decimal('548.00')),
 (3753, 'o_103753', Decimal('303.00')),
 (3758, 'o_103758', Decimal('308.00')),
 (3763, 'o_103763', Decimal('313.00')),
 (3768, 'o_103768', Decimal('318.00')),
 (3773, 'o_103773', Decimal('323.00')),
 (3778, 'o_103778', Decimal('328.00')),
 (3783, 'o_103783', Decimal('333.00')),
 (3788, 'o_103788', Decimal('338.00')),
 (3793, 'o_103793', Decimal('343.00')),
 (3798, 'o_103798', Decimal('348.00')),
 (3803, 'o_103803', Decimal('353.00')),
 (3808, 'o_103808', Decimal('358.00')),
 (3813, 'o_103813', Decimal('363.00')),
 (3818, 'o_103818', Decimal('368.00')),
 (3823, 'o_103823', Decimal('373.00')),
 (3828, 'o_103828', Decimal('378.00')),
 (3833, 'o_103833', Decimal('383.00')),
 (3838, 'o_103838', Decimal('388.00')),
 (3843, 'o_103843', Decimal('393.00')),
 (3848, 'o_103848', Decimal('398.00')),
 (3853, 'o_103853', Decimal('403.00')),
 (3858, 'o_103858', Decimal('408.00')),
 (3863, 'o_103863', Decimal('413.00')),
 (3868, 'o_103868', Decimal('418.00')),
 (3873, 'o_103873', Decimal('423.00')),
 (3878, 'o_103878', Decimal('428.00')),
 (3883, 'o_103883', Decimal('433.00')),
 (3888, 'o_103888', Decimal('438.00')),
 (3893, 'o_103893', Decimal('443.00')),
 (3898, 'o_103898', Decimal('448.00')),
 (3903, 'o_103903', Decimal('453.00')),
 (3908, 'o_103908', Decimal('458.00')),
 (3913, 'o_103913', Decimal('463.00')),
 (3918, 'o_103918', Decimal('468.00')),
 (3923, 'o_103923', Decimal('473.00')),
 (3928, 'o_103928', Decimal('478.00')),
 (3933, 'o_103933', Decimal('483.00')),
 (3938, 'o_103938', Decimal('488.00')),
 (3943, 'o_103943', Decimal('493.00')),
 (3948, 'o_103948', Decimal('498.00')),
 (3953, 'o_103953', Decimal('503.00')),
 (3958, 'o_103958', Decimal('508.00')),
 (3963, 'o_103963', Decimal('513.00')),
 (3968, 'o_103968', Decimal('518.00')),
 (3973, 'o_103973', Decimal('523.00')),
 (3978, 'o_103978', Decimal('528.00')),
 (3983, 'o_103983', Decimal('533.00')),
 (3988, 'o_103988', Decimal('538.00')),
 (3993, 'o_103993', Decimal('543.00')),
 (3998, 'o_103998', Decimal('548.00')),
 (4253, 'o_104253', Decimal('303.00')),
 (4258, 'o_104258', Decimal('308.00')),
 (4263, 'o_104263', Decimal('313.00')),
 (4268, 'o_104268', Decimal('318.00')),
 (4273, 'o_104273', Decimal('323.00')),
 (4278, 'o_104278', Decimal('328.00')),
 (4283, 'o_104283', Decimal('333.00')),
 (4288, 'o_104288', Decimal('338.00')),
 (4293, 'o_104293', Decimal('343.00')),
 (4298, 'o_104298', Decimal('348.00')),
 (4303, 'o_104303', Decimal('353.00')),
 (4308, 'o_104308', Decimal('358.00')),
 (4313, 'o_104313', Decimal('363.00')),
 (4318, 'o_104318', Decimal('368.00')),
 (4323, 'o_104323', Decimal('373.00')),
 (4328, 'o_104328', Decimal('378.00')),
 (4333, 'o_104333', Decimal('383.00')),
 (4338, 'o_104338', Decimal('388.00')),
 (4343, 'o_104343', Decimal('393.00')),
 (4348, 'o_104348', Decimal('398.00')),
 (4353, 'o_104353', Decimal('403.00')),
 (4358, 'o_104358', Decimal('408.00')),
 (4363, 'o_104363', Decimal('413.00')),
 (4368, 'o_104368', Decimal('418.00')),
 (4373, 'o_104373', Decimal('423.00')),
 (4378, 'o_104378', Decimal('428.00')),
 (4383, 'o_104383', Decimal('433.00')),
 (4388, 'o_104388', Decimal('438.00')),
 (4393, 'o_104393', Decimal('443.00')),
 (4398, 'o_104398', Decimal('448.00')),
 (4403, 'o_104403', Decimal('453.00')),
 (4408, 'o_104408', Decimal('458.00')),
 (4413, 'o_104413', Decimal('463.00')),
 (4418, 'o_104418', Decimal('468.00')),
 (4423, 'o_104423', Decimal('473.00')),
 (4428, 'o_104428', Decimal('478.00')),
 (4433, 'o_104433', Decimal('483.00')),
 (4438, 'o_104438', Decimal('488.00')),
 (4443, 'o_104443', Decimal('493.00')),
 (4448, 'o_104448', Decimal('498.00')),
 (4453, 'o_104453', Decimal('503.00')),
 (4458, 'o_104458', Decimal('508.00')),
 (4463, 'o_104463', Decimal('513.00')),
 (4468, 'o_104468', Decimal('518.00')),
 (4473, 'o_104473', Decimal('523.00')),
 (4478, 'o_104478', Decimal('528.00')),
 (4483, 'o_104483', Decimal('533.00')),
 (4488, 'o_104488', Decimal('538.00')),
 (4493, 'o_104493', Decimal('543.00')),
 (4498, 'o_104498', Decimal('548.00')),
 (4753, 'o_104753', Decimal('303.00')),
 (4758, 'o_104758', Decimal('308.00')),
 (4763, 'o_104763', Decimal('313.00')),
 (4768, 'o_104768', Decimal('318.00')),
 (4773, 'o_104773', Decimal('323.00')),
 (4778, 'o_104778', Decimal('328.00')),
 (4783, 'o_104783', Decimal('333.00')),
 (4788, 'o_104788', Decimal('338.00')),
 (4793, 'o_104793', Decimal('343.00')),
 (4798, 'o_104798', Decimal('348.00')),
 (4803, 'o_104803', Decimal('353.00')),
 (4808, 'o_104808', Decimal('358.00')),
 (4813, 'o_104813', Decimal('363.00')),
 (4818, 'o_104818', Decimal('368.00')),
 (4823, 'o_104823', Decimal('373.00')),
 (4828, 'o_104828', Decimal('378.00')),
 (4833, 'o_104833', Decimal('383.00')),
 (4838, 'o_104838', Decimal('388.00')),
 (4843, 'o_104843', Decimal('393.00')),
 (4848, 'o_104848', Decimal('398.00')),
 (4853, 'o_104853', Decimal('403.00')),
 (4858, 'o_104858', Decimal('408.00')),
 (4863, 'o_104863', Decimal('413.00')),
 (4868, 'o_104868', Decimal('418.00')),
 (4873, 'o_104873', Decimal('423.00')),
 (4878, 'o_104878', Decimal('428.00')),
 (4883, 'o_104883', Decimal('433.00')),
 (4888, 'o_104888', Decimal('438.00')),
 (4893, 'o_104893', Decimal('443.00')),
 (4898, 'o_104898', Decimal('448.00')),
 (4903, 'o_104903', Decimal('453.00')),
 (4908, 'o_104908', Decimal('458.00')),
 (4913, 'o_104913', Decimal('463.00')),
 (4918, 'o_104918', Decimal('468.00')),
 (4923, 'o_104923', Decimal('473.00')),
 (4928, 'o_104928', Decimal('478.00')),
 (4933, 'o_104933', Decimal('483.00')),
 (4938, 'o_104938', Decimal('488.00')),
 (4943, 'o_104943', Decimal('493.00')),
 (4948, 'o_104948', Decimal('498.00')),
 (4953, 'o_104953', Decimal('503.00')),
 (4958, 'o_104958', Decimal('508.00')),
 (4963, 'o_104963', Decimal('513.00')),
 (4968, 'o_104968', Decimal('518.00')),
 (4973, 'o_104973', Decimal('523.00')),
 (4978, 'o_104978', Decimal('528.00')),
 (4983, 'o_104983', Decimal('533.00')),
 (4988, 'o_104988', Decimal('538.00')),
 (4993, 'o_104993', Decimal('543.00')),
 (4998, 'o_104998', Decimal('548.00')),
 (5253, 'o_105253', Decimal('303.00')),
 (5258, 'o_105258', Decimal('308.00')),

## 4. GIN-index demo + `EXPLAIN (ANALYZE, BUFFERS)`

Плани виводяться helper-функцією `explain()`, яка виконує рівно `EXPLAIN (ANALYZE, BUFFERS) <query>` і зберігає output для зведеної таблиці в кінці розділу.

### Step 1. Containment query без GIN-індексу

In [36]:
run_sql('''
DROP INDEX IF EXISTS idx_t7_events_payload_gin_pathops;
DROP INDEX IF EXISTS idx_t7_events_payload_gin_ops;
DROP INDEX IF EXISTS idx_t7_events_device_btree;
ANALYZE t7_hw_events;
''')

explain(
    "1. @> payment_method=card, no index",
    '''
        SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload @> jsonb_build_object('payment_method', 'card');
    '''
)

===== 1. @> payment_method=card, no index =====
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('payment_method', 'card');
--------------------------------------------------------------------------------
Aggregate  (cost=1756.59..1756.60 rows=1 width=8) (actual time=33.951..33.953 rows=1 loops=1)
  Buffers: shared hit=1000
  ->  Seq Scan on t7_hw_events  (cost=0.00..1750.00 rows=2634 width=0) (actual time=0.011..33.767 rows=3334 loops=1)
        Filter: (payload @> jsonb_build_object('payment_method', 'card'))
        Rows Removed by Filter: 46666
        Buffers: shared hit=1000
Planning:
  Buffers: shared hit=81
Planning Time: 0.452 ms
Execution Time: 34.002 ms

### Step 2. GIN-індекс `jsonb_path_ops` для containment / JSONPath workload

In [37]:
%%sql
CREATE INDEX idx_t7_events_payload_gin_pathops
    ON t7_hw_events USING GIN (payload jsonb_path_ops);

ANALYZE t7_hw_events;

SELECT
    pg_size_pretty(
        pg_relation_size('idx_t7_events_payload_gin_pathops')
    ) AS gin_index_size,
    pg_size_pretty(
        pg_relation_size('t7_hw_events')
    ) AS table_size;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
Done.
Done.
1 rows affected.

[('1144 kB', '8000 kB')]

### Step 3. Той самий containment query після GIN

In [38]:
explain(
    "2. @> payment_method=card, GIN jsonb_path_ops",
    '''
        SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload @> jsonb_build_object('payment_method', 'card');

    '''
)

===== 2. @> payment_method=card, GIN jsonb_path_ops =====
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('payment_method', 'card');
--------------------------------------------------------------------------------
Aggregate  (cost=1091.68..1091.69 rows=1 width=8) (actual time=5.353..5.355 rows=1 loops=1)
  Buffers: shared hit=1004
  ->  Bitmap Heap Scan on t7_hw_events  (cost=34.20..1083.47 rows=3285 width=0) (actual time=0.491..5.180 rows=3334 loops=1)
        Recheck Cond: (payload @> jsonb_build_object('payment_method', 'card'))
        Heap Blocks: exact=1000
        Buffers: shared hit=1004
        ->  Bitmap Index Scan on idx_t7_events_payload_gin_pathops  (cost=0.00..33.37 rows=3285 width=0) (actual time=0.371..0.372 rows=3334 loops=1)
              Index Cond: (payload @> jsonb_build_object('payment_method', 'card'))
              Buffers: shared hit=4
Planning:
  Buffers: shared hit=105
Planning Time: 0.490 ms
Execution Time: 5.438 ms

In [39]:
explain(
    "2b. @> referrer=google, GIN jsonb_path_ops",
    '''
        SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload @> jsonb_build_object('referrer', 'google');
    '''
)

===== 2b. @> referrer=google, GIN jsonb_path_ops =====
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('referrer', 'google');
--------------------------------------------------------------------------------
Aggregate  (cost=1071.77..1071.78 rows=1 width=8) (actual time=4.062..4.064 rows=1 loops=1)
  Buffers: shared hit=1004
  ->  Bitmap Heap Scan on t7_hw_events  (cost=26.43..1065.29 rows=2591 width=0) (actual time=0.451..3.935 rows=2500 loops=1)
        Recheck Cond: (payload @> jsonb_build_object('referrer', 'google'))
        Heap Blocks: exact=1000
        Buffers: shared hit=1004
        ->  Bitmap Index Scan on idx_t7_events_payload_gin_pathops  (cost=0.00..25.78 rows=2591 width=0) (actual time=0.333..0.334 rows=2500 loops=1)
              Index Cond: (payload @> jsonb_build_object('referrer', 'google'))
              Buffers: shared hit=4
Planning:
  Buffers: shared hit=105
Planning Time: 0.475 ms
Execution Time: 4.125 ms

### Step 4. Коли GIN не допомагає: path-specific text equality
`payload ->> 'device' = 'mobile'` — це рівність над *виразом*, а не оператор `@>`; GIN-opclass його не підтримує → GIN-індекс не використовується.

In [40]:
explain(
    "3. ->> device = mobile, no expression index (GIN exists)",
    '''
        SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload ->> 'device' = 'mobile';
    '''
)

===== 3. ->> device = mobile, no expression index (GIN exists) =====
SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload ->> 'device' = 'mobile';
--------------------------------------------------------------------------------
Aggregate  (cost=1750.62..1750.63 rows=1 width=8) (actual time=9.389..9.391 rows=1 loops=1)
  Buffers: shared hit=1000
  ->  Seq Scan on t7_hw_events  (cost=0.00..1750.00 rows=250 width=0) (actual time=0.015..8.958 rows=8333 loops=1)
        Filter: ((payload ->> 'device'::text) = 'mobile'::text)
        Rows Removed by Filter: 41667
        Buffers: shared hit=1000
Planning:
  Buffers: shared hit=77
Planning Time: 0.288 ms
Execution Time: 9.461 ms

In [41]:
%%sql
CREATE INDEX idx_t7_events_device_btree
    ON t7_hw_events ((payload ->> 'device'));

ANALYZE t7_hw_events;

SELECT pg_size_pretty(
    pg_relation_size('idx_t7_events_device_btree')
) AS btree_index_size;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
Done.
Done.
1 rows affected.

[('360 kB',)]

In [43]:
explain(
    "4. ->> device = mobile, expression B-tree",
    '''
        SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload ->> 'device' = 'mobile';
    '''
)

===== 4. ->> device = mobile, expression B-tree =====
SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload ->> 'device' = 'mobile';
--------------------------------------------------------------------------------
Aggregate  (cost=1242.93..1242.94 rows=1 width=8) (actual time=5.235..5.236 rows=1 loops=1)
  Buffers: shared hit=1009
  ->  Bitmap Heap Scan on t7_hw_events  (cost=96.94..1222.07 rows=8342 width=0) (actual time=0.577..4.776 rows=8333 loops=1)
        Recheck Cond: ((payload ->> 'device'::text) = 'mobile'::text)
        Heap Blocks: exact=1000
        Buffers: shared hit=1009
        ->  Bitmap Index Scan on idx_t7_events_device_btree  (cost=0.00..94.86 rows=8342 width=0) (actual time=0.439..0.439 rows=8333 loops=1)
              Index Cond: ((payload ->> 'device'::text) = 'mobile'::text)
              Buffers: shared hit=9
Planning:
  Buffers: shared hit=103
Planning Time: 0.619 ms
Execution Time: 5.327 ms

Для порівняння: та сама логіка, переписана як containment, може використати GIN без окремого expression index (семантика майже та сама: `@>` порівнює JSON-значення, `->>` — текст).

In [44]:
explain(
    "4b. @> device=mobile via GIN (rewrite instead of ->>)",
    '''
        SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload @> '{"device": "mobile"}';
    '''
)

===== 4b. @> device=mobile via GIN (rewrite instead of ->>) =====
SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload @> '{"device": "mobile"}';
--------------------------------------------------------------------------------
Aggregate  (cost=1183.74..1183.75 rows=1 width=8) (actual time=9.395..9.398 rows=1 loops=1)
  Buffers: shared hit=1006
  ->  Bitmap Heap Scan on t7_hw_events  (cost=63.25..1163.66 rows=8033 width=0) (actual time=1.174..8.858 rows=8333 loops=1)
        Recheck Cond: (payload @> '{"device": "mobile"}'::jsonb)
        Heap Blocks: exact=1000
        Buffers: shared hit=1006
        ->  Bitmap Index Scan on idx_t7_events_payload_gin_pathops  (cost=0.00..61.24 rows=8033 width=0) (actual time=1.028..1.029 rows=8333 loops=1)
              Index Cond: (payload @> '{"device": "mobile"}'::jsonb)
              Buffers: shared hit=6
Planning:
  Buffers: shared hit=128
Planning Time: 0.696 ms
Execution Time: 9.535 ms

### Step 5 (додатково). `jsonb_path_ops` vs `jsonb_ops` для key existence `?`
`jsonb_path_ops` зберігає хеші шляхів+значень і **не підтримує** `?`/`?|`/`?&`. Default `jsonb_ops` індексує також ключі.

In [45]:
explain(
    "5. ? 'tags', only jsonb_path_ops GIN",
    '''
        SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload ? 'tags';
    '''
)

===== 5. ? 'tags', only jsonb_path_ops GIN =====
SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload ? 'tags';
--------------------------------------------------------------------------------
Aggregate  (cost=1650.07..1650.08 rows=1 width=8) (actual time=15.114..15.116 rows=1 loops=1)
  Buffers: shared hit=1000
  ->  Seq Scan on t7_hw_events  (cost=0.00..1625.00 rows=10029 width=0) (actual time=0.011..14.484 rows=10000 loops=1)
        Filter: (payload ? 'tags'::text)
        Rows Removed by Filter: 40000
        Buffers: shared hit=1000
Planning:
  Buffers: shared hit=121
Planning Time: 0.654 ms
Execution Time: 15.200 ms

In [46]:
%%sql
CREATE INDEX idx_t7_events_payload_gin_ops
    ON t7_hw_events USING GIN (payload);  -- default opclass = jsonb_ops

ANALYZE t7_hw_events;

SELECT indexrelname AS index_name,
       pg_size_pretty(pg_relation_size(indexrelid)) AS index_size
FROM pg_stat_user_indexes
WHERE relname = 't7_hw_events'
ORDER BY pg_relation_size(indexrelid) DESC;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
Done.
Done.
4 rows affected.

[('idx_t7_events_payload_gin_ops', '1696 kB'),
 ('idx_t7_events_payload_gin_pathops', '1144 kB'),
 ('t7_hw_events_pkey', '1112 kB'),
 ('idx_t7_events_device_btree', '360 kB')]

In [47]:
explain(
    "6. ? 'tags', GIN jsonb_ops",
    '''
        SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload ? 'tags';
    '''
)

===== 6. ? 'tags', GIN jsonb_ops =====
SELECT COUNT(*)
        FROM t7_hw_events
        WHERE payload ? 'tags';
--------------------------------------------------------------------------------
Aggregate  (cost=1232.50..1232.51 rows=1 width=8) (actual time=10.734..10.736 rows=1 loops=1)
  Buffers: shared hit=1006
  ->  Bitmap Heap Scan on t7_hw_events  (cost=78.94..1206.91 rows=10237 width=0) (actual time=1.144..10.063 rows=10000 loops=1)
        Recheck Cond: (payload ? 'tags'::text)
        Heap Blocks: exact=1000
        Buffers: shared hit=1006
        ->  Bitmap Index Scan on idx_t7_events_payload_gin_ops  (cost=0.00..76.38 rows=10237 width=0) (actual time=1.010..1.010 rows=10000 loops=1)
              Index Cond: (payload ? 'tags'::text)
              Buffers: shared hit=6
Planning:
  Buffers: shared hit=144
Planning Time: 0.556 ms
Execution Time: 10.847 ms

### Write-cost GIN: вставка 50 000 рядків без / з JSONB-індексами
Read/write trade-off вимірюємо, а не постулюємо: однаковий `INSERT ... SELECT` у копію таблиці без індексів і з усіма трьома JSONB-індексами.

In [49]:
def timed_insert(with_indexes: bool) -> float:
    ddl = """
    DROP TABLE IF EXISTS t7_hw_events_writetest;
    CREATE TABLE t7_hw_events_writetest (LIKE t7_hw_events INCLUDING DEFAULTS);
    """
    if with_indexes:
        ddl += """
            CREATE INDEX ON t7_hw_events_writetest USING GIN (payload jsonb_path_ops);
            CREATE INDEX ON t7_hw_events_writetest USING GIN (payload);
            CREATE INDEX ON t7_hw_events_writetest ((payload ->> 'device'));
        """
    run_sql(ddl)
    t0 = time.perf_counter()
    run_sql(
        """
            INSERT INTO t7_hw_events_writetest
            SELECT *
            FROM t7_hw_events;
        """
    )
    return time.perf_counter() - t0


write_cost = pd.DataFrame({
    "setup": ["no indexes", "GIN path_ops + GIN jsonb_ops + B-tree"],
    "insert_50k_rows_sec": [round(timed_insert(False), 3), round(timed_insert(True), 3)],
})
run_sql("DROP TABLE IF EXISTS t7_hw_events_writetest;")
write_cost["slowdown_x"] = (
    write_cost.insert_50k_rows_sec / write_cost.insert_50k_rows_sec.iloc[0]
).round(1)
write_cost

                                   setup  insert_50k_rows_sec  slowdown_x
0                             no indexes                0.157         1.0
1  GIN path_ops + GIN jsonb_ops + B-tree                0.792         5.0

### Зведена таблиця всіх EXPLAIN-планів (парситься з output-ів вище)

In [50]:
def summarize(label, lines):
    plan = "\n".join(lines)
    top_cost = re.search(r"cost=[\d.]+\.\.([\d.]+)", lines[0]).group(1)
    scan_nodes = re.findall(
        r"(Parallel Seq Scan|Seq Scan|Bitmap Index Scan|Bitmap Heap Scan|"
        r"Index Only Scan|Index Scan)(?: using (\w+))? on",
        plan
    )
    buffers = re.search(r"Buffers: shared hit=(\d+)(?: read=(\d+))?", plan)
    return {
        "query": label,
        "scan nodes": " → ".join(
            dict.fromkeys(n + (f" ({i})" if i else "") for n, i in scan_nodes)
        ),
        "total cost": float(top_cost),
        "shared buffers": int(buffers.group(1)) +
            int(buffers.group(2) or 0) if buffers else None,
        "execution ms": float(
            re.search(r"Execution Time: ([\d.]+) ms", plan).group(1)
        ),
    }

pd.set_option("display.max_colwidth", 120)
explain_summary = pd.DataFrame([summarize(k, v) for k, v in PLANS.items()])
explain_summary

,query,scan nodes,total cost,shared buffers,execution ms
0,"1. @> payment_method=card, no index",Seq Scan,1756.60,1000,34.002
1,"2. @> payment_method=card, GIN jsonb_path_ops",Bitmap Heap Scan → Bitmap Index Scan,1091.69,1004,5.438
2,"2b. @> referrer=google, GIN jsonb_path_ops",Bitmap Heap Scan → Bitmap Index Scan,1071.78,1004,4.125
3,"3. ->> device = mobile, no expression index (GIN exists)",Seq Scan,1750.63,1000,9.461
4,"4. ->> device = mobile, expression B-tree",Bitmap Heap Scan → Bitmap Index Scan,1242.94,1009,5.327
5,4b. @> device=mobile via GIN (rewrite instead of ->>),Bitmap Heap Scan → Bitmap Index Scan,1183.75,1006,9.535
6,"5. ? 'tags', only jsonb_path_ops GIN",Seq Scan,1650.08,1000,15.200
7,"6. ? 'tags', GIN jsonb_ops",Bitmap Heap Scan → Bitmap Index Scan,1232.51,1006,10.847

## 5. JSONB vs normalized

### Step 1. Нормалізована таблиця для `checkout`-подій
Типи й `CHECK`-обмеження тепер перевіряються базою під час запису $-$ у JSONB `total` може бути рядком, а `payment_method` $-$ будь-яким.

In [51]:
%%sql
DROP TABLE IF EXISTS t7_hw_checkouts_norm;

CREATE TABLE t7_hw_checkouts_norm (
    event_id       INTEGER PRIMARY KEY,
    user_id        INTEGER NOT NULL,
    event_ts       TIMESTAMPTZ NOT NULL,
    order_id       TEXT NOT NULL,
    total          NUMERIC(10, 2) NOT NULL,
    items_count    INTEGER NOT NULL CHECK (items_count > 0),
    payment_method TEXT NOT NULL CHECK (
        payment_method IN ('card', 'paypal', 'crypto')
    )
);

INSERT INTO t7_hw_checkouts_norm (
    event_id, user_id, event_ts, order_id, total, items_count, payment_method
)
SELECT
    event_id,
    user_id,
    event_ts,
    payload ->> 'order_id' AS order_id,
    (payload ->> 'total')::NUMERIC(10, 2) AS total,
    (payload ->> 'items_count')::INTEGER AS items_count,
    payload ->> 'payment_method' AS payment_method
FROM t7_hw_events
WHERE event_type = 'checkout';

CREATE INDEX idx_t7_checkouts_norm_pm
    ON t7_hw_checkouts_norm (payment_method);

ANALYZE t7_hw_checkouts_norm;

SELECT
    COUNT(*) AS n_checkouts,
    pg_size_pretty(
        pg_total_relation_size('t7_hw_checkouts_norm')
    ) AS norm_total_size,
    pg_size_pretty(
        pg_total_relation_size('t7_hw_events')
    ) AS events_total_size
FROM t7_hw_checkouts_norm;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
Done.
Done.
10000 rows affected.
Done.
Done.
1 rows affected.

[(10000, '1112 kB', '12 MB')]

### Step 2. Один аналітичний запит двома способами

In [52]:
explain(
    "7. avg total by payment_method — JSONB",
    '''
        SELECT
            payload ->> 'payment_method' AS payment_method,
            AVG((payload ->> 'total')::NUMERIC) AS avg_total,
            COUNT(*) AS n
        FROM t7_hw_events
        WHERE event_type = 'checkout'
        GROUP BY payload ->> 'payment_method'
        ORDER BY avg_total DESC
        LIMIT 3;
    '''
)

===== 7. avg total by payment_method — JSONB =====
SELECT
            payload ->> 'payment_method' AS payment_method,
            AVG((payload ->> 'total')::NUMERIC) AS avg_total,
            COUNT(*) AS n
        FROM t7_hw_events
        WHERE event_type = 'checkout'
        GROUP BY payload ->> 'payment_method'
        ORDER BY avg_total DESC
        LIMIT 3;
--------------------------------------------------------------------------------
Limit  (cost=1954.21..1954.22 rows=3 width=72) (actual time=17.500..17.503 rows=3 loops=1)
  Buffers: shared hit=1003
  ->  Sort  (cost=1954.21..1968.05 rows=5535 width=72) (actual time=17.498..17.500 rows=3 loops=1)
        Sort Key: (avg(((payload ->> 'total'::text))::numeric)) DESC
        Sort Method: quicksort  Memory: 25kB
        Buffers: shared hit=1003
        ->  HashAggregate  (cost=1799.65..1882.68 rows=5535 width=72) (actual time=17.434..17.458 rows=3 loops=1)
              Group Key: (payload ->> 'payment_method'::text)
              Batches: 1  Memory Usage: 217kB
              Buffers: shared hit=1000
              ->  Seq Scan on t7_hw_events  (cost=0.00..1649.95 rows=9980 width=132) (actual time=0.016..10.796 rows=10000 loops=1)
                    Filter: (event_type = 'checkout'::text)
                    Rows Removed by Filter: 40000
                    Buffers: shared hit=1000
Planning:
  Buffers: shared hit=181 dirtied=1
Planning Time: 1.113 ms
Execution Time: 17.713 ms

In [53]:
explain(
    "8. avg total by payment_method — normalized",
    '''
        SELECT
            payment_method,
            AVG(total) AS avg_total,
            COUNT(*) AS n
        FROM t7_hw_checkouts_norm
        GROUP BY payment_method
        ORDER BY avg_total DESC
        LIMIT 3;
    '''
)

===== 8. avg total by payment_method — normalized =====
SELECT
            payment_method,
            AVG(total) AS avg_total,
            COUNT(*) AS n
        FROM t7_hw_checkouts_norm
        GROUP BY payment_method
        ORDER BY avg_total DESC
        LIMIT 3;
--------------------------------------------------------------------------------
Limit  (cost=269.06..269.07 rows=3 width=46) (actual time=7.600..7.604 rows=3 loops=1)
  Buffers: shared hit=97
  ->  Sort  (cost=269.06..269.07 rows=3 width=46) (actual time=7.597..7.599 rows=3 loops=1)
        Sort Key: (avg(total)) DESC
        Sort Method: quicksort  Memory: 25kB
        Buffers: shared hit=97
        ->  HashAggregate  (cost=269.00..269.04 rows=3 width=46) (actual time=7.551..7.555 rows=3 loops=1)
              Group Key: payment_method
              Batches: 1  Memory Usage: 24kB
              Buffers: shared hit=94
              ->  Seq Scan on t7_hw_checkouts_norm  (cost=0.00..194.00 rows=10000 width=11) (actual time=0.008..0.944 rows=10000 loops=1)
                    Buffers: shared hit=94
Planning:
  Buffers: shared hit=117
Planning Time: 2.766 ms
Execution Time: 7.716 ms

In [54]:
# обидва варіанти дають однаковий результат
res_jsonb = pd.read_sql(
    '''
      SELECT
          payload ->> 'payment_method' AS payment_method,
          ROUND(AVG((payload ->> 'total')::NUMERIC), 2) AS avg_total,
          COUNT(*) AS n
      FROM t7_hw_events
      WHERE event_type = 'checkout'
      GROUP BY 1
      ORDER BY avg_total DESC
      LIMIT 3
    ''',
    engine
)
res_norm = pd.read_sql(
    '''
        SELECT
            payment_method,
            ROUND(AVG(total), 2) AS avg_total,
            COUNT(*) AS n
        FROM t7_hw_checkouts_norm
        GROUP BY 1
        ORDER BY avg_total DESC
        LIMIT 3
    ''',
    engine
)
assert res_jsonb.equals(res_norm)
display(res_norm)
display(
    pd.DataFrame(
        [summarize(k, PLANS[k]) for k in PLANS if k.startswith(("7.", "8."))]
    )
)

  payment_method  avg_total     n
0         paypal     300.52  3333
1           card     300.50  3334
2         crypto     300.48  3333

,query,scan nodes,total cost,shared buffers,execution ms
0,7. avg total by payment_method — JSONB,Seq Scan,1954.22,1003,17.713
1,8. avg total by payment_method — normalized,Seq Scan,269.07,97,7.716

### Step 3. Bonus: MongoDB-equivalent (pseudocode $-$ не виконується у PostgreSQL)

```javascript
// MongoDB equivalent: avg total checkout per payment_method, top-3
db.events.aggregate([
  { $match: { event_type: "checkout" } },
  { $group: {
      _id: "$payload.payment_method",
      avg_total: { $avg: { $toDouble: "$payload.total" } },
      n: { $sum: 1 }
  } },
  { $sort: { avg_total: -1 } },
  { $limit: 3 }
]);
// індекс-аналог: db.events.createIndex({ event_type: 1, "payload.payment_method": 1 })
```

**Коментар.**
* **PostgreSQL JSONB**
> зручний, коли поруч потрібні SQL, `JOIN` з нормалізованими таблицями (users, orders, features), ACID-транзакції та одна система для OLTP + аналітики середнього обсягу. Саме так тут: event-log і daily features живуть в одній БД.
* **MongoDB aggregation pipeline**
> природний для document-first workloads: документ $-$ одиниця читання/запису, схема еволюціонує без міграцій, горизонтальне шардування вбудоване; але `$lookup`-join-и і крос-документні транзакції $-$ слабше місце.
* **High-volume raw clickstream**
> (мільярди подій, append-only) дешевше тримати в document store або в data lake (Parquet + Spark/DuckDB/Trino), а в Postgres $-$ лише відібрані/агреговані зрізи; для метрик за часом $-$ TimescaleDB, для online-features із низькою латентністю $-$ Redis.
* **Curated ML features**
> (як `v_t7_hw_taxi_features`, `t7_hw_checkouts_norm`) зручніше тримати в typed SQL-таблицях: типи, `CHECK`, стабільна схема для training/serving, прості B-tree індекси.

## Reflection

*Цифри — зі збереженого запуску (зведена таблиця в кінці Завдання 4); після повторного Run All `actual time` і оцінки `rows` трохи змінюються, оператори плану — ні.*

**1. До і після GIN.**
> `payload @> {"payment_method":"card"}` без індексу: `Seq Scan`, cost **1756.60**, `Rows Removed by Filter: 46666`, **34.0 ms**. Після `GIN jsonb_path_ops` (1144 kB при таблиці 8000 kB) план змінився на `Bitmap Index Scan` (4 буфери, 0.37 ms) $\rightarrow$ `Bitmap Heap Scan`: cost **1091.69**, **5.4 ms** ($\text{~}6\times$). Buffers майже ті самі (1000 $\rightarrow$ 1004, `Heap Blocks: exact=1000`): 3 334 збіги розкидані по всіх сторінках, тож виграш дало не менше I/O, а відмова від перевірки `@>` для 50 000 документів.

**2. Чому GIN не для `->> 'device'`.**
> GIN обслуговує оператори `@>`/`@?`/`?`, а не рівність над виразом. Тому з наявним GIN план 3 лишився `Seq Scan` (9.5 ms) з оцінкою `rows=250` при фактичних 8 333. Expression B-tree (360 kB) дав `Bitmap Index Scan on idx_t7_events_device_btree`: cost 1750.63 $\rightarrow$ **1242.94**, **5.3 ms**, і точну оцінку `rows=8342`. Виграш помірний, бо умова неселективна (~17 % рядків). Аналогічно для `? 'tags'`: з `jsonb_path_ops` $-$ `Seq Scan` (15.2 ms), з `jsonb_ops` $-$ `Bitmap Index Scan` (10.8 ms).

**3. Read/write trade-off.**
> Селективні `@>`/`?` пришвидшуються, але три JSONB-індекси займають $\approx$ 3.2 MB (~40 % таблиці), а `INSERT` 50k рядків сповільнився з **0.157 s до 0.792 s ($\text{~}5\times$)**. Для append-heavy clickstream це суттєво.

**4. JSONB чи normalized.**
> Той самий агрегат: JSONB $-$ `Seq Scan` 50 000 рядків, **1003 буфери**, cost 1954.22, **17.7 ms**, оцінка 5 535 груп замість 3. Normalized $-$ **97 буферів**, cost 269.07, **7.7 ms**, результат ідентичний. JSONB підходить для сирого event-log зі змінними схемами; typed-таблиця $-$ для стабільних полів, які постійно агрегуються, і для curated ML-features.

**5. Новий тип `refund`.**
> У JSONB міграції не потрібно: `INSERT` з `event_type='refund'` і payload `{order_id, amount, reason}`, а наявний GIN покриє його автоматично; варто лише додати валідацію в ingestion. У normalized-підході потрібні `CREATE TABLE t7_hw_refunds_norm (... amount NUMERIC(10,2) CHECK (amount > 0))`, індекси, backfill і оновлення ETL $-$ більше роботи, зате гарантії типів і цілісності.